### ISSUE TITLE
Add cl.replace_message()

### ISSUE THREAD

**Issue by mcai** [Chainlit/chainlit#10]
Oftentimes, we need to update the response to user's query, such as showing the progress (steps) of the generation before the final result comes, so it will be convenient if we can call cl.replace_message() to replace the message(s) that've been sent in the current response.

**Comment by willydouhard** [comment]
I agree, I will include this in the next release!

**Comment by willydouhard** [comment]
added in the `0.2.107` release! see https://docs.chainlit.io/api-reference/message

**Comment by mcai** [comment]
Awesome.
