### ISSUE TITLE
Can chat histories be saved and accessed?

### ISSUE THREAD

**Issue by scooter7** [Chainlit/chainlit#103]
Hi,

Can chat histories be saved and accessed?

Thanks!

**Comment by willydouhard** [comment]
Yes, you can save them with chainlit cloud as described [here](https://docs.chainlit.io/cloud/create-project). A local DB feature is also going to be released soon

**Comment by scooter7** [comment]
Hi @willydouhard , I have the chainlit cloud project ID. But, when I'm logged into Chainlit Cloud, I don't see any menu options that  would indicate being able to find chat histories.

Is that project ID something that needs to be appended to a URL in order to access the chat histories?

Thanks!

**Comment by willydouhard** [comment]
The history is not in the chainlit cloud UI. You should see a new `history` tab in your regular chainlit UI. Also make sure to set the parameter `public` in your config to `false`

**Comment by scooter7** [comment]
Hi @willydouhard , 

So, if I set to false, how would users be able to interact with the app? How would they need to authenticate?

Thanks!

**Comment by willydouhard** [comment]
Right now they will authenticate through our auth0 service. You can add users through the cloud Chainlit UI. We are currently working to allow developers to configure their own oauth.

**Comment by gogi2811** [comment]
Is the local db to store chat enabled?
