### ISSUE TITLE
Avatars overwritten by ChatProfile icon

### ISSUE THREAD

**Issue by thehapyone** [Chainlit/chainlit#1038]
**Describe the bug**
In the new release 1.1.300rc1, when the ChatProfile is used and the chatprofile icon is set, this automatically overwrites the avatar image set in the `/public/avatars/assistant.png` directory
When the icon value is not set, the avatar works as expected.

-- Avatar works here
```
            cl.ChatProfile(
                name="Chat Only",
                default=True
            ),
```
-- Avatar is overwritten by the icon
```
            cl.ChatProfile(
                name="Chat Only",
                icon="https://picsum.photos/200",
                default=True
            ),
```

**Expected behavior**
The ChatProfile icon should not overwrite the avatar images

**Comment by willydouhard** [comment]
To me a chat profile is an  assistant so it makes sense that its icon replaces the default avatar (much like GTPs work in ChatGPT). Interested in having your opinion on that!
