### ISSUE TITLE
Rating on BotReply

### ISSUE THREAD

**Issue by sofianhw** [Chainlit/chainlit#105]
Now on ChatGPT, we can give a rating for the bot's reply from 1 to 5 stars. How do we do that with ChainLit?

**Comment by monuminu** [comment]
+1

**Comment by willydouhard** [comment]
Chainlit `0.4.2` was just released. It comes with [multiple solutions](https://docs.chainlit.io/data) to persist chats and enable users to give feedback.

Here is how the UI looks once you data persistence is enabled:
<img width="991" alt="Screenshot 2023-06-26 at 16 17 28" src="https://github.com/Chainlit/chainlit/assets/13104895/f2d497b5-4568-46dd-aa8f-707b2289e1d5">

As of now, Chainlit does not support "star feedback" but thumbs up or down.

**Comment by sofianhw** [comment]
> Chainlit `0.4.2` was just released. It comes with [multiple solutions](https://docs.chainlit.io/data) to persist chats and enable users to give feedback.
> 
> Here is how the UI looks once you data persistence is enabled: <img alt="Screenshot 2023-06-26 at 16 17 28" width="991" src="https://user-images.githubusercontent.com/13104895/248833688-f2d497b5-4568-46dd-aa8f-707b2289e1d5.png">
> 
> As of now, Chainlit does not support "star feedback" but thumbs up or down.

Cool!
thanks @willydouhard i think that enough for now

**Comment by willydouhard** [comment]
> Hi @willydouhard ,
> 
> This is a great new feature!
> 
> Will there be any way to save the chat histories to external files (txt, csv) stored in Github, Amazon S3, Google Drive, etc.?
> 
> Thanks!

You can already implement your [own client](https://docs.chainlit.io/data#custom-persistence) to do that

**Comment by scooter7** [comment]
Hi @willydouhard ,

If I use the  Chainlit Cloud Persistence method, how would I access the data?

Thanks!

**Comment by willydouhard** [comment]
From the UI as of now (in the history tab that appears once you configured the cloud persistence).

**Comment by scooter7** [comment]
Hi @willydouhard ,

It looks like I'll need to use the custom persistence option.

Do you know how I could save the chat histories to my Github repo?

Thanks!

**Comment by PrashantSaikia** [comment]
Hi @scooter7 ,
Did you manage to write a custom persistence option? I too would like to be able to save the chat history and feedback (upvote/downvote) history locally.

**Comment by scooter7** [comment]
Hi @PrashantSaikia , I have not yet. Thanks!
