### ISSUE TITLE
Starters support more than 4 options

### ISSUE THREAD

**Issue by thehapyone** [Chainlit/chainlit#1062]
Hi,

In the pre-release version (1.1.300) of chainlit that adds supports for starters, is it possible the remove the current limit of 4 and make it more flexible? For example it could be possible to have up to 8 or 10 if the are stacked horizontal in a grid of 4 to 5

**Comment by umair313** [comment]
its not even working for me how do you run it?

**Comment by ModEnter** [comment]
Hello, this feature is not in the roadmap, feel free however to implement it and propose a PR, all contributions are welcome

**Comment by stephenrs** [comment]
@thehappyone I added 6 starters to my project before I realized it was only supposed to support 4 (in v1.1.402), and it worked fine.

So, I assumed that the limit of 4 is not being enforced, and I don't think it should be.

So, try adding more than 4 and see if it works for you.

**Comment by stephenrs** [comment]
@ModEnter 

> Hello, this feature is not in the roadmap, feel free however to implement it and propose a PR, all contributions are welcome

Is the roadmap published somewhere? It would really be helpful to know what it is.
