### ISSUE TITLE
How should I name the avatar image

### ISSUE THREAD

**Issue by dmilcevski** [Chainlit/chainlit#1082]
I am trying version 1.1.301 and have multiple models with their full name. For example `meta-llama/Meta-Llama-3-8B-Instruct`. How should I name the avatar image in `public/avatars/` to get an image shown for the assistant? At the moment I get empty image.

**Comment by dingzt97** [comment]
I was having the same issue, did you fix it?

**Comment by Valdanitooooo** [comment]
docs: https://docs.chainlit.io/api-reference/chat-profiles#usage


I think the `Chat Profiles` feature can solve your problem, but I haven't carefully studied whether the 1.1.301  version you are using can do this

```python
@cl.set_chat_profiles
async def chat_profile():
    return [
        cl.ChatProfile(
            name="GPT-3.5",
            markdown_description="The underlying LLM model is **GPT-3.5**.",
            icon="/public/avatars/gpt-3.5.png",
        ),
        cl.ChatProfile(
            name="GPT-4",
            markdown_description="The underlying LLM model is **GPT-4**.",
            icon="/public/avatars/gpt-4.png",
        ),
    ]

@cl.on_chat_start
async def on_chat_start():
    chat_profile = cl.user_session.get("chat_profile")

```
