### ISSUE TITLE
Copilot not working for me

### ISSUE THREAD

**Issue by chibexme** [Chainlit/chainlit#1083]
I've been trying to get copilot work with different chainlit version with no success.

my chainlit server runs on http://localhost:8000/

I hosted the below page on my xampp server locally, but the chat widget is not loading

`<!DOCTYPE html>

<script src="http://localhost:8000/copilot/index.js"></script>
<script>
  window.mountChainlitWidget({
    chainlitServer: "http://localhost:8000",
  });
</script>`

**Comment by ModEnter** [comment]
Hello, this issue is fixed by [this PR](https://github.com/Chainlit/chainlit/pull/1337)
