### ISSUE TITLE
Chainlit unusable under proxy with request rewriting

### ISSUE THREAD

**Issue by akamya997** [Chainlit/chainlit#1089]
**Describe the bug**
Using version `1.1.302`, I tried to deploy it using docker on certain cloud service. But it can only return a blank page while working well on my local machine. 
The service URL is like `http://example.com/some/endpoint`, but chainlit is trying to get the assets from `http://example.com/assets/...`, thus returning a blank page and making it unusable. Unfortunately, it is not the case that can be solved by the `--root-path` config which is merged in #1064.
I found that this problem is caused by request rewriting, see the following for more details.

**To Reproduce**
I have also tried to reproduce this problem in a local environment using Nginx.

1. Use nginx to set up a proxy using a server config like
```nginx
server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name _;

    location /endpoint {
            rewrite ^/endpoint/(.*)$ /$1 break;
            proxy_pass http://localhost:9000;
    }
}
```
2. Set up chainlit service using demo.py like `chainlit run demo.py -w --port 9000`
3. Visit `http://localhost:8080/endpoint` and see a blank page

**Expected behavior**
Chainlit works well under proxy with request rewriting.

**Screenshots**
There are some screenshots from local test.
1. Successfully get the html file under proxy
<img src="https://github.com/Chainlit/chainlit/assets/44839751/55aeee83-068f-40e1-acfe-cbad32528259" width="500">
<img src="https://github.com/Chainlit/chainlit/assets/44839751/9b750267-0872-416f-bacb-43183e8b24a9" width="500">

2. Failed to get assets due to wrong prefix, the assets should be under `/endpoint/assets`
<img src="https://github.com/Chainlit/chainlit/assets/44839751/8cbaf7dd-99e0-4897-9bb2-677ed5598d3e" width="500">

**Additional context**
As a temporary solution, I hard coded the `root-path` for frontend only, which means that I modified the following lines to make it works for me: 
https://github.com/Chainlit/chainlit/blob/abf4108424b48b3a92b1b71479956b7e46ba772f/backend/chainlit/server.py#L279
https://github.com/Chainlit/chainlit/blob/abf4108424b48b3a92b1b71479956b7e46ba772f/backend/chainlit/server.py#L309-L311

**Comment by davidvesp** [comment]
I think that the problem is that you need to add the root-path argument, something like this:

chainlit run app.py --root-path /endpoint

**Comment by greg2705** [comment]
Hello, I have the same problem even when using the root_path. Any solutions without hardcode ?

**Comment by davidvesp** [comment]
we resolved using the previous command:

chainlit run app.py --root-path /endpoint

and then configuring nginx like this:

location /endpoint/ {
            proxy_http_version 1.1;
            proxy_pass http://localhost:8080/;
            rewrite ^/endpoint/(.*)$ /endpoint/$1 break;
        }

**Comment by lumiranda-fadv** [comment]
@ModEnter 

After all, how was the problem solved? I seem to have a similar one

**Comment by Eric-Miao** [comment]
> we resolved using the previous command:
> 
> chainlit run app.py --root-path /endpoint
> 
> and then configuring nginx like this:
> 
> location /endpoint/ { proxy_http_version 1.1; proxy_pass http://localhost:8080/; rewrite ^/endpoint/(.*)$ /endpoint/$1 break; }

Thx @davidvesp, this solution indeed works. 
I have tried out tons of combination of 1. all kinds of nginx proxy config with and without prefix 2. with and without --root-path (also CHAINLIT_ROOT_PATH in .env) 3. launch with a seperate uvicorn

This is still the only legit solution that works. 

Otherwise you might encouter one of the following problem that turns into a blank page
1. double prefix in request (e.g. /chainlit/chainlit/assets/xxxx)
2. no prefix in request (e.g. /assets/xxx)

This is so annoying and I'm using the latest version (2.2.1)
