### ISSUE TITLE
Author's avatar name triggering cl.Text hyperlink. 

### ISSUE THREAD

**Issue by Owe1n** [Chainlit/chainlit#110]
Hi,
I think I spotted a Bug when creating a a message such as : 
`await cl.Message(
        content="A random message containing an author name ... ",
        author="random",
    ).send()
    `
And then setting an avatar to the author "random" : 
` await cl.Avatar(
        name="random",
        url="blank",
    ).send()`
    It will then trigger the hyperlink to an empty cl.Text for the first message on the word "random". 
Is this a desirable behavior ? 
<img width="1399" alt="Capture d’écran 2023-06-27 à 15 52 18" src="https://github.com/Chainlit/chainlit/assets/59530749/547ddfbe-dd14-42ab-8584-859a397c1415">

**Comment by willydouhard** [comment]
Nice catch, will be fixed soon!

**Comment by willydouhard** [comment]
Should be fixed with the latest release.
