### ISSUE TITLE
Also support older versions of dependencies

### ISSUE THREAD

**Issue by krlng** [Chainlit/chainlit#111]
Chainlit is a great idea! But being a really young project, dependencies added simply by using `poetry add` will be pinned to the most recent version. This makes it hard to use in a project that also uses other packages. In my concrete example I run into a problem on solving the version of open-telemetry which is used by uptrace on the chainlit side and azure-monitoring on my side:

```
 Because no versions of chainlit match >0.4.101,<0.5.0
 and chainlit (0.4.101) depends on uptrace (>=1.18.0,<2.0.0), chainlit (>=0.4.101,<0.5.0) requires uptrace (>=1.18.0,<2.0.0).
(1) So, because no versions of uptrace match >1.18.0,<2.0.0
 and uptrace (1.18.0) depends on opentelemetry-sdk (1.18.0), chainlit (>=0.4.101,<0.5.0) requires opentelemetry-sdk (1.18.0).

    Because no versions of azure-monitor-opentelemetry match >1.0.0b12,<1.0.0b13 || >1.0.0b13,<2.0.0
 and azure-monitor-opentelemetry (1.0.0b13) depends on opentelemetry-sdk (1.17.0), azure-monitor-opentelemetry (>1.0.0b12,<2.0.0) requires opentelemetry-sdk (1.17.0).
    And because azure-monitor-opentelemetry (1.0.0b12) depends on opentelemetry-sdk (1.17.0), azure-monitor-opentelemetry (>=1.0.0b12,<2.0.0) requires opentelemetry-sdk (1.17.0).
    And because chainlit (>=0.4.101,<0.5.0) requires opentelemetry-sdk (1.18.0) (1), chainlit (>=0.4.101,<0.5.0) is incompatible with azure-monitor-opentelemetry (>=1.0.0b12,<2.0.0)
    So, because <package> depends on both azure-monitor-opentelemetry (^1.0.0b12) and chainlit (^0.4.101), version solving failed.
```

I am pretty sure downgrading the minimal required version of uptrace (but maybe also some other such as fastapi, click, pydantic...) would not lead to any issues but make it easier to actually use chainlit.

Can also provide PR if wished.

**Comment by constantinidan** [comment]
Hey @krlng thanks for your opening the issue! We can loosen the requirement versions if it doesn't impact chainlit. If you wish to provide a PR on this, it would be amazing!

**Comment by krlng** [comment]
Bad timing, I am currently in parental leave, so this won't happen from my side soon.

**Comment by willydouhard** [comment]
> Bad timing, I am currently in parental leave, so this won't happen from my side soon.

Congrats and all the best for your family!
