### ISSUE TITLE
Remove all actions of a message, after user clicked anyone of them?

### ISSUE THREAD

**Issue by gxagxagxa** [Chainlit/chainlit#115]
Actions and Action Callbacks are easy and great.

I found how to remove the clicked action in the docs.
However,  in some cases, I need to remove all actions of a message after user clicked anyone of them.  
For example, A send email message with options: OK and Cancel.  No matter which action they clicked, just can't click it again.

I figure a tricky way to do this:

```python
import contextvars

actions_vars = contextvars.ContextVar('action_for_id', default={})


@cl.action_callback(name='answer.satisfy')
async def action_callback(action: cl.Action):
    message_actions = actions_vars.get().pop(action.forId)
    await cl.Message(content=f"{action}").send()
    for a in message_actions:
        await a.remove()


@cl.on_message
async def reply(user_input: str):
    actions = [
        cl.Action(name='answer.satisfy', label='OK', value=f'true'),
        cl.Action(name='answer.satisfy', label='Cancel', value=f'false'),
    ]
    message = cl.Message(content='here is the message', actions=actions)
    await message.send()
	
    existing = actions_vars.get()
    existing.update({message.temp_id: actions})
    actions_vars.set(existing)

```

**Comment by willydouhard** [comment]
Currently context vars or the user session are the right way to do this. Here is an example with the user session https://github.com/Chainlit/cookbook/tree/main/confirm-action

We might add methods on the Message class such as `remove_elements` or `remove_actions` in the future!

**Comment by gxagxagxa** [comment]
> Currently context vars or the user session are the right way to do this. Here is an example with the user session https://github.com/Chainlit/cookbook/tree/main/confirm-action
> 
> We might add methods on the Message class such as `remove_elements` or `remove_actions` in the future!

Thanks for replying 😊, `remove_elements` or `remove_actions` will be great!

**Comment by willydouhard** [comment]
Will do in the next release!

**Comment by dokato** [comment]
Has `remove_actions` function been added @willydouhard ? couldn't find in docs
