### ISSUE TITLE
Google OAuth Not Working - The OAuth client was not found.

### ISSUE THREAD

**Issue by cosmicai-info** [Chainlit/chainlit#1152]
**Describe the bug**
I am trying to use OAuth with Google. Its always complaining with error

"Access blocked: Authorization Error

The OAuth client was not found.
If you are a developer of this app, see [error details](https://accounts.google.com/).
Error 401: invalid_client"

**To Reproduce**
Just save below code into app.py and run chainlit run app.py -w 

**Expected behavior**
It should have prompted to select google account and login. after that it should have redirected to my regular chat app.

**Screenshots**

![ChainLitOauthError](https://github.com/user-attachments/assets/3899c6a2-4f25-4306-bf54-c9e6aa95b288)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser : Chrome and Firefox
- Version : chainlit                                 1.1.306
- 
**Smartphone (please complete the following information):**

**Additional context**

a) Code

****  I have setup environment variables
OAUTH_GOOGLE_CLIENT_ID
OAUTH_GOOGLE_CLIENT_SECRET

and here is code:

from typing import Dict, Optional
import chainlit as cl

import os

os.environ["OAUTH_GOOGLE_CLIENT_ID"] = "xxxx.apps.googleusercontent.com"
os.environ["OAUTH_GOOGLE_CLIENT_SECRET"]= "SecretPass"
os.environ["CHAINLIT_AUTH_SECRET"]="xxxxxxxxdkmYlv3IzT25nm8P"

print(f"H:{os.environ.get('OAUTH_GOOGLE_CLIENT_ID')}")
@cl.oauth_callback
def oauth_callback(
  provider_id: str,
  token: str,
  raw_user_data: Dict[str, str],
  default_user: cl.User,
) -> Optional[cl.User]:
    print("In callback ")
    return default_user

@cl.on_message
async def main(message: cl.Message):
    # Your custom logic goes here...

    # Send a response back to the user
    await cl.Message(
        content=f"Received: {message.content}",
    ).send()

b) Debug logs
2024-07-22 16:10:40 - File modified: app.py. Reloading app...

←[32mINFO←[0m:     127.0.0.1:62892 - "←[1mGET / HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:62896 - "←[1mGET /auth/config HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:62897 - "←[1mGET /project/translations?language=en-US HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:62897 - "←[1mGET /login HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:62897 - "←[1mGET /logo?theme=dark HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:62896 - "←[1mGET /auth/oauth/google HTTP/1.1←[0m" ←[33m307 Temporary Redirect←[0m

**Comment by illegalplumbing** [comment]
The auth callback url generated is /callback rather than /auth/oauth/google/callback

**Comment by cosmicai-info** [comment]
I figured it out. issue was mainly the way env variables were being set
