### ISSUE TITLE
Why, after running 'chainlit', when I open the website it shows 'Unauthorized: credentialssignin' and I cannot log in, what is the reason for this?

### ISSUE THREAD

**Issue by meiyiyeshi** [Chainlit/chainlit#1176]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dokterbob** [comment]
@meiyiyeshi Thanks for contributing!

Please answer the specific questions in the bug report and reopen. Any relevant code (e.g. pertaining to auth) you can share would be a 👍🏼 .
