### ISSUE TITLE
Tasklist example not working on 1.1.400

### ISSUE THREAD

**Issue by Reymond190** [Chainlit/chainlit#1180]
Tasklist example errors when tried to run.
"Object of type Message is not JSON serializable"

1. copy paste the example from https://docs.chainlit.io/api-reference/elements/tasklist
2. chainlit run app.py

**Expected behavior**
when the example run, caused an error "Object of type Message is not JSON serializable".

**Screenshots**
![Screenshot from 2024-07-31 22-04-22](https://github.com/user-attachments/assets/67b9c306-de2c-403f-afd5-48ddc6863244)

**Desktop (please complete the following information):**

- OS: [e.g. iOS]: windows
- Browser [e.g. chrome, safari]: chrome

**Additional context**

**Comment by barun-saha** [comment]
So, I changed the reference code slightly. Appears to work now without said error:

```python
# Optional: link a message to each task to allow task navigation in the chat history
# message_id = await cl.Message(content="Started processing data").send()
# task1.forId = message_id
#
# .send() returns the Message; use message ID instead
message = cl.Message(content="Started processing data")
await message.send()
task1.forId = message.id
```

**Comment by dokterbob** [comment]
It seems there's a PR for it already. We'll get it merged ASAP.
