### ISSUE TITLE
Chainlit can't be recognized 

### ISSUE THREAD

**Issue by Zampiva** [Chainlit/chainlit#1198]
I installed chainlit using pip install chainlit on terminal, when I hit pip install chainlit again it says that every requirement is already satisfied. But when I hit chainlit hello or chainlit run it says that chainlit is not recognized as an installed file, I have already set python 3.9 as default version on windows environment path and restart my PC, but that error keeps appearing. 

Edit: I was able to run chainlit on anaconda prompt as admin, but that error keeps appearing on VS code and pycharm.

![Desktop Screenshot 2024 08 09 - 10 35 03 38](https://github.com/user-attachments/assets/cb643b44-b473-40da-b9b3-9897000599db)

```
chainlit hello
chainlit : The term 'chainlit' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At line:1 char:1
+ chainlit hello
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (chainlit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

- OS: Windows 10 Pro
- Browser Firefox
- Version 129

**Comment by 64asoda** [comment]
Hello, How did you fix the error?

**Comment by Zampiva** [comment]
> Hello, How did you fix the error?

Whenever text editor are you using, open the terminal and copy the path of your project
-open anaconda prompt as admin and hit cd + path
-if you can't open the path at first tempt, delete the last archive of the path and hit cd again
-hit dir; cd + last archive name
now you can run chainlit
