### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by InfernalAzazel** [Chainlit/chainlit#12]
This is a very excellent project that has solved some problems in the field and made writing artistic intelligence applications more conservative I hope my suggestions will make it better

[ ] 1. I hope the following tags and URLs can be customized
![1685248400(1)](https://github.com/Chainlit/chainlit/assets/40333954/ca73f834-616f-4d47-a717-79034b78eb0d)
[ ]   2. I hope to have a login page and the ability to authenticate and log in to my own server
[ ]  3. Hope chat can have multiple sessions
[ ]  4. Internationalized language support
[x] 5. Adapt to mobile UI
![image](https://github.com/Chainlit/chainlit/assets/40333954/e3b41025-1e34-4ca4-954a-ec8f3a7cdd7e)

**Comment by willydouhard** [comment]
Thank you for your feedback!

Features around login, sessions, and deployment to custom urls are on the way even I cannot commit to a specific deadline at the moment.

Internationalized is the not priority at the moment but would love to see some contributions around that :).

For the UI on mobile I will fix the header in the next release.

**Comment by willydouhard** [comment]
Fixed the header nav on mobile in the 0.2.107 release!

**Comment by InfernalAzazel** [comment]
> 在 0.2.107 版本中修复了移动设备上的标题导航！

awesome !

**Comment by InfernalAzazel** [comment]
> Fixed the header nav on mobile in the 0.2.107 release!

![2023-05-29_09-38](https://github.com/Chainlit/chainlit/assets/40333954/d7e457b0-7417-41fb-83c4-d134c868fec5)

awesome

**Comment by InfernalAzazel** [comment]
After using chainlit for a while, my feeling is very great. gradio and streamlit can still go into the trash can, which is particularly convenient for debugging ai.

If the flexibility of chainlit in the future can allow users to customize more, it will inevitably be beneficial.

Gradio and streamlit are more inclined to debug AI design, and developing commercial software is a disadvantage.

In the current development of chainlit, it seems that it is very suitable for developers to debug AI and develop commercial software.
