### ISSUE TITLE
`edit_message` in wrong place in `config.toml`

### ISSUE THREAD

**Issue by EWouters** [Chainlit/chainlit#1204]
**Describe the bug**
If you run chainlit with an empty `config.toml` the `edit_message` key is placed below `[features.audio]`, however it only works when it is inside the `[features]` block.

**To Reproduce**

1. Run chainlit without a `config.toml` to generate the file
2. The generated `config.toml` has the line `edit_message = true`, change it to `edit_message = false`
3. Run chainlit again
4. Messages are still editable

**Expected behavior**
Messages should not be editable when `edit_message = false`.

**Additional context**
Moving `edit_message = false` up to the `[features]` block disables editing messages as expected.

**Comment by dokterbob** [comment]
Seems that the default `config.toml` needs to be adjusted to resolve this. 

@EWouters Any chance you'd be able to:
a. Find where the default config is.
b. Fire a PR updating it, linking to the current issue?
