### ISSUE TITLE
How to open sidebar by default

### ISSUE THREAD

**Issue by Valdanitooooo** [Chainlit/chainlit#1222]
I couldn't find any options in the document that can be configured in this way.

**Comment by dokterbob** [comment]
AFAIK it currently can't, but we're open to (suggestions for) a PR, which should also address #1200.

Perhaps you feel like creating a new issue combining both, suggesting a configuration options and UX?

**Comment by Valdanitooooo** [comment]
> #1200.

That's exactly what I want to express, thanks!
