### ISSUE TITLE
Incorrect message ordering in UI after 1.1.400

### ISSUE THREAD

**Issue by francisjervis** [Chainlit/chainlit#1230]
**Describe the bug**
Assistant messages (including AskUserMessages) are stacked at the top of the chat window, with user messages at the bottom, instead of being in the order they were posted.

**To Reproduce**

Update to chainlit 1.1.400 or later. Emit >1 turns of AskUserMessage/user input events to UI.

**Expected behavior**
Messages are displayed in the order they were posted, with user input below the corresponding AskUserMessage.

**Screenshots**
<img width="977" alt="Screenshot 2024-08-16 at 9 58 56 PM" src="https://github.com/user-attachments/assets/f60bd818-7c37-4271-8b66-61c8de3ba18d">

**Desktop (please complete the following information):**

Mac, Chrome 127

**Comment by marty-sullivan** [comment]
+1 also seeing this problem

**Comment by puppetm4st3r** [comment]
x2, also here!

**Comment by Harbon** [comment]
I have the same issue

**Comment by puppetm4st3r** [comment]
back to 1.3

**Comment by fdojose** [comment]
I thought it was intentional ;) But it seams is an error.

**Comment by francisjervis** [comment]
Confirming that this is still not fixed in 1.2.0.

**Comment by puppetm4st3r** [comment]
any new with this?

**Comment by scdozier** [comment]
agree this is broken .. If you refresh page, it reorders correctly.  Downgrading to 1.1.306 works.

**Comment by tugbayatilla** [comment]
same issue. 

## Version: 1.1.306
<img width="967" alt="Screenshot 2024-10-11 at 09 32 30" src="https://github.com/user-attachments/assets/a848b054-890b-4987-a607-56144e86b880">

## Version: 1.2
<img width="874" alt="Screenshot 2024-10-11 at 09 33 39" src="https://github.com/user-attachments/assets/81e71b1e-0c56-4371-b92b-e0d8e5dda9f8">

**Comment by yyoussef11** [comment]
@dokterbob  the issue is clear in this commit "e3a42ba377cf70bc851c3bea2aa65f161602a634" for version [1.1.400rc1](https://github.com/Chainlit/chainlit/releases/tag/1.1.400rc1)

there was a change at the level of the "Make sure the child assistant messages of a step are displayed at the root level." 
line 196

**Comment by gcleaves** [comment]
The problem remains in v1.3.0 [2024-10-22]. Long live v1.1.306!!!!

**Comment by previacita** [comment]
+1 here. It would seem to me that showing messages in the correct order is a must have for a chat application.

**Comment by anthonym1991** [comment]
Samen problem.

**Comment by pmercier** [comment]
+1 Facing the same problem here with v1.3.1 too.

**Comment by pmercier** [comment]
Tested different code version to confirm that it's front related:

* Using 1.1.306 for front and back : No problem
* Using 1.1.400 for front and back : Incorrect sequencing
* Using 1.1.306 frontend code with 1.3.1 backend : No problem
* Using 1.1.400 frontend code with 1.3.1 backend : Incorrect sequencing

Looking in changelog / code / debugging :

* Between 1.1.306 and 1.1.400, the step notion was added.
* Before 1.1.400, all messages was stored sequentially in frontend memory.
* After 1.1.400, they are stored as step in their parent.

When activating data persistency, if we reload the chat with a good old F5, whatever code version, the messages are displayed in proper order.

**Comment by pmercier** [comment]
Have it working correctly now. It'll make a PR .

**Comment by pmercier** [comment]
For those who need it, the patch can be back ported to 1.1.400 if you package your own frontend.

**Comment by gcleaves** [comment]
@dokterbob @willydouhard Please review the pull request ;)

**Comment by imadNaseer** [comment]
guys make sure that you are not entering a static id.
res = cl.Message(content="", id="message_id")
