### ISSUE TITLE
When I use pdf-qa demo. It shows PayloadTooLargeError

### ISSUE THREAD

**Issue by jiansongjay** [Chainlit/chainlit#126]
When I upload a pdf file using PDF-QA demo, the “PayloadTooLargeError” is displayed
It appears to be an error related to Node

**Comment by willydouhard** [comment]
What is the size of the PDF file you are trying to upload?

**Comment by jiansongjay** [comment]
Just 1.6 MB

**Comment by jiansongjay** [comment]
> What is the size of the PDF file you are trying to upload?


Just 1.6 MB

**Comment by willydouhard** [comment]
Where exactly is this error showing? In the UI or in your terminal? It looks like a Node error but we do not use Node so that is intriguing (except for the local db with prisma).
