### ISSUE TITLE
Prepare for release 1.1.403

### ISSUE THREAD

**Issue by dokterbob** [Chainlit/chainlit#1266]
ETA: ~4/9

* [ ] Update changelog
* [ ] Update docs based on changelog
* [ ] Manual testing by @willydouhard

**Comment by EWouters** [comment]
> Hey! Do you think you guys will have time to add relaxed requirements for dataclasses_json in this release?
> 
> Using LangChain with unstructured currently gives the following error:
> 
> The conflict is caused by: chainlit 1.1.304 depends on dataclasses_json<0.6.0 and >=0.5.7 unstructured-client 0.24.1 depends on dataclasses-json>=0.6.4

Addressed in #1267

**Comment by dokterbob** [comment]
> > Hey! Do you think you guys will have time to add relaxed requirements for dataclasses_json in this release?
> > Using LangChain with unstructured currently gives the following error:
> > The conflict is caused by: chainlit 1.1.304 depends on dataclasses_json<0.6.0 and >=0.5.7 unstructured-client 0.24.1 depends on dataclasses-json>=0.6.4
> 
> Addressed in #1267

We'd be open to have some _explicit_ removal of dep versions, particularly if this comes with unit tests for the interaction surface with those specific deps (so we can be sure that chainlit doesn't break if we remove `<` versions, now or in the future).

**Comment by dokterbob** [comment]
We're probably gonna bump the minor version due to added features.

Release PR/changelog is here: https://github.com/Chainlit/chainlit/pull/1289

Release ETA: later today.
