### ISSUE TITLE
The HTTP request is not available through methods decorated

### ISSUE THREAD

**Issue by ahmadmayahi** [Chainlit/chainlit#1283]
**Describe the bug**
The HTTP request is not available through methods decorated .

**Expected behavior**
The request object should be available everywhere, as this helps us build multi-agent chatbots. The current implementation makes that impossible.

**Comment by dokterbob** [comment]
Thanks for the feedback @ahmadmayahi. Though I should like to ask that before you create bug reports you take a minute or two to see whether a similar issue already exists. 

In this case, it's a dup of #1213. Happy to hear your thoughts on my proposal there -- or possibly even your PR towards that end!
