### ISSUE TITLE
There is no way to load a different config.toml file

### ISSUE THREAD

**Issue by ahmadmayahi** [Chainlit/chainlit#1284]
**Describe the bug**
There is no way to load a different `config.toml` file.

In a multi-tenant application, each application has a dedicated configuration file.

I suggest that Chainlit allow developers to load the configuration file dynamically if they choose to. For example, it should be possible to download the file via an HTTP request. Additionally, HTTP request should also be available, as multi-tenant support wouldn't work properly otherwise.

**Comment by dokterbob** [comment]
There is, as soon as we deploy the upcoming release! https://github.com/Chainlit/chainlit/blob/main/CHANGELOG.md#changed https://github.com/Chainlit/chainlit/pull/1259

**Comment by dokterbob** [comment]
Long term, I'm explicitly open to discuss an abstraction layer for config loading (like `load_config() -> Config` or similar) with file-based loading as the default implementation. Developers can then get their config from wherever they like, data store or URL or some ugly little pickle somewhere. ;)

If you're interested to explore ideas on that, feel free to reopen and/or rephrase the issue to facilitate sharing of thoughts with other devs as well. Appreciate the input! @ahmadmayahi

**Comment by ahmadmayahi** [comment]
Thanks @dokterbob 

Actually, I have a list of how to make `chainlit` fully multi-tenant.

### Problem

Currently, Chainlit doesn't support multi-tenancy, meaning a new instance cannot host multiple tenants. For example, there is only one configuration file, `config.toml`. In a multi-tenant setup, however, each tenant should have a dedicated configuration file.

### Configurations (TOML file)

The `config.toml` file should be loaded dynamically, leaving it to the developer to decide how to achieve this. Instead of having a hardcoded `config.toml` in [[backend/chainlit/config.py](https://github.com/Chainlit/chainlit/blob/86798bca7332710b2aefb95be40ba4d8848917be/backend/chainlit/config.py#L39)](https://github.com/Chainlit/chainlit/blob/86798bca7332710b2aefb95be40ba4d8848917be/backend/chainlit/config.py#L39

The loading should be handled by a Python function in [`[main.py](http://main.py/)`](http://main.py), the app containing the Chainlit instance:

```python
# This function will return the contents of the config.toml file
def load_configuration(request: Request):
    pass
```

The HTTP request object also needs to be available in the configuration file, allowing the developer to load the config from HTTP, for example. This can be accomplished using FastAPI dependency injection.

Chainlit should function the same way, except it will load the configuration file through the `load_configuration` function.

### Env files

The `.env` file must also support multi-tenancy, similar to the configuration file:

```python
def load_env_file(request: Request):
    pass
```

### HTTP Request in All Functions

The HTTP request object needs to be available in all the [[Chainlit lifecycle hooks](https://docs.chainlit.io/api-reference/lifecycle-hooks/on-chat-start)](https://docs.chainlit.io/api-reference/lifecycle-hooks/on-chat-start).

```python
@on_chat_start
async def main(request: Request):
    pass
```

### Extra settings into the config.toml file

Add the following extra setting into the config.toml file:

```python
[auth]
requires_login = true
```

Now, for Chainlit to use password authentication, it needs to check whether the `requires_login` flag is enabled and then call the function `auth_callback`.

The [[auth callback](https://docs.chainlit.io/authentication/password#password)](https://docs.chainlit.io/authentication/password#password) also needs to have the request object:

```python
@cl.password_auth_callback
def auth_callback(request: Request):
	password
```

### Assets

Currently, Chainlit supports asset files through the public folder. These assets are:

- [[Logo and favicons](https://docs.chainlit.io/customisation/custom-logo-and-favicon#logo-and-favicon)](https://docs.chainlit.io/customisation/custom-logo-and-favicon#logo-and-favicon).
- [[Custom JS file](https://docs.chainlit.io/customisation/custom-js#js)](https://docs.chainlit.io/customisation/custom-js#js).
- [[Custom CSS file](https://docs.chainlit.io/customisation/custom-css#css)](https://docs.chainlit.io/customisation/custom-css#css).

Instead of the `public` folder, the assets need to be loaded through a function named `load_assets`, and all of them should access absolute URLs such as [`https://myapp.cloudflare/assets/logo.png`](https://myapp.cloudflare/assets/logo.png):

```python
from dataclasses import dataclass

@dataclass
class Assets:
    favicon: str
    logo: int
    js: str
    css: str

def load_assets(request: Request) -> Assets:
	pass
```

Notice, the `request` should also be available.

### Uvicorn

I'm not entirely sure about the specific workings of the Chainlit web server; however, it is possible to delegate its functionality to FastAPI through the process of mounting. Ideally, I would prefer it to consistently utilize FastAPI delegation without the necessity of mounting it.

### Redis

To enable Redis support, it must be installed and configured. The `.env` file should be used for the connection URL, password, and any other configuration settings.
