### ISSUE TITLE
1.1.404 - Plotly Broken

### ISSUE THREAD

**Issue by hayescode** [Chainlit/chainlit#1309]
**Describe the bug**

The new `1.1.404` release breaks Plotly visualizations.
![image](https://github.com/user-attachments/assets/086084cd-3a4c-412f-899f-ac09683cc747)

The application is looking for `/assets/react-plotly-012ed517.js` but the code is `/assets/react-plotly-5bb34118.js`
![image](https://github.com/user-attachments/assets/cfa56152-3f2c-47cb-8c30-d142427ce7c0)

**Expected behavior**
Plotly displays to the user

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Edge

**Comment by dokterbob** [comment]
Thanks for the quick feedback @hayescode! We'll look into it ASAP.

**Comment by hayescode** [comment]
@dokterbob closing this i think this was a cache issue. Clearing cache and restarting my web app fixed this.
