### ISSUE TITLE
Chainlit socket io path is set wrongly when ROOT_PATH is used

### ISSUE THREAD

**Issue by qtangs** [Chainlit/chainlit#1313]
**Describe the bug**
Chainlit socket io path seems wrong.

**To Reproduce**

1. Run chainlit with environment variable: CHAINLIT_ROOT_PATH=chainlit
2. Open app using the custom path: http://localhost:8000/chainlit
3. App is not able to establish websocket connection

**Expected behavior**
App should work normally.

**Suggested solution**
I have tested changing these lines
- https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/server.py#L178
  fr: `sio_mount_location = f"{ROOT_PATH}/ws" if ROOT_PATH else "ws"`
  to: `sio_mount_location = f"{ROOT_PATH}/ws" if ROOT_PATH else "/ws"`

- https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/server.py#L185
  fr: `app.mount(f"/{sio_mount_location}", asgi_app)`
  to: `app.mount(sio_mount_location, asgi_app)`

**Screenshots**
Nil

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 128.0.6613.120

**Smartphone (please complete the following information):**
N/A

**Additional context**
Nil

**Comment by nethi** [comment]
I had to do similar workaround. Also I was surprised to see this breaking change in a previous release but no mention of it.

**Comment by Tug** [comment]
> I have tested changing these lines
> 
> https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/server.py#L178
> fr: sio_mount_location = f"{ROOT_PATH}/ws" if ROOT_PATH else "ws"
> to: sio_mount_location = f"{ROOT_PATH}/ws" if ROOT_PATH else "/ws"
> 
> https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/server.py#L185
> fr: app.mount(f"/{sio_mount_location}", asgi_app)
> to: app.mount(sio_mount_location, asgi_app)

Indeed that fixes the problem. https://github.com/Chainlit/chainlit/pull/1203 seems to be the culprit. @qtangs will you open a PR ? I can do it also.

**Comment by dokterbob** [comment]
Thanks for the report @qtangs!

Are you perhaps able to help to verify whether #1337 resolves your issue?

**Comment by dokterbob** [comment]
Tested to work with `CHAINLIT_ROOT_PATH=chainlit` for #1337. 

To be released today.

**Comment by qtangs** [comment]
> Tested to work with `CHAINLIT_ROOT_PATH=chainlit` for #1337.

Thanks @dokterbob . Sorry I wasn't able to help. So glad the team reacted quickly on this.
