### ISSUE TITLE
The markdown format is not supported

### ISSUE THREAD

**Issue by jiansongjay** [Chainlit/chainlit#132]
It doesn’t support markdown format？
![image](https://github.com/Chainlit/chainlit/assets/2103028/1a0baf16-7870-4fb2-a67e-a192178446e0)

**Comment by willydouhard** [comment]
I am not sure I understand what you mean. Are you expecting a specific display for scientific notation?

**Comment by willydouhard** [comment]
Here is an example to display a table:

```py
import chainlit as cl


@cl.on_chat_start
async def main():
    msg = """| heading | b  |  c |  d  |
  | - | :- | -: | :-: |
  | cell 1 | cell 2 | 3 | 4 |
"""
    await cl.Message(content=msg).send()
```

<img width="457" alt="Screenshot 2023-07-04 at 14 16 45" src="https://github.com/Chainlit/chainlit/assets/13104895/a16db80e-3178-4c9d-a134-97f9c95b95e9">

Source [here](https://codepen.io/akash-mittal/pen/ZEKGZZO)

**Comment by jiansongjay** [comment]
> Here is an example to display a table:
> 
> ```python
> import chainlit as cl
> 
> 
> @cl.on_chat_start
> async def main():
>     msg = """| heading | b  |  c |  d  |
>   | - | :- | -: | :-: |
>   | cell 1 | cell 2 | 3 | 4 |
> """
>     await cl.Message(content=msg).send()
> ```
> 
> <img alt="Screenshot 2023-07-04 at 14 16 45" width="457" src="https://user-images.githubusercontent.com/13104895/250898627-a16db80e-3178-4c9d-a134-97f9c95b95e9.png">
> Source [here](https://codepen.io/akash-mittal/pen/ZEKGZZO)

So it's not displayed because of the style problem of table lines?

**Comment by willydouhard** [comment]
I am not sure I understand, can you show the markdown you are sending to in the message content?
