### ISSUE TITLE
CrewAI agent integrations

### ISSUE THREAD

**Issue by ModEnter** [Chainlit/chainlit#1338]
Is there any plan to integrate with CrewAI? Would be good to have this! :D

_this question was asked by [RYangData](https://github.com/RYangData) on Chainlit/docs, this is a repost to the correct repository.
https://github.com/Chainlit/docs/issues/142

**Comment by dokterbob** [comment]
@ModEnter What's CrewAI and why would we want this? What would it take to get there?

**Comment by ModEnter** [comment]
Ask @RYangData, I just moved a docs issue to chainlit 😉  I guess we can just delete this issue, as it has no been answered/reacted to by its author
