### ISSUE TITLE
Missing blinking dot

### ISSUE THREAD

**Issue by vaclcer** [Chainlit/chainlit#1354]
Hi, the blinking dot / progress bar / spinnig wheel, simply an element to tell the user something is happening in the background was there, but somehow got lost after 1.1.306 release. Can we get it back? Ir is there any other best practice to achieve it? Thanks!

Tested this code in version 1.1.304 and a blinking dot was displayed, but in the latest version 1.1.401, no progress indicator is shown. Looks like this ability was removed sometime in between these two versions.

```
import chainlit as cl


@cl.on_message
async def on_message(message: cl.Message):
    msg = cl.Message(content="")
    await msg.send()

    # do some work
    await cl.sleep(4)

    msg.content = f"Processed message {message.content}"

    await msg.update()
```

_Originally posted by @nileshtrivedi in https://github.com/Chainlit/chainlit/issues/588#issuecomment-2273060474_

**Comment by MA3CIN** [comment]
Same issue is described in https://github.com/Chainlit/chainlit/issues/1254

**Comment by dokterbob** [comment]
Closing as it's a dup.
