### ISSUE TITLE
Mixed dependencies in the Storage Clients module for the Data Layer

### ISSUE THREAD

**Issue by hadarsharon** [Chainlit/chainlit#1355]
**Describe the bug**
When importing a certain storage client for usage in the data layer (e.g. `S3StorageClient`), one might encounter import errors due to mixed dependencies in the module, such as: **Azure** packages missing.

**To Reproduce**

1. Install Chainlit with relevant packages for using the `S3StorageClient` for the data layer (i.e. `boto3`)
2. Make sure you have no Azure packages installed in your Python runtime env. 
3. Try importing the client with `from chainlit.data.storage_clients import S3StorageClient`
4. You should encounter import errors because the `storage_clients` module has top-level imports for Azure:
```python
import boto3  # type: ignore
from azure.storage.filedatalake import (
    ContentSettings,
    DataLakeFileClient,
    DataLakeServiceClient,
    FileSystemClient,
)
```
**(Note the top-level import of both boto3 and azure.storage.filedatalake within the module, even though we only choose one client out of the two)**
6. Same issue would apply if you had Azure dependencies installed, but not S3 (`boto3`) 

**Expected behavior**
The storage client should be importable and ready for instantiation based on the type you require, without having to install all other storage clients' dependencies. 

**Desktop (please complete the following information):**

- OS: iOS
- Version: 1.2.0

---

I can imagine that splitting the `storage_clients` module to separate sub-modules based on the specific client type (e.g. `S3`, `Azure`, `GCS` etc.) would resolve this issue, as each would import **only** what that specific client needs.

**Comment by ndricca** [comment]
A simple workaround is to just create a new script for only S3StorageClient and import it from there into your main app.py file.
I could do a PR to handle this maybe in the next days.

**Comment by hadarsharon** [comment]
> > I can imagine that splitting the storage_clients module to separate sub-modules based on the specific client type (e.g. S3, Azure, GCS etc.) would resolve this issue, as each would import only what that specific client needs.
> 
> I have done this locally (creating a new script for only S3StorageClient and import it from there into your main app.py file) and it works like a charm. I could do a PR to handle this maybe in the next days.

Yes, I have done so too and it works fine, but I imagine some people would not appreciate having to do that, or not realize that this is a solution. 

Bunching all the imports together in the same module for all the storage clients just seems like a simple oversight to me. I'm not sure why the data layers were properly distributed to modules (e.g. dynamodb in its own module) but the storage clients weren't.

**Comment by dokterbob** [comment]
> **Describe the bug** When importing a certain storage client for usage in the data layer (e.g. `S3StorageClient`), one might encounter import errors due to mixed dependencies in the module, such as: **Azure** packages missing.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install Chainlit with relevant packages for using the `S3StorageClient` for the data layer (i.e. `boto3`)
> 2. Make sure you have no Azure packages installed in your Python runtime env.
> 3. Try importing the client with `from chainlit.data.storage_clients import S3StorageClient`
> 4. You should encounter import errors because the `storage_clients` module has top-level imports for Azure:
> 
> ```python
> import boto3  # type: ignore
> from azure.storage.filedatalake import (
>     ContentSettings,
>     DataLakeFileClient,
>     DataLakeServiceClient,
>     FileSystemClient,
> )
> ```
> 
> **(Note the top-level import of both boto3 and azure.storage.filedatalake within the module, even though we only choose one client out of the two)** 6. Same issue would apply if you had Azure dependencies installed, but not S3 (`boto3`)
> 
> **Expected behavior** The storage client should be importable and ready for instantiation based on the type you require, without having to install all other storage clients' dependencies.
> 
> **Desktop (please complete the following information):**
> 
> * OS: iOS
> * Version: 1.2.0
> 
> I can imagine that splitting the `storage_clients` module to separate sub-modules based on the specific client type (e.g. `S3`, `Azure`, `GCS` etc.) would resolve this issue, as each would import **only** what that specific client needs.

Let us know if you are doing a PR for this (to avoid double work). I imagine a `storage_clients` module in the `data` module with a `base.py` and files for each implementation (and, preferably, no code in `__init__.py`.

I love how active this community is! ❤️

**Comment by HadarSha** [comment]
I will look into doing one tomorrow, unless someone beats me to it :)

**Comment by hadarsharon** [comment]
I will look into doing one tomorrow, unless someone beats me to it :)

**Comment by ndricca** [comment]
Hi guys, I am trying doing the PR and I am working on Windows. 
I have set up everything but once running `pnpm run buildUi` I am encountering errors (tsup: command not found).

**Comment by dokterbob** [comment]
> Hi guys, I am trying doing the PR and I am working on Windows. I have set up everything but once running `pnpm run buildUi` I am encountering errors (tsup: command not found).
> 
> Should I open a new issue on this? Is Windows supported?

Did you do `pnpm install` before running the build?

**Comment by dokterbob** [comment]
@hadarsharon @ndricca No need to work both on the same PR, plenty of other bugs and cleanup left! :')

**Comment by ndricca** [comment]
I have done PR #1363 , can you check it?

**Comment by dokterbob** [comment]
Closing this in favour of the PR (just for our overview).
