### ISSUE TITLE
issue deploying chainlit in gcp cloud run

### ISSUE THREAD

**Issue by nani1149** [Chainlit/chainlit#1358]
I am trying to deploy chainlit app in gcp cloud run and running into below issue.Below is the error

<img width="891" alt="image" src="https://github.com/user-attachments/assets/9d9898ed-148d-4e47-bee4-2ef6782e487e">

Here is the docker file that i am using for the deployment

[source/app.py"]`](https://github.com/nani1149/llm-transalation-langchain-chainlit/blob/main/Dockerfile)

Please let me know if i am missing anything.. More documentation in docs will be helpful

Thank you

**Comment by nani1149** [comment]
@smannathan Thanks..it worked.. running into another issue.. i have https://mydomain.com env var for chainiturl and CHAINLIT_URL/auth/oauth/google/callback as redirect url.. my cloud run url ishttps://chainlit-transalation-878726209708.us-central1.run.app.

Issue : authentication is working but it is redirecting to https://mydomain.com public site not to my chainlit application.. am i using wrong env if yes..what is the correct env for chainlit url

**Comment by dokterbob** [comment]
@nani1149 I recommend you ask the community for support on Discord. I'm sure others faced similar problems and are happy to help you there. We prefer to keep issues mostly for bugs, thanks! :D
