### ISSUE TITLE
Security: allowed origins should not be * by default

### ISSUE THREAD

**Issue by dokterbob** [Chainlit/chainlit#1359]
CORS headers should be restricted to the current domain at least, by default.

**Comment by dokterbob** [comment]
@dosu Where do we have to look in the settings/code to set this to a sensible/safe default value?

**Comment by dokterbob** [comment]
@dosu Maybe we could make the default in the settings file 127.0.0.1 and localhost, then document users to change it for production to whatever website/domain they use?

**Comment by Harish-NTCPWC** [comment]
@dosu index.html:1 Access to fetch at 'https://demo.com/chatbot/auth/config' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost, *', but only one is allowed. Have the server send the header with a valid value.

web app is working fine without any cors issue, but copilot brings this cors error
