### ISSUE TITLE
read params in url within element

### ISSUE THREAD

**Issue by sundi133** [Chainlit/chainlit#136]
how to read url get params ? like localhost:8000/user_id=1

**Comment by swdes** [comment]
Hello. I don't know about @sundi133 usecase but I would love to access the get variable during the on_chat_start so I can initiate my assistant with same specific embeddings.

**Comment by willydouhard** [comment]
Noted, will look into it

**Comment by lehic** [comment]
Hi there, 
I have a similar requirement. 

I need to start conversations between a user and the AI assistant by providing a specific parameter. This parameter is unique and vital for ensuring the assistant responds accurately to the user's questions by identifying the correct context.

Do you have plans to include this feature in your roadmap soon? If not, could you suggest any workaround solutions to support this use case?

Thanks

**Comment by martinaruoccolrqa** [comment]
Hello, do you have any news about this?
