### ISSUE TITLE
v1.2 is not working in docker

### ISSUE THREAD

**Issue by tugbayatilla** [Chainlit/chainlit#1360]
**Describe the bug**
When i upgrade the version from `1.1.306`to `1.2.0`, docker container is not working as expected anymore.

**To Reproduce**
### Working examples
Example 1
```
FROM python:3.11.10-slim

RUN pip install chainlit==1.1.306

WORKDIR /app
COPY app.py .

CMD ["chainlit", "run", "app.py"]
```

```
FROM python:3.12.6-slim

RUN pip install chainlit==1.1.306

WORKDIR /app
COPY app.py .

CMD ["chainlit", "run", "app.py"]
```

<img width="1716" alt="image" src="https://github.com/user-attachments/assets/6817d22f-9fbb-4630-aef9-fc759d4c8ba2">

### Problematic Examples

```
FROM python:3.11.10-slim

RUN pip install chainlit==1.2.0

WORKDIR /app
COPY app.py .

CMD ["chainlit", "run", "app.py"]
```

```
FROM python:3.12.6-slim

RUN pip install chainlit==1.2.0

WORKDIR /app
COPY app.py .

CMD ["chainlit", "run", "app.py"]
```
<img width="887" alt="image" src="https://github.com/user-attachments/assets/d69ac761-e679-4911-b5ea-a6a09c60d1cc">

**Expected behavior**
When you upgrade the version of chainlit, i am expecting to see the (almost) same result on previous version.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOs 14.6.1 (23G93)
- Browser Chroma
- Version 129.0.6668.58 (Official Build) (arm64)

**Comment by hadarsharon** [comment]
Hey @tugbayatilla Please try modifying your entrypoint as follows:

```
CMD ["chainlit", "run", "app.py", "--host", "0.0.0.0"]
```

This was a breaking change done as part of #861 
I believe listening at 0.0.0.0 should resolve your issue

**Comment by dokterbob** [comment]
Thanks @hadarsharon! 

@tugbayatilla I recommend you check the release notes before upgrading!

**Comment by tugbayatilla** [comment]
> Hey @tugbayatilla Please try modifying your entrypoint as follows:
> 
> ```
> CMD ["chainlit", "run", "app.py", "--host", "0.0.0.0"]
> ```
> 
> This was a breaking change done as part of #861 I believe listening at 0.0.0.0 should resolve your issue

That solves the problem. Thanks.
