### ISSUE TITLE
WebSocket Connection Error with Gunicorn and Multiple Workers

### ISSUE THREAD

**Issue by huoxiao-C** [Chainlit/chainlit#1369]
After mounting Chainlit to the FastAPI application, if the Gunicorn command is used to start the application and multiple processes are specified (using the -w option), an error will occur. The startup command is: gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:3010

### bug description
If the method based on FastAPI provided on the Chainlit official website (https://docs.chainlit.io/deploy/api) is used to mount Chainlit, and then the application is started using the Gunicorn command with multiple processes specified, such as: `gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:3010`, an error will be encountered on the web UI stating "Unable to connect to server".

Additionally, the console will display the following errors:

[2024-09-24 11:03:23 +0800] [10116] [INFO] connection closed
[2024-09-24 11:03:24 +0800] [10116] [INFO] ('127.0.0.1', 63124) - "WebSocket /chat/ws/socket.io/?EI0=4&transport=websocket&sid=TVH1xbI1HXjNDocwAAAK" 403
[2024-09-24 11:03:24 +0800] [10116] [INFO] connection rejected (403 Forbidden)
[2024-09-24 11:03:24 +0800] [10116] [INFO] connection closed
[2024-09-24 11:03:25 +0800] [10116] [INFO] ('127.0.0.1', 63129) - "WebSocket /chat/ws/socket.io/?EI0=4&transport=websocket&sid=i_R_YcNkA9SIqMBuAAAc" 403
[2024-09-24 11:03:25 +0800] [10116] [INFO] connection rejected (403 Forbidden)
[2024-09-24 11:03:25 +0800] [10116] [INFO] connection closed
### Chainlit mounting code:
```py
app = FastAPI()
@app.get("/")
def read_root():
    return {"message": "Hello, World!"}

mount_chainlit(app=app, target="src/chainlit_app.py", path="/chat").
```

### software information

- chainlit：1.1.402
- python：3.8.5
- Browser：google chrome
- OS：windows or linux

**Comment by dokterbob** [comment]
@dosu Could you suggest a more concise title for the issue? 

@huoxiao-C Do let us know whether the bot helped you out!

**Comment by huoxiao-C** [comment]
hello dokterbob，the bot method is not ok，we still cannot specify multiworker with gunicorn

**Comment by dokterbob** [comment]
@huoxiao-C Sorry it took a while.

Could you perhaps increase logging to provide a full traceback for the 403? Also, make sure you're on the latest version (we improved some things around error handling).

We need to know the exact code generating this error.

Should work roughly like this: https://search.brave.com/search?q=fastapi+logging+of+tracebacks&source=web&summary=1&conversation=7c7357e15d8a0fc3f88da7&summary_og=bb464324cb55a1e106371f

Could you also double check (if you haven't already) that `-w 1` doesn't generate the error?

**Comment by huoxiao-C** [comment]
@dokterbob hello dokterbob, thanks for your reply
1）There is no problem with setting the number of Gunicorn workers to 1. 
2）I tried the method you mentioned, the message is as flows. The web UI still show that connection to the server failed，
<img width="850" alt="3B38A34E-ADFB-4bec-A5A9-D36A59756A11" src="https://github.com/user-attachments/assets/9038f5f9-a167-456f-9f85-181e972075f5"> 
and the frontend server shows 
![image](https://github.com/user-attachments/assets/b602c65d-1fdd-4388-ba95-564d88d3a296)
。
### This is my testing code
_**main.py**_
```
import traceback
from chainlit.utils import mount_chainlit
from fastapi import FastAPI, HTTPException
from fastapi.exceptions import RequestValidationError
from fastapi.responses import PlainTextResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

app = FastAPI()


@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request, exc):
    print(f"Exception: {exc}, Traceback: {exc.__traceback__}")
    print(f"new Traceback：", ''.join(traceback.format_tb(exc.__traceback__)))
    return PlainTextResponse(str(exc), status_code=exc.status_code)

mount_chainlit(app=app, target="cl_test.py", path="/chat")
```

_**cl_test.py**_
```
import chainlit as cl
@cl.on_chat_start
async def on_chat_start():
    print("on_chat_start调用")
    guide_text = """Hi，我是DataAgent\n"""
    await cl.Message(guide_text).send()
```

**_app run command_**
```gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:3010```

**software information**
os：linux
python：3.9.20
chainlit：1.3.2
gunicorn：23.0.0

**Comment by dokterbob** [comment]
@huoxiao-C Sorry for the delay. Having learned more about the code, there is no persistence in sessions (ref #1513). Whatever chainlit stores about the session is thread-local, in memory.

That means that the only way to scale is to use sticky sessions supplied by the load balancer.

**Comment by dokterbob** [comment]
Would love feedback on #1575, please see if it can resolve your issue. We're also open to a suggested approach on cookie based sticky sessions.
