### ISSUE TITLE
Fix Tool Call Positioning and Step Loader Animation in Message UI

### ISSUE THREAD

**Issue by kevinwmerritt** [Chainlit/chainlit#1372]
**Describe the bug**

- Tool calls appear below the result message
- Step loader "skeleton" continues to animate after run is complete
- The result message appears as a second message rather than as part of the initial tool message as the [image in the README](https://github.com/Chainlit/chainlit/blob/main/images/quick-start.png) would suggest.

**To Reproduce**
<details><summary>All examples use this demo code from the README</summary>
<p>

```python

import chainlit as cl


@cl.step(type="tool")
async def tool():
    # Fake tool
    await cl.sleep(2)
    return "Response from the tool!"


@cl.on_message  # this function will be called every time a user inputs a message in the UI
async def main(message: cl.Message):
    """
    This function is called every time a user inputs a message in the UI.
    It sends back an intermediate response from the tool, followed by the final answer.

    Args:
        message: The user's message.

    Returns:
        None.
    """

    final_answer = await cl.Message(content="").send()

    # Call the tool
    final_answer.content = await tool()

    await final_answer.update()
```
</p>
</details> 

Using default config:

```toml
cot = "full"
```

![area1](https://github.com/user-attachments/assets/40a9fbfa-215a-4b4e-ab7e-f1b742ee3152)

Using default config:

```toml
cot = "tool_call"
```

![Area2](https://github.com/user-attachments/assets/94790576-81f8-4fde-a684-59e65fcc64a7)

**Expected behavior**
Message UI looks like what is described in the documentation [here](https://docs.chainlit.io/concepts/step#a-simple-tool-calling-example).

**Desktop (please complete the following information):**

- Mac 14.7 (23H124)
- Chrome 128.0.6613.138 (Official Build)

**Additional context**
More test cases are needed to to help lock in the expected behavior given the variety of ways to compose steps and messages. The message UI has changed considerably in 2024. I hope it can start to stabilize and have some tests so that regressions can be caught as it adds friction to staying up to date.

Possibly related:
- https://github.com/Chainlit/chainlit/issues/1230
- https://github.com/Chainlit/chainlit/issues/1254
- https://github.com/Chainlit/chainlit/issues/1228

**Comment by dokterbob** [comment]
@kevinwmerritt Love to hear whether you consider the reply by our beloved bot (which we're still test-driving) relevant or applicable!

Also interested as to the experiences of other users vis-a-vis tool reporting.

@dosu Could you please suggest a more specific/applicable title for the issue? Are there any similar or related issues? If not, rather than relevant to the chainlit library, might it be something about this user's specific use case (do we know enough about their specific use case?)?

**Comment by dokterbob** [comment]
@kevinwmerritt The centering PR has been recently merged and isn't on main yet. Could try and replicate this issue on main? Perhaps it's already been resolved?

**Comment by kevinwmerritt** [comment]
Thanks @dokterbob for looking at this.

I believe that @willydouhard had this working properly but it has regressed in recent months. I liked the UI decisions that were made.

Right now when someone new to this project follows the demo in the readme or the documentation they will get a different result than what the screenshot in the readme or docs imply.

This is not a good onboarding experience.

I just would like to see the message UI get back to what @willydouhard intended.

@dokterbob what branch are you referring to?

**Comment by kevinwmerritt** [comment]
Here is a video of how https://help.chainlit.io/ works with a tool call:

![Area3](https://github.com/user-attachments/assets/8ea6d22c-5448-4292-81f1-9d7b4087e1da)

I'm not sure what version help.chainlit.io is currently running, but in 1.2.0 the behavior is different and/or broken.

**Comment by dokterbob** [comment]
> @dokterbob what branch are you referring to?
main

**Comment by puppetm4st3r** [comment]
also happen when you send manual messages from copilot web site to backend and then copilot front render of the message is not in expected order

**Comment by willydouhard** [comment]
Since the new COT changes, you no longer have to pre send an empty message to display the loader.

This is more natural and will work as intended:
```py
import chainlit as cl


@cl.step(type="tool")
async def tool():
    # Fake tool
    await cl.sleep(2)
    return "Response from the tool!"


@cl.on_message  # this function will be called every time a user inputs a message in the UI
async def main(message: cl.Message):
    """
    This function is called every time a user inputs a message in the UI.
    It sends back an intermediate response from the tool, followed by the final answer.

    Args:
        message: The user's message.

    Returns:
        None.
    """


    # Call the tool
    tool_res = await tool()

    await cl.Message(content=tool_res).send()
    ```
    I am going to update the docs!

**Comment by kevinwmerritt** [comment]
Thanks @willydouhard. That makes a lot of sense.

Here is what I'm seeing now:

- When using the step decorator, the tool message does not "complete" in the UI.
- It properly says "Using <tool name>" but does not say "Used <tool name>" at the end.

![Area4](https://github.com/user-attachments/assets/0f8cdd30-37f3-45f1-94c1-20ab209ccfa5)

This is with `1.2.0`

**Comment by kevinwmerritt** [comment]
I resolved by updating my translation file.
