### ISSUE TITLE
Chainlit 1.2.0 breaks SQLAlchemyDataLayer

### ISSUE THREAD

**Issue by itonskie** [Chainlit/chainlit#1375]
**Describe the bug**
In Chainlit version 1.2.0, the new BaseDataLayer class has abstract methods implemented, which causes compatibility issues with SQLAlchemyDataLayer. Specifically, I encounter the following error when trying to instantiate SQLAlchemyDataLayer:

Traceback (most recent call last):
  File "/workspaces/Bluedrive_Chatbot_v3/bluedrive_chatbot.py", line 20, in <module>
    SQLAlchemyDataLayer(conninfo=conninfo)
TypeError: Can't instantiate abstract class SQLAlchemyDataLayer with abstract method get_element

**To Reproduce**

1. Use Chainlit version 1.2.0.
2. Try to instantiate SQLAlchemyDataLayer
3. Run the script

**Expected behavior**
I expect it to instantiate SQLAlchemyDataLayer without this error

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Ubuntu]
- Version [22.04]

**Additional context**
Looked at the previous version. 1.1.404. it works up until that point

**Comment by dokterbob** [comment]
This has been solved with #1346. We'll do a fixup release soon!
