### ISSUE TITLE
Migrating from 1.1.200 to 1.1.300 Custom Endpoints

### ISSUE THREAD

**Issue by Physium** [Chainlit/chainlit#1387]
Is the only way to use custom endpoints by mounting chainlit as a FastApi sub application? The previous approach of importing app from chainlit.server works for my usecase because there was only a need for an additional endpoint, it doesnt make sense now that i have to deploy a whole FastApi application just to have 1 api and make my chainlit a sub app.

**Comment by dokterbob** [comment]
@Physium Yes, you'll have to deploy a 'whole' FastAPI application.

As you see in the docs, it'll take all of some 7 lines. https://docs.chainlit.io/integrations/fastapi#fastapi
I am confident, you can manage! ;)

**Comment by Physium** [comment]
Appreciate your confirmation in this. The example shows how easy it is no doubt, but migrating to this approach from an existing project built around the previous design requires significant effort. Not that it's your problem but yea I wish it was "7 lines".
