### ISSUE TITLE
User Sessions shared across multiple users behind Proxy or VPN

### ISSUE THREAD

**Issue by dvdr00t** [Chainlit/chainlit#1407]
**Describe the bug**  
When multiple users access the Chainlit application from the same IP (e.g., when behind a proxy or VPN), the `user_session` is shared across those users, leading to data from one session being accessible by another. This results in a mixing of session data, causing unexpected behavior, such as retrieving or storing incorrect session-specific information.

**To Reproduce**  
1. Deploy a Chainlit application and expose a specifc port to the internet.
2. Have two or more users access the application through a proxy or VPN (e.g., an office network).
3. Each user sets and retrieves session-specific data using `cl.user_session.set()` and `cl.user_session.get()`.
4. Observe that session data from one user is accessible by another.

**Expected behavior**  
Each user should have a unique session, even when accessing the application from the same IP address, ensuring that session-specific data remains private to each user.

**Screenshots**  
If applicable, add screenshots to help explain the problem.

**Desktop (please complete the following information):**  
- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**  
- Device:
- OS:
- Browser:
- Version:

**Additional context**  
The issue seems to stem from how user sessions are identified and stored. In the current setup, it appears that sessions are identified solely by the session ID, which may not be properly isolated for different users behind the same IP. As a result, users sharing the same IP (e.g., through a corporate proxy or VPN) can end up sharing the same session, causing a mix-up of session data.

**Comment by dokterbob** [comment]
#1442 is probably related.

**Comment by dokterbob** [comment]
Should be resolved with #1575. Would love feedback as to whether indeed the issue is resolved!
