### ISSUE TITLE
LlamaIndexCallbackHandler() - langchain_rename interaction

### ISSUE THREAD

**Issue by jimmarshall87** [Chainlit/chainlit#141]
Not 100% sure of this but would I be correct to say that for subtasks involving the LlamaIndexCallbackHandler that the langchain_rename override method is not called?

Or to put it another way, it is not currently possible to override the author name for LlamaIndex based interactions? 

If so, it would be great to be able to!

**Comment by willydouhard** [comment]
It might work if you pass a `LangchainCallbackHandler` to your langchain agent as well as passing a `LlamaIndexCallbackHandler` to the llama instance

**Comment by jimmarshall87** [comment]
no dice I'm afraid. I already had `response = await cl.make_async(agent)(input_str, callbacks=[cl.LangchainCallbackHandler()])` in the `@cl.langchain_run` and then `service_context = ServiceContext.from_defaults(llm_predictor=self.current_query_llm_predictor, callback_manager=CallbackManager([cl.LlamaIndexCallbackHandler()]))` in the part dealing with Llama Index. I then roll the tool up into LangChain with 
```tool_config = IndexToolConfig(
                query_engine = query_engine,
                name=repo["tool_name"],
                description=repo["tool_description"],
                tool_kwargs={"return_direct": True}
            )
            self.tools.append(LlamaIndexTool.from_tool_config(tool_config))```

But if I make `@cl.langchain_rename` like this:

```
@cl.langchain_rename
def rename(orig_author: str):
    logger.info(f"Author: {orig_author}")
    rename_dict = {
        "llm": "MyAuthor",
        "LLMChain": "MyAuthor",
        "retrieve": "MyAuthor",
     
    }
```
The method is only called when `orig_author == "LLMChain"`

**Comment by willydouhard** [comment]
Ah yes it will only work for the langchain agent, not for the llama steps like retrieve. Good catch! Will fix this

**Comment by jimmarshall87** [comment]
> Ah yes it will only work for the langchain agent, not for the llama steps like retrieve. Good catch! Will fix this

Good man! Keep up the great work!

**Comment by willydouhard** [comment]
Fixed with https://docs.chainlit.io/api-reference/author-rename
