### ISSUE TITLE
Getting the Import Error issue

### ISSUE THREAD

**Issue by adithyaboyapati** [Chainlit/chainlit#143]
ImportError: dlopen(/Users/users/anaconda3/envs/env1/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

**Comment by willydouhard** [comment]
Looks like a duplicate of https://github.com/Chainlit/chainlit/issues/56
