### ISSUE TITLE
AskUserMessage printing the message in the wrong order

### ISSUE THREAD

**Issue by juliouyehara** [Chainlit/chainlit#1437]
I'm facing a problem, when I use AskUserMessage, the input message appears on the screen, I'm sending instruction messages right after requesting the input through AskUserMessage, the problem is that after I make the input, it should appear in sequence on the screen. the instructions, but what happens is that the input goes down and stays after the instructions, and in other parts like selecting the user action the same error occurs.

Assistent: Qual o seu cdfazenda ?

Assistent:
Oi, eu sou a Rúmi! Sua assistente para consulta e cadastro de dados no Ideagri!
Como você pode falar comigo:
💬: Texto
🗣️: Áudio
🖼️: Imagem

O que eu sei?

Resumo de cada animal
Animais vazios
Previsões de parto
Previsões de secagem
Previsões de desmama
🕒 Em tempo real

O que eu posso cadastrar?

Partos
Aptidão
Diagnósticos de Gestação
Pesagens
Ordenhas
Secagem
Baixa de animais

User: 26250

**Comment by juliouyehara** [comment]
@dosu a part of my code, 
The expectation is that the cdfazenda input appears first, but after the AskUserMessage input, cdfazenda appears last.

How can I track the messages and how can I correct this error in code?
:

if cdfazenda is None:
        res = await cl.AskUserMessage(content="Qual o seu cdfazenda ?", timeout=20).send()

    try:
        cl.user_session.set("cdfazenda", res['output']) 
    except:
        pass

    await cl.Message(content="Oi, eu sou a Rúmi! Sua assistente para consulta e cadastro de dados no Ideagri!\n \
                            Como você pode falar comigo: \n \
                            💬: Texto \n \
                            🗣️: Áudio \n \
                            🖼️: Imagem \n \
                            \n O que eu sei? \n \
                            \n- Resumo de cada animal ).send()

**Comment by juliouyehara** [comment]
@dosu the logger is:

2024-10-15 19:57:26 - Sending AskUserMessage for cdfazenda
2024-10-15 19:57:29 - Received cdfazenda input: 26250
2024-10-15 19:57:29 - Sending instruction message

 But the output is 
 
Assistant: Qual o seu cdfazenda ?


Assistant:
Oi, eu sou a Rúmi! Sua assistente para consulta e cadastro de dados no Ideagri!
Como você pode falar comigo:
💬: Texto
🗣️: Áudio
🖼️: Imagem

O que eu sei?

Resumo de cada animal
Animais vazios
Previsões de parto
Previsões de secagem
Previsões de desmama
🕒 Em tempo real

O que eu posso cadastrar?

Partos
Aptidão
Diagnósticos de Gestação
Pesagens
Ordenhas
Secagem
Baixa de animais

User: 26250

**Comment by juliouyehara** [comment]
@dosu i put a time sleep and this is the logger:

2024-10-15 20:02:50 - Sending AskUserMessage for cdfazenda
2024-10-15 20:02:56 - Received cdfazenda input: 26250
2024-10-15 20:03:06 - Sending instruction messag

How can I guarantee that the printout of the message in the chat will not move to the last position, because what happens is that the message appears asking for cdfazenda, I put cdfazenda and with time sleep the code waits 10 seconds before sending the instructions , and when it is sent, cdfazenda goes to the last position in the screen chat, remembering that this code is in the @on_chat_start decorator, and it does not invoke @on_message which even presents the same error

**Comment by juliouyehara** [comment]
@dosu 
Okay, my code is in this format, AskUSerMessage is sent before sending instructions, what can I do besides these instructions you gave me to deal with the error

**Comment by juliouyehara** [comment]
@dosu 

res = await cl.AskUserMessage(content="Qual o seu cdfazenda ?", timeout=20).send()


In this code there is a way to omit what was typed in the chat, so I can configure the user input so that the code sends the message?

**Comment by yyoussef11** [comment]
@juliouyehara  any luck on this issue ? 
I am facing the same issue and it's annoying

**Comment by juliouyehara** [comment]
@yyoussef11 i've resolved this issue installing chainlit version 1.1.306

**Comment by yyoussef11** [comment]
@dokterbob 
actually i have found the issue on my current when i was using cl.AskActionMessage followed with a check on the result and then AskUserMessage.

I am currently running chainlit v1.2.0 (latest stable)

When using cl.Action only with a message and then handling the cl.AskUserMessage in the callback function, the issue was not faced.

I have described my code under this issue: https://github.com/Chainlit/chainlit/issues/1429

**Comment by gcleaves** [comment]
I was suffering the same problem of out-of-order messages and it went away after downgrading from 1.2.0 to 1.1.306.

**Comment by yyoussef11** [comment]
@dokterbob  i don't think downgrading should considered a fix for this issue.
I would appreciate if you can re-open this issue and try to help us understand what could be the root cause.
cl.AskUserMessage works fine when in a callback function
but doesn't when it's used directly

**Comment by yyoussef11** [comment]
@dokterbob 
have a look on this thread :
https://github.com/Chainlit/chainlit/issues/1230

**Comment by previacita** [comment]
same problem
