### ISSUE TITLE
Reloading all imported files on change

### ISSUE THREAD

**Issue by dissorial** [Chainlit/chainlit#146]
My chainlit app is set up with multiple files, such as `app.py`, `metadata.py`, `utils.py` and so on. I run the app with `chainlit run app.py -w`. In `app.py`, I make imports such as `from utils import FUNCTIONS_MAPPING` or `from metadata import FUNCTIONS_METADATA`. 

Whenever I make a change in app.py, the app gets reloaded/refreshed, which makes sense given the `-w` flag. However, when I make a change in a file like 'metadata.py' or 'functions.py', the app is not reloaded. Instead, I have to shut down the app and run it again for the changes to be included. 

Is there a way I can configure the 'chainlit run app.py -w' script (or write a new script) that will allow me to define which files in my directory it should be looking for changes in?

**Comment by willydouhard** [comment]
Are those files in your application root folder?

**Comment by dissorial** [comment]
Yes

**Comment by willydouhard** [comment]
I can't reproduce, changing any python file in the root dir does trigger an app reload, even if that file is not imported.

this is the actual logic:

```py
async def watch_files_for_changes():
            extensions = [".py"]
            files = ["chainlit.md", "config.toml"]
            async for changes in awatch(config.root, stop_event=stop_event):
                for change_type, file_path in changes:
                    file_name = os.path.basename(file_path)
                    file_ext = os.path.splitext(file_name)[1]

                    if file_ext.lower() in extensions or file_name.lower() in files:
                        logger.info(
                            f"File {change_type.name}: {file_name}. Reloading app..."
                        )
 ```
 
 So as long as the file you edit has a `.py` extension, it it supposed to work.

**Comment by xleven** [comment]
My observation: imports from a sub package, e.g. `from app.utils import foo` in target.py, will not reload correctly when `foo` in `app/utils.py` is modified. Guess it's due to the `app/__pycache__` folder created during runtime. Sometimes even a restart of chainlit won't take the changes into effect so I do a manual `rm -rf **/__pycache__`.

**Comment by willydouhard** [comment]
So the file watcher is working but your python module is cached if I understand correctly?

**Comment by xleven** [comment]
Yes exactly. I tried to understand `load_module()` func in config.py but haven't figure it out.

**Comment by umarbutler** [comment]
I am experiencing the same issue as @dissorial. Changes to modules in my root directory cause the app (i.e., `app.py`) to reload but not the changed module in question. The issue persists regardless of whether I use `from` or not (i.e., `import utils` and `from utils import xyz` both don't work).

**Comment by ramnes** [comment]
We should probably just reload the process rather than trying to eval files, which is very fragile in general.

**Comment by umarbutler** [comment]
If reloading the process means that all modules will be reloaded, then I'd prefer for that not to happen. One of my modules loads embeddings into RAM so I don't want that to be reloaded every time I change a file. The workaround I'm employing at the moment is:
```python
import chainlit
import importlib
import module_that_should_not_be_reloaded
import module_that_should_be_reloaded
import module_that_should_be_reloaded_2

importlib.reload(module_that_should_be_reloaded)
importlib.reload(module_that_should_be_reloaded_2)
```

The downside to this workaround is that you cannot choose to reload only the module has been changed.

**Comment by ramnes** [comment]
Can't you mmap the embeddings or offload them in another process? I think this would be a good practice in any case.

**Comment by willydouhard** [comment]
I think the [cache](https://docs.chainlit.io/api-reference/cache) feature might be helpful.

**Comment by umarbutler** [comment]
> Can't you mmap the embeddings or offload them in another process? I think this would be a good practice in any case.

I hadn't thought of this option, thanks for sharing!

**Comment by 1jacky** [comment]
your home path of chainlit different with import root path
