### ISSUE TITLE
SQLAlchemy Data Layer: Switch to more generic ORM layer

### ISSUE THREAD

**Issue by niklasdiehm** [Chainlit/chainlit#1460]
**Is your feature request related to a problem? Please describe.**
Pull request #836 was very nice to support sqlalchemy based data persistence.
However, the sqlalchemy data layer only works with postgres db. Whenever a change is made in the data layer, one must change the respective self written file for mssql, mysql, ...

**Describe the solution you'd like**
If you would change the implementation of the functions from query-strings to an more generic ORM-based approch (see [SQL alchemy ORM](https://docs.sqlalchemy.org/en/20/orm/), the sqlalchemy data layer would support any database supported by sqlalchemy with only the need to pass a connection string or engine object.

**Describe alternatives you've considered**
Alternatives would be to rename the sqlalchemy data layer to postgres data layer and add files for other databases, e.g. mssql and mysql. This would however require even more work to do when changing something at the data layer.

**Additional context**
I am willing to contribute to a feature request with maybe some help needed

**Comment by dokterbob** [comment]
@niklasdiehm Please have a look, there's someone already working on a PR for this. I'm not sure about the status but they might need some help.

In addition, our current priority is making data layers properly pluggable, and migrating them to a community-run repo in the coming weeks!
