### ISSUE TITLE
Elements don't display when using authentication in 1.3.0 & 2.0.dev1

### ISSUE THREAD

**Issue by hayescode** [Chainlit/chainlit#1472]
**Describe the bug**
Since updating version from 2.0.dev0 to 1.3.0 & 2.0.dev1 no elements display when using authentication or authentication+data layer. The elements are successfully persisted, and resuming chats display the elements correctly, but not when the user is actually interacting. They either say "An error has occurred, or loading, or some other error.

I believe this is related to **Authentication** but I have included examples with the data layer too.

Looking at the [diff between these versions](https://github.com/Chainlit/chainlit/compare/2.0.dev0...1.3.0) I cannot figure it out! @dokterbob @willydouhard any ideas?

> [!NOTE]  
> Elements do not work when only using authentication (no data layer)

## Example 1
```py
import chainlit as cl
import pandas as pd
import chainlit.data as cl_data
from chainlit.data.sql_alchemy import SQLAlchemyDataLayer
from chainlit.data.storage_clients.azure import AzureStorageClient

adls = AzureStorageClient(account_url=..., container=..., credential=credential, sas_token=...)
db = cl_data._data_layer = SQLAlchemyDataLayer(conninfo=..., ssl_require=True, storage_provider=adls, user_thread_limit=100, show_logger=True)

@cl.oauth_callback
def login(provider_id: str, token: str, raw_user_data: Dict[str, str], default_user: cl.User, id_token: Optional[str]) -> Optional[cl.PersistedUser]:
    return default_user

@cl.on_chat_start
async def start():
    text_content = "Hello, this is a text element."
    elements = [
        cl.Text(name="simple_text", content=text_content, display="inline")
    ]

    await cl.Message(
        content="Check out this text element!",
        elements=elements,
    ).send()
```
![image](https://github.com/user-attachments/assets/0010911a-bf2f-4f88-ac49-d44be9c06ec9)

## Example 1 (Auth Only)
```py
import chainlit as cl

@cl.oauth_callback
def login(provider_id: str, token: str, raw_user_data: Dict[str, str], default_user: cl.User, id_token: Optional[str]) -> Optional[cl.PersistedUser]:
    return default_user

@cl.on_chat_start
async def start():
    text_content = "Hello, this is a text element."
    elements = [
        cl.Text(name="simple_text", content=text_content, display="inline")
    ]

    await cl.Message(
        content="Check out this text element!",
        elements=elements,
    ).send()
```
![image](https://github.com/user-attachments/assets/0010911a-bf2f-4f88-ac49-d44be9c06ec9)

## Example 2
```py
import chainlit as cl
import pandas as pd
import chainlit.data as cl_data
from chainlit.data.sql_alchemy import SQLAlchemyDataLayer
from chainlit.data.storage_clients.azure import AzureStorageClient

adls = AzureStorageClient(account_url=..., container=..., credential=credential, sas_token=...)
db = cl_data._data_layer = SQLAlchemyDataLayer(conninfo=..., ssl_require=True, storage_provider=adls, user_thread_limit=100, show_logger=True)

@cl.oauth_callback
def login(provider_id: str, token: str, raw_user_data: Dict[str, str], default_user: cl.User, id_token: Optional[str]) -> Optional[cl.PersistedUser]:
    return default_user

@cl.on_chat_start
async def start():
    iris = pd.read_csv(
        "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
    )

    elements = [cl.Dataframe(data=iris_doubled, display="inline", name="Dataframe")]

    step = cl.Step(name="dataframe", parent_id=cl.context.current_step.id)
    await step.stream_token("This message has a Dataframe")
    step.elements = elements
    await step.update()
```
![image](https://github.com/user-attachments/assets/a85a25f1-f807-416f-8810-88596b05d9b8)

**Comment by hayescode** [comment]
@dosu any ideas?

**Comment by hayescode** [comment]
FOUND IT! @dokterbob #1441 is the culprit. Reverting just this change fixes it. It looks like @wenboown [found this issue](https://github.com/Chainlit/chainlit/pull/1441#issuecomment-2425286714) as well.

**Comment by wenboown** [comment]
yes, it took me a full day to debug this problem since it is not obvious where to look. Hopefully the team can provide a patch soon.

**Comment by hayescode** [comment]
@wenboown 100% this was difficult to find.

The issue is specifically [here](https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/server.py#L898-L903). Commenting this out makes Elements work properly again.

@dokterbob @willydouhard I'm going to make a PR to revert this.

**Comment by xavidop** [comment]
I am facing the same issue, gonna revert back to 1.2.0 for now

**Comment by hayescode** [comment]
https://github.com/Chainlit/chainlit/pull/1474

**Comment by dokterbob** [comment]
Thanks for your courage figuring this out. I think I see the problem already, let me attempt a quick fix.

**Comment by dokterbob** [comment]
I just replicated it with this minimal example:
```
from typing import Dict, Optional
import chainlit as cl


@cl.password_auth_callback
def auth_callback(username: str, password: str):
    # Fetch the user matching username from your database
    # and compare the hashed password with the value stored in the database
    if (username, password) == ("admin", "admin"):
        return cl.User(
            identifier="admin", metadata={"role": "admin", "provider": "credentials"}
        )
    else:
        return None


@cl.on_chat_start
async def start():
    text_content = "Hello, this is a text element."
    elements = [cl.Text(name="simple_text", content=text_content, display="inline")]

    await cl.Message(
        content="Check out this text element!",
        elements=elements,
    ).send()
```

**Comment by hayescode** [comment]
@dokterbob Feel free to close my PR if you can fix this without reverting the reason this was added in the 1st place. Once merged please make new releases because besides this issue this release improved lots of other things the community wants but we can't upgrade because of this.

**Comment by dokterbob** [comment]
> @dokterbob Feel free to close my PR if you can fix this without reverting the reason this was added in the 1st place. Once merged please make new releases because besides this issue this release improved lots of other things the community wants but we can't upgrade because of this.

I'm on it! Thanks for the report!

**Comment by dokterbob** [comment]
This is far as I've gotten today. Test replicates it but `useFetch()` is failing somehow. I'm not at all experienced with React (more of a Vue guy) so any help here is appreciated: https://github.com/Chainlit/chainlit/tree/dokterbo/1472-elements-data-layer

**Comment by dokterbob** [comment]
Maybe we can even fetch stuff in the same way we do elsewhere in the API and get rid of the entire useFetch system?

**Comment by wenboown** [comment]
> Alternatively, if we migrate to using a cookie for authentication, it would solve a lot of potential security pit falls and we won't need to supply auth headers explicitly.

How much work would this involve and whether it is on your roadmap for future development already? It might be better to "do it properly" rather than quick patch if you already plan to spend time on migrating to cookie?

**Comment by hayescode** [comment]
> I'm not at all experienced with React

@dokterbob me neither, sorry i can't help on that front

**Comment by hayescode** [comment]
@dokterbob why don't you merge #1474 and make a 1.3.1 release while you figure this out if it's going to take more than 1 day? The last stable release imo is 1.1.404 which is what my users are on and that release contains this "massive vunerability" that exists since forever. At least a new release would be useable in the meantime.

**Comment by dokterbob** [comment]
> @dokterbob why don't you merge #1474 and make a 1.3.1 release while you figure this out if it's going to take more than 1 day? The last stable release imo is 1.1.404 which is what my users are on and that release contains this "massive vunerability" that exists since forever. At least a new release would be useable in the meantime.

In short, I'm reluctant shipping a release knowingly re-introducing a high risk security issue. That doesn't seem to me to be the responsible thing to do. I hope to push a fix out this morning though.

In the mean time, you are welcome to just run chainlit from the hotfix branch:
```
pip install git+https://github.com/hayescode/chainlit@patch-3#subdirectory=backend/
```

**Comment by dokterbob** [comment]
@hayescode Are you on Discord? Would love to connect.
