### ISSUE TITLE
Elements not loading(401) after oath integration.

### ISSUE THREAD

**Issue by rv59-njit** [Chainlit/chainlit#1476]
We have image elements with the following code in our chat app:

```
    map_image = cl.Image(path="./public/map.png", name="image1", display="inline")
    final_answer.elements = [map_image]
```

This was working fine until we added auth integration using auth0. Now, images are not loading because of 401 error with the following error:

```
{"detail":"Invalid authentication token"}
```

```
src="https:/xxxxxxxxxxxxx.com/project/file/27b79c3b-d425-4660-b7f7-2500fbe0d4ef?session_id=cfa5ecb7-ef16-48b6-a655-04810f28b776"
```

Can you please tell us how we can bypass authentication for public images in our project?

P.S. we are using chainlit 1.3

**Comment by hayescode** [comment]
See https://github.com/Chainlit/chainlit/issues/1472

I have PR #1474 open to revert it.

**Comment by dokterbob** [comment]
Dup of #1472
