### ISSUE TITLE
Load spinner not showing up in newer chainlit versions.

### ISSUE THREAD

**Issue by nookbe-dg** [Chainlit/chainlit#1480]
**Describe the bug**
The load spinner (previously a dot, in later versions a load bar with text) is not showing up.
Only when i downgrade chainlit to chainlit==1.1.300 it appears again.

**To Reproduce**
e.g. use chainlits newest 1.3 version.

- OS: iOS
- Browser chrome

**Comment by nookbe-dg** [comment]
As a quick fix, i now use the Step class to display the user some sort of loading.

**Comment by previacita** [comment]
Same problem!
