### ISSUE TITLE
Send/Stream messages from multiple different processes

### ISSUE THREAD

**Issue by MohMaz** [Chainlit/chainlit#1491]
**Is your feature request related to a problem? Please describe.**
It's a feature that might already be supported somehow.

**Describe the solution you'd like**
I want to have the UI run on one server, and be able to **send/stream messages to it from two or more processes** (e.g. VMs). I'm trying to integrate chainlit with a [Autogen distributed group chat sample](https://github.com/microsoft/autogen/tree/main/python/packages/autogen-core/samples/distributed-group-chat)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dokterbob** [comment]
You would probably run chainlit as usual, then forward messages from your VM's to chainlit. So like a normal chainlit app.
I.e. it does not require any changes in functionality on chainlit's side.

Does that make sense? If not, feel free to reopen.

**Comment by MohMaz** [comment]
> You would probably run chainlit as usual, then **forward messages from your VM's to chainlit**. So like a normal chainlit app. I.e. it does not require any changes in functionality on chainlit's side.

Thanks for the reply. I'm not sure about how to forward, I was hoping to be able to get a client-ish connected to the server. 
So if I do this code in two different python files and run with `chainlit` command, it tried to spin up the server twice and get port binding error.

```python
@cl.on_chat_start  # type: ignore
async def start_chat():
    set_all_log_levels(logging.ERROR)
    warnings.filterwarnings("ignore", category=UserWarning, message="Resolved model mismatch.*")
    asyncio.run(main(load_config()))
```



If in the second app I just do:

```python
import chainlit as cl
await cl.Message("Hello!").send()
```

I get an error that context is not properly initialized. I tried to use the functions in `chainlit.context` like `init_*` or `get_context`, but wasn't able to make it work.

So was hoping to get a sample code on to connect.

**Comment by dokterbob** [comment]
User agent (browser) <- (client) Chainlit API (socket.io events over WebSocket) (server) -> Chainlit backend <- (client) custom API (could use parts of Chainlit API) (server) -> Execution backend

If you need more support with specific architecture, that's what I do as a freelance consultant -- so beyond the scope of Chainlit maintenance.

**Comment by dokterbob** [comment]
#1481 seems related.
