### ISSUE TITLE
Support follow_symlink=True in Bazel environment for static file mounting

### ISSUE THREAD

**Issue by allene-ha** [Chainlit/chainlit#1512]
**Description:**
I encountered an issue when trying to serve static files in my Chainlit app using Bazel. Files in the public directory weren’t being mounted successfully. After debugging, I found that adding the `follow_symlink=config.project.follow_symlink` parameter to [this mount function](https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/server.py#L208-L212) resolved the issue, allowing static files to be served as expected in the Bazel environment.

Could this parameter be set to `config.project.follow_symlink` by default in future releases? This would help improve compatibility with Bazel and similar environments that rely on symlinks for dependencies.

**Additional Context:**
A similar issue was reported in #317, where adding `follow_symlink=True` resolved the problem for Bazel setups. Implementing this change directly would prevent repeated manual adjustments.

Thank you!

**Comment by dokterbob** [comment]
Thanks for the feedback. I'm happy to merge a PR clarifying this parameter and it's use case but for security reasons it's generally considered a bad idea to follow symlinks, especially to do it by default!

**Comment by allene-ha** [comment]
Thank you for the explanation. I’ve recognized the potential security risks associated with `follow_symlink=True`. Would it be possible to add support for follow_symlink as a parameter? This way, I could control the setting through configuration rather than it being enabled by default.
