### ISSUE TITLE
disabled microphone

### ISSUE THREAD

**Issue by cesi08** [Chainlit/chainlit#1516]
with chainlit version 1.2.0 in wich way i can disable/hide  the microphone?
![image](https://github.com/user-attachments/assets/9cb03db0-0bbe-4fe8-a6f6-71f551ed9b41)

**Comment by dokterbob** [comment]
@dosu Anything in the config for disabling audio or the microphone?

**Comment by cesi08** [comment]
@dosu i have try

```
from chainlit.config import config
config.features.audio.enabled = False
```



but the microphone still appared

**Comment by cesi08** [comment]
it does not work

``
from chainlit.config import config, reload_config
config.features.audio.enabled = False
reload_config()

**Comment by cesi08** [comment]
@dosu ? suggestion?

**Comment by cesi08** [comment]
@dosu not works

**Comment by dokterbob** [comment]
> @dosu i have try
> 
> ```
> from chainlit.config import config
> config.features.audio.enabled = False
> ```
> 
> but the microphone still appared

Config updating doesn't really work (its on the roadmap). You'd best edit the config file on-disk, then restart chainlit.

Let me know if there's any issues with that, in which case you can re-open this issue.

**Comment by cesi08** [comment]
@dokterbob  in wich way i can edit config.toml? beacause i ve tried 

[features.audio]
    enabled = false

but didn't work
