### ISSUE TITLE
Permissions denied after upgrade to 1.3.2

### ISSUE THREAD

**Issue by vikbehal** [Chainlit/chainlit#1517]
**Describe the bug**
After upgrading chainlit from 1.1.306 to 1.3.2 for security issue[https://github.com/Chainlit/chainlit/pull/1493], I am seeing below error while application is being deployed on aks after upgrading package.

**To Reproduce**

1. Upgrade chainlit to 1.3.2
2. Build image and deploy on aks. Please image is deployed to read only directory. This worked without any issue in 1.1.306.
3. Check pod logs

**Expected behavior**
The application should run without any error.

**Screenshots**
![image](https://github.com/user-attachments/assets/c71c962e-ff83-4bdf-8faa-efd1205dc318)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Edge
- Version 130

**Smartphone (please complete the following information): NA**

**Additional context**
NA

**Comment by dokterbob** [comment]
@vikbehal You might want to commit the translations. Chainlit automatically writes these files on first start. Kind of an anti-feature, and on the roadmap, but nothing to do with 1.3.2 (just new languages added).
