### ISSUE TITLE
Elements don't show when using HTTPS

### ISSUE THREAD

**Issue by jbcallaghan** [Chainlit/chainlit#1526]
Issue:
Elements aren't being displayed when using HTTPS with the Chainlit app and resuming a chat. (Chainlit 1.3.2)

Reproduce:

This app uses a custom storage client for Minio and S3 compatibility with SQLAlchemyDataLayer. Elements are displayed correctly when not using HTTPS. Tried both NGINX for SSL and directly within Chainlit and the results are the same where in the element block, the text "An error occurred" is displayed instead of the actual elements on chat resume or viewing an existing chat from history.

Debugging, I can see that the code SQLAlchemyDataLayer retrieves the correct URL reference from Minio for the bucket and object and copying and pasting the URL in a browser opens as expected.

The content of the bucket object in question is a few lines of markdown text.

<--- Custom Storage Client - showing only change from S3, which includes endpoint URL -->
from typing import Any, Dict, Union

import boto3 
from chainlit.data.storage_clients import BaseStorageClient
from chainlit.logger import logger

class MinioStorageClient(BaseStorageClient):
    """
    Class to enable Minio storage provider using S3 compatibility
    """

    def __init__(self, bucket: str, endpoint_url: str, acces_key_id: str, secret_access_key: str):
        try:
            self.bucket = bucket
            self.client = boto3.client('s3',
                endpoint_url=endpoint_url,
                aws_access_key_id=acces_key_id,
                aws_secret_access_key=secret_access_key,
            )
            self.url = f"{endpoint_url}/{bucket}"
            logger.info("MinioStorageClient initialized")
        except Exception as e:
            logger.warn(f"MinioStorageClient initialization error: {e}")

Expected:
Resume chat should display markdown or other elements correctly using either HTTPS or HTTP in Chainlit.

Desktop:
- Windows 11
- Latest Chrome, Edge and Opera

**Comment by dokterbob** [comment]
Thanks for the feedback @jbcallaghan. What are you getting in the browser's JS console?
What does the URL of the element, as it is referred to in your browser's DOM, look like?

**Comment by jbcallaghan** [comment]
Thanks, I took a proper look and can see it is complaining because Minio is being served on HTTP and Chainlit on HTTPS. 

index-DnjoDoLU.js:332 Mixed Content: The page at 'https://chainlit_app_address_here/thread/xxxxx' was loaded over HTTPS, but requested an insecure resource 'http://minio_address_here/bucket_here/xxxx/xxxxx'. This request has been blocked; the content must be served over HTTPS.

**Comment by jbcallaghan** [comment]
You can resolve, I managed to fix the issue by enabling HTTPS for Minio. Thanks for your help

**Comment by jbcallaghan** [comment]
Issue resolved
