### ISSUE TITLE
@cl.on_stop isn't working

### ISSUE THREAD

**Issue by Jaquavious-Finkleton** [Chainlit/chainlit#1539]
**Describe the bug**
Hello Chainlit Devs, I have this chatbot app and it has a `@cl.on_stop` function to it, but it won't work. When I click the button to stop the assistant from generating its response, it'll either continue to generate its response further, then stop, or it'll not work at all and the assistant will finish generating its response then say "`Task manually stopped.`" instead of the custom messaging I want it to display. It's basically like a train, it doesn't come to a complete halt, it takes time for it to stop, or it won't at all.

**To Reproduce**
This is the same code in my project, that should reproduce the issue. Here it is:
```
#---------- ON STOP FUNCTION ----------#
@cl.on_stop
async def stop_task():
    cl.Message(
        author="Assistant",
        content="Task successfully stopped."
    ).send()
```

**Expected behavior**
I intend for the assistant to stop generating its response the moment I click the button, like how it's supposed to.

**Desktop**

- OS: Windows
- Browser: Microsoft Edge
- Version: 131.0.2903.63

**Smartphone**

- Device: OnePlus 10 Pro 5G
- OS: OxygenOS 14
- Browser: Google Chrome
- Version: Android 14

**Comment by HadarSha** [comment]
@ThatOneCoder20 You forgot to await the coroutine. Try with this minor modification (Added `await`):

```python
#---------- ON STOP FUNCTION ----------#
@cl.on_stop
async def stop_task():
    await cl.Message(
        author="Assistant",
        content="Task successfully stopped."
    ).send()
```

**Comment by hadarsharon** [comment]
@ThatOneCoder20 You forgot to await the coroutine. Try with this minor modification (Added `await`):

```python
#---------- ON STOP FUNCTION ----------#
@cl.on_stop
async def stop_task():
    await cl.Message(
        author="Assistant",
        content="Task successfully stopped."
    ).send()
```

**Comment by hadarsharon** [comment]
@ThatOneCoder20 Doubt you can do much about it as things currently stand, it seems like it's baked into Chainlit's code right now:

```python
@sio.on("stop")
async def stop(sid):
    if session := WebsocketSession.get(sid):
        trace_event("stop_task")

        init_ws_context(session)
        await Message(content="Task manually stopped.").send()

        if session.current_task:
            session.current_task.cancel()

        if config.code.on_stop:
            await config.code.on_stop()
```

If I were you I would just remove your message and leave it with the default one.

**Comment by hadarsharon** [comment]
@ThatOneCoder20 No, I meant it is built into Chainlit, this is a snippet from the following file: 

`.venv/lib/python3.12/site-packages/chainlit/socket.py`

If you want to use your own fork or something, it's there.
