### ISSUE TITLE
Compatibility issue with Chainlit 1.3.2 and Pydantic 2.10.2

### ISSUE THREAD

**Issue by Hamza-cpp** [Chainlit/chainlit#1556]
# Compatibility issue with Chainlit 1.3.2 and Pydantic 2.10.2  

## Description  
I'm encountering a `PydanticUserError` when attempting to run the `chainlit` command in my project using Chainlit 1.3.2 and Pydantic 2.10.2. The error suggests that `CodeSettings` is not fully defined and requires a rebuild of the dataclass. This issue occurs immediately upon invoking the `chainlit` CLI.  

---

## Steps to Reproduce  
1. Set up a Python environment (e.g., with `venv`).  
2. Install the following dependencies:
   - Chainlit: `1.3.2`
   - Pydantic: `2.10.2`
3. Run the `chainlit hello` command.  

---

## Expected Behavior  
The `chainlit hello` command should execute without errors, launching the Chainlit application as expected.  

---

## Observed Behavior  
The following traceback is encountered:  
```bash
(.venv) youssef@hp ~/Hamza_OK/Chef_Beldi  $ chainlit hello
Traceback (most recent call last):
  File "/home/youssef/Hamza_OK/Chef_Beldi/.venv/bin/chainlit", line 5, in <module>
    from chainlit.cli import cli
  File "/home/youssef/Hamza_OK/Chef_Beldi/.venv/lib/python3.12/site-packages/chainlit/__init__.py", line 18, in <module>
    from chainlit.action import Action
  File "/home/youssef/Hamza_OK/Chef_Beldi/.venv/lib/python3.12/site-packages/chainlit/action.py", line 5, in <module>
    from chainlit.telemetry import trace_event
  File "/home/youssef/Hamza_OK/Chef_Beldi/.venv/lib/python3.12/site-packages/chainlit/telemetry.py", line 12, in <module>
    from chainlit.config import config
  File "/home/youssef/Hamza_OK/Chef_Beldi/.venv/lib/python3.12/site-packages/chainlit/config.py", line 538, in <module>
    config = load_config()
             ^^^^^^^^^^^^^
  File "/home/youssef/Hamza_OK/Chef_Beldi/.venv/lib/python3.12/site-packages/chainlit/config.py", line 507, in load_config
    settings = load_settings()
               ^^^^^^^^^^^^^^^
  File "/home/youssef/Hamza_OK/Chef_Beldi/.venv/lib/python3.12/site-packages/chainlit/config.py", line 479, in load_settings
    code_settings = CodeSettings(action_callbacks={})
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youssef/Hamza_OK/Chef_Beldi/.venv/lib/python3.12/site-packages/pydantic/_internal/_dataclasses.py", line 121, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youssef/Hamza_OK/Chef_Beldi/.venv/lib/python3.12/site-packages/pydantic/_internal/_mock_val_ser.py", line 100, in __getattr__
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: `CodeSettings` is not fully defined; you should define `Action`, then call `pydantic.dataclasses.rebuild_dataclass(CodeSettings)`.

For further information visit https://errors.pydantic.dev/2.10/u/class-not-fully-defined
```

---
## Environment Details:

```bash
(.venv) youssef@hp ~/Hamza_OK/Chef_Beldi  $ pip freeze | grep chainlit
chainlit==1.3.2
(.venv) youssef@hp ~/Hamza_OK/Chef_Beldi  $ pip freeze | grep pydantic
pydantic==2.10.2
pydantic_core==2.27.1
```

Operating System: Ubuntu 24.04
- Python Version: 3.12
- Chainlit Version: 1.3.2
- Pydantic Version: 2.10.2

---
## Suggested Solution  
This issue appears to be caused by compatibility problems between Chainlit 1.3.2 and Pydantic 2.10.2. As a temporary workaround, downgrading Pydantic to version 2.10.1 resolves the issue.  

To apply this fix:  
1. Run the following command to downgrade Pydantic:  
   ```bash
   pip install pydantic==2.10.1
   ```
2. Verify that the `chainlit hello` command now works as expected.
A permanent solution may involve updating Chainlit to ensure compatibility with the latest Pydantic version. Additionally, documenting the specific versions of dependencies required for compatibility would help users avoid similar issues in the future.

**Comment by dokterbob** [comment]
Thanks for the feedback and your detective work!

I would suggest we limit pydantic support to `<2.10.2` from `<3` in pyproject or, alternatively, excluding this version specifically (`!=2.10.2`) and place a link to the related issue there, so we know when we can remove it. https://github.com/pydantic/pydantic/issues/11031

Happy to merge a PR to this extent!

Perhaps pydantic will do us a favour and yank the version instead. :)

**Comment by dokterbob** [comment]
Dup of #1544. I see this is causing a lot of users annoyance, let me roll that PR for you. ;)
