### ISSUE TITLE
SQL Alchemy data layer is not being initialized without storage clients.

### ISSUE THREAD

**Issue by BhuvanGowdaN13** [Chainlit/chainlit#1576]
I'm trying to implement customdatalayer using postgres sql database by not using aws or azure storage clients instead locally.

initialization : cl_data._data_layer = SQLAlchemyDataLayer(conninfo=conninfo)

log: SQLAlchemyDataLayer storage client is not initialized and elements will not be persisted!
2024-12-09 15:55:26 - Your app is available at http://localhost:8000
 
Need help

**Comment by dokterbob** [comment]
Need help? Share your code!

**Comment by BhuvanGowdaN13** [comment]
I have configured the issue and it was solved by importing and defining the below
from chainlit.data.base import BaseStorageClient
cl_data._data_layer = SQLAlchemyDataLayer(conninfo="postgresql+asyncpg://username:password@:5432/postgres",storage_provider=BaseStorageClient)
By the way thanks for replying.

**Comment by efealioksuz** [comment]
BaseStorageClient is used for non-text data persistence like Azure Data Lake, S3, Google Storage, etc. though.
