### ISSUE TITLE
Add drop-down button

### ISSUE THREAD

**Issue by mcai** [Chainlit/chainlit#16]
Sometimes, it’s convenient to click a drop-down button with a list of available options, e.g., click the “generate image” button with the default value (option) set to StableDiffusion 1.5 or the last model the user uses, while the user can also try one of the other models to generate.

**Comment by willydouhard** [comment]
We are planning to add new elements, including different kinds of inputs to typically configure some model parameters. This is probably going to be released in June but I can't commit to a deadline :)

**Comment by jonosooty** [comment]
This is great. I would add another use case into the mix. We want the ability to pre - filter the results from a retriever based on some user defined values. For example, we might constrain the search to a particular product, product range, document type etc. Then we can use the right kind of prompting strategy. Of course this can be done probably in the backend agent and routing and multi-steps but a hint from the user might be much simpler way of deciding what to do.

**Comment by willydouhard** [comment]
Should now be possible with [chat settings](https://docs.chainlit.io/api-reference/chat-settings)!

**Comment by Siddhijain16** [comment]
@willydouhard How we can use dropdown value for conditions like to call different chain on different options ?

**Comment by willydouhard** [comment]
Example [here](https://github.com/Chainlit/cookbook/blob/main/image-gen/app.py#L93). We also added [Chat Profiles](https://docs.chainlit.io/chat-experience/chat-profiles) in the latest release that you might find useful.
