### ISSUE TITLE
Enable to use Chainlit as a Streamlit component

### ISSUE THREAD

**Issue by mcai** [Chainlit/chainlit#17]
I wonder if we can enable the use of Chainlit chatbot UI as a Streamlit component besides the use of a standalone app, so users can leverage their existing knowledge of Streamlit to integrate Chainlit into their Streamlit apps.

**Comment by willydouhard** [comment]
Right now this is not possible. What I could see is people to take parts of the Chainlit UI (which you can find here https://github.com/Chainlit/chainlit/tree/main/src/chainlit/frontend) and use them to build custom Streamlit components.
