### ISSUE TITLE
Saving previous dialogs

### ISSUE THREAD

**Issue by alifanov** [Chainlit/chainlit#174]
It seems that chainlit can only work with single session.
Is it possible to make support of dialogs (like in ChatGPT, Bard and so on on the left side)?

**Comment by willydouhard** [comment]
If you are looking to persist dialogs to browse them at a later time you can take a look at [data persistence](https://docs.chainlit.io/cloud/persistence/introduction).

If you are looking to "resume" a dialog at any time (meaning continue the conversation), this feature is not yet available.
