### ISSUE TITLE
Enable removing or clearing the history of last messages

### ISSUE THREAD

**Issue by mcai** [Chainlit/chainlit#18]
It will be convenient if we can add some buttons to enable users either remove specific message or clear the whole history of last messages besides the input box.

<img width="409" alt="Screenshot 2023-05-31 at 14 44 32" src="https://github.com/Chainlit/chainlit/assets/354163/700dd42e-c17c-4612-9824-a144d62f86f9">

**Comment by willydouhard** [comment]
I agree. While this gets implemented, you can try to clear your local storage. It will wipe the whole history.

This will only work if you are not using a cloud project. In that case the history is saved in a DB.
