### ISSUE TITLE
Upload File button in front-end UI, just like OpenAI code interpretor

### ISSUE THREAD

**Issue by gxagxagxa** [Chainlit/chainlit#198]
Inspired by OpenAI code interpreter, I wanna implement my own version, which allow user directly upload some files.

By reading the docs, Chainlit has a `AskFileMessage` for users to upload files. 
However, It's need User input some command text to activate server send `AskFileMessage`，and it's not quite intuitive.

If it's possible to add a upload file button in front-end UI, and also a `@cl.on_file_uploaded_callback` decorator. (kind of like Chainlit Actions)
![企业微信截图_16898557031759](https://github.com/Chainlit/chainlit/assets/12197510/b39f8d7c-182f-4cad-b763-6273b5218f1d)

**Comment by willydouhard** [comment]
Yes, this is an opened issue. We are open to contributions to speed up the release, otherwise it will probably be added in august.

**Comment by gxagxagxa** [comment]
Sounds great! Can't wait for the new release!

**Comment by willydouhard** [comment]
#304
