### ISSUE TITLE
Module 'chainlit' has no attribute 'langchain_factory'

### ISSUE THREAD

**Issue by adarshxs** [Chainlit/chainlit#202]
I'm trying to integrate langchain with chainlit while running a local text generation inference server from hugging face.

I get the `Module 'chainlit' has no attribute 'langchain_factory'` error for some reason when I run:

```
@cl.langchain_factory(use_async=True)
def main():
    llm = llm
    chain = LLMChain(llm=llm, prompt=PromptTemplate.from_template(prompt_template))
    return chain
```

**Comment by MathiasSpanhove** [comment]
`langchain_factory` has been removed in the last chainlit version.
You can find the migration guide here: https://docs.chainlit.io/guides/migration/0.6.0#langchain-factory-migration-example

**Comment by adarshxs** [comment]
Got it thanks!
