### ISSUE TITLE
Add function message in Prompt playground

### ISSUE THREAD

**Issue by JacobDu** [Chainlit/chainlit#207]
Prompt playground is very helpful for adjusting prompts and understanding the execution process of the agent. 👍

I am using the `OPENAI_FUNCTIONS` agent type  from `Langchain` to make calls to the execution tools, but in the playground, I can only see messages from SYSTEM, AI, and USER, and cannot view any FUNCTION messages. 

Is it possible to add the display of function messages in the playground?

**Comment by willydouhard** [comment]
We are planning to vastly improve the prompt playground in the future. Would love to have a chat to get your feedback. Can you ping me on discord?
