### ISSUE TITLE
Extend user feedback with more than thumbs

### ISSUE THREAD

**Issue by Anindyadeep** [Chainlit/chainlit#214]
This is very much important while LLMs are deployed in production. Providing an up/down vote button is an awesome way to support telemetry and study app usage by users and potential areas where LLMs are failing. 

Here are some screenshots
![image](https://github.com/Chainlit/chainlit/assets/58508471/77526275-f1ea-4bb1-960e-45477cee2c10)

In the above image, I asked a simple question to chatGPT.

Now when I pressed the downvote button it provides me a form like this

![image](https://github.com/Chainlit/chainlit/assets/58508471/170869d0-adc8-4ba5-a1c0-27e08b1ee5c8)

Another screenshot provides an alternative LLM response based on direct feedback and also provides a summary of what will be going to the backend for feedback.

![image](https://github.com/Chainlit/chainlit/assets/58508471/025cdc62-2ff2-41dc-b5f5-28663b773476)

Implementing this feature will help developers to test LLMs on the grounds where user is providing potential negative feedback.

**Comment by willydouhard** [comment]
I think [this](https://docs.chainlit.io/cloud/persistence/introduction) is what you are looking for.

**Comment by Anindyadeep** [comment]
> I think [this](https://docs.chainlit.io/cloud/persistence/introduction) is what you are looking for.

Yeah I saw that one, but can it be extended to mimic the behavior of how chatgpt does like why the feedback was negative and what you were looking for

**Comment by willydouhard** [comment]
Not yet, but this is a good feature request! Will add that soon.

**Comment by Anindyadeep** [comment]
Awesome👍

**Comment by willydouhard** [comment]
#304
