### ISSUE TITLE
Return clickable link in response Message

### ISSUE THREAD

**Issue by vumichien** [Chainlit/chainlit#216]
Can I include a link file in the response message? I have saved the data path and page in the metadata, and I would like the user to be able to access the file quickly by clicking on the link. Can I reference the link in a format similar to Markdown for the user to easily click on it?

**Comment by willydouhard** [comment]
You can use markdown like so:

```py
import chainlit as cl


@cl.on_message
async def main(message: str):
    content = "here is a link [google.com](https://google.com)"
    await cl.Message(content=content).send()
```

You can also use [elements](https://docs.chainlit.io/concepts/elements) if you want the links to open elements in a side bar or new page.

**Comment by vumichien** [comment]
Thank you @willydouhard
