### ISSUE TITLE
Azure OpenAI support

### ISSUE THREAD

**Issue by hooman-bayer** [Chainlit/chainlit#22]
hi again and thanks again for chainlit! 🥳 

Beside OpenAI, a lot of people like me, use Azure OpenAI API (Please see [`langchain docs`](https://python.langchain.com/en/latest/modules/models/chat/integrations/azure_chat_openai.html)). But currently it cant be easily used in `chainlit`.

**Comment by hooman-bayer** [comment]
Nevermind

According to Langchain simply set the following env variables for embedding models:

```
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_BASE"] = "https://<your-endpoint.openai.azure.com/"
os.environ["OPENAI_API_KEY"] = "your AzureOpenAI key"
os.environ["OPENAI_API_VERSION"] = "2023-03-15-preview"
```

and similarly for the `chat_model`.

**Comment by hooman-bayer** [comment]
Reopening this because `prompt playground` is a very useful feature which does not work with Azure OpenAI yet. Any hints how to solve it?

**Comment by willydouhard** [comment]
For a quick local hack you can add hardcode your deployment_id here https://github.com/Chainlit/chainlit/blob/main/src/chainlit/server.py#L91 in your local installation.

For the real fix, we need to enhance the prompt playground to make it more flexible and compatible with more LLMs.

**Comment by tonglei856** [comment]
I write my .env as follow:

```
OPENAI_API_TYPE="azure"
OPENAI_API_KEY="<azure openai key>"
OPENAI_API_BASE="https://<azure colleciton>.openai.azure.com/"
OPENAI_API_VERSION="2023-07-01-preview"
```
then it' work
