### ISSUE TITLE
Example code not working 

### ISSUE THREAD

**Issue by rafaeldelrey** [Chainlit/chainlit#222]
At the 0.6 migration guide, as well as in the langchain integration example code at [https://docs.chainlit.io/integrations/langchain](https://docs.chainlit.io/integrations/langchain), it is written:
`await cl.Message(content=res["text"]).send()`

I believe it should be "answer", instead of "text".  At least, this is the case for the return from ConversationalRetrievalChain

**Comment by willydouhard** [comment]
Depending on the type of the chain, the output key might differ.
