### ISSUE TITLE
Suggest the next question for user

### ISSUE THREAD

**Issue by vumichien** [Chainlit/chainlit#223]
Is it possible for me to generate suggested questions as Bing search does?
![image](https://github.com/Chainlit/chainlit/assets/31467068/cd146434-5685-4464-829f-d9f138efc95c)
The assistant will provide the user with suggested questions to choose from and use as input for their next question.

**Comment by willydouhard** [comment]
The generation would be up to you in your python code. To display them in the UI, you can use [actions](https://docs.chainlit.io/concepts/actions)
