### ISSUE TITLE
Unable to add image to chainlit.md readme

### ISSUE THREAD

**Issue by antoan** [Chainlit/chainlit#228]
For some reason I'm unable to render an image at the root of my app that I've added to an otherwise blank chainlit.md document with:
`
![](doomed_chicken.jpg)`

Is this to be expected?

Cheers

**Comment by willydouhard** [comment]
Hello, for security reasons public files have to be served in the `public` directory. So your readme should be `![](public/doomed_chicken.jpg)` and you should move the image as well.

**Comment by antoan** [comment]
Thank you, much appreciated.
