### ISSUE TITLE
findLastIndex error when loading hello in Firefox

### ISSUE THREAD

**Issue by piacentini** [Chainlit/chainlit#230]
findLastIndex is not a standard JS function, so Firefox can not load a Chainlit app. 
Attached is a screenshot, just run

chainlit hello

And open localhost:8000 in Firefox.
![Screenshot_20230726_164432](https://github.com/Chainlit/chainlit/assets/1039234/831c256c-b79a-4bf4-987b-bcd1c24b3313)

**Comment by alimtunc** [comment]
Hi, it has been fixed recently and will be on the next release.
