### ISSUE TITLE
Session is disconnected

### ISSUE THREAD

**Issue by FawenYo** [Chainlit/chainlit#237]
Hi, I have using Chainlit to build my LangChain app, and all things work on my local device
But when I tried to deploy it on the DigitalOcean App Platform using Docker image, the site will show the error `Could not reach the server.` and crashed with the error message `KeyError: 'Session is disconnected'`

Can this be fixed?

**Comment by ramnes** [comment]
Hey @FawenYo, can you provide a reproducible example?

**Comment by GianfrancoCorrea** [comment]
im having the same error when openai takes to long to answer

**Comment by willydouhard** [comment]
This is caused by synchronous long running actions. Ideally, long running functions should be async and awaited. If that's not possible, you can wrap your function with [cl.make_async](https://docs.chainlit.io/api-reference/make-async) to run it in a separate thread. This will fix your issue.
