### ISSUE TITLE
upload multiply documents

### ISSUE THREAD

**Issue by heweapon** [Chainlit/chainlit#238]
At present, it seems that only one PDF can be uploaded for processing. When will you be able to upload multiple documents?Thank you.

**Comment by willydouhard** [comment]
You can ask for multiple files at once, example [here](https://docs.chainlit.io/api-reference/ask/ask-for-file).

**Comment by heweapon** [comment]
> You can ask for multiple files at once, example [here](https://docs.chainlit.io/api-reference/ask/ask-for-file).

OK.Thank you!
