### ISSUE TITLE
Author rename

### ISSUE THREAD

**Issue by vumichien** [Chainlit/chainlit#240]
I'm encountering an issue with author_rename. It seems to only be able to rename the chatbot for response messages, but not for the initial message where the default name is still being displayed. Any suggestions on how to resolve this?
![image](https://github.com/Chainlit/chainlit/assets/31467068/13ef3557-755d-4650-9678-10f1a56c8448)

**Comment by willydouhard** [comment]
By initial message you mean the user message or the first chatbot message?

Can you provide a minimal code snippet so I can reproduce ?

**Comment by vumichien** [comment]
I mean the first chatbot message. This is a minimal snippet
```python
@cl.author_rename
def rename(orig_author: str):
    rename_dict = {"Chatbot": "Assistant"}
    return rename_dict.get(orig_author, orig_author)


@cl.on_chat_start
async def init():
     # load DB
     # load model
     cl.user_session.set("chain", chain)
    await cl.AskUserMessage(content="こんにちは！私はデトモのチャットボットです🤖。何かお手伝いいたしましょうか。 ", timeout=20).send()

@cl.on_message
async def main(message: str):
    # Retrieve the chain from the user session
    chain = cl.user_session.get("chain")
   # Logic to response
```

**Comment by willydouhard** [comment]
Nice catch, here is the fix https://github.com/Chainlit/chainlit/pull/242

**Comment by vumichien** [comment]
Thank you for promptly resolving the issue.
