### ISSUE TITLE
Run JS code on FE thats is comming from the BE

### ISSUE THREAD

**Issue by raonigabriel** [Chainlit/chainlit#241]
Feature request / idea:
Create some sort of "SystemMessage" that is (if needed) not shown to the user in the FE but to silently execute a custom piece of JS code then return the results the server. That might require setting up separate (multiplexed) channels eg, DefaultMessageChannel and SystemMessageChannel.
A variant of this is to run JS code but with a text message.

Example:
BE -> pushes a SystemMessage("js code  here") -> FE runs / evals the JS code -> FE returns the reply to the BE
Request:
{
"messageType" : "SYSTEM"
"requestId": "b6955e31-bc31-43fd-a662-dcb19fab8c87"
"text": "",
"code": "Intl.DateTimeFormat().resolvedOptions().timeZone"
}

Response:
{
"messageType" : "SYSTEM"
"requestId": "b6955e31-bc31-43fd-a662-dcb19fab8c87",
"result": "Asia/Calcuta"
}

Use cases:
* To grab the users timezone (Intl.DateTimeFormat().resolvedOptions().timeZone)
* To grab the users Location (GeoLocation API)
* To ask the user for custom permissions (MIc, Camera)

**Comment by sebderhy** [comment]
I'm having the same issue, because I want to integrate Google Analytics (which asks me to put a custom JS code in my code) into my chatbots.
