### ISSUE TITLE
broken image link in agent responses

### ISSUE THREAD

**Issue by urbanscribe** [Chainlit/chainlit#249]
having trouble gettin images to display in chainlit from a simple agent call  response

EXAMPLE AGENT RESPONSE
```
[I have generated an image of a lion for you. Here it is:
![lion](sandbox:/images/new_image_image-0_2937c3b9-5eb6-4808-9dc5-903ac1b8fd83.png)
Let me know if there's anything else I can help with!]
```
here lion is the prompt
and second is the path
since agent generated dont have much control over it.

when displayed in chainlit front end using 
    await cl.Message(content=res, elements=elements, actions=actions).send()
where res is the reponse and the element is the image (that is retrieved directly from a image_path, not from res)

I get the response with the 
`[![lion](sandbox:/images/new_image_image-0_2937c3b9-5eb6-4808-9dc5-903ac1b8fd83.png)]
`
as a broken image link between two lines of text

I tried to see if there a method that can handle sandbox, tried stripping sandbox out from the response before passing to cl.Message and a bunch of other ideas but just cannot get the res element as is above to display in cl.Message without a broken link.

this agent generated message response has a structure 
- what I did 
- here it is
- do you need more help 

and I have to get the text from the response from res
and the image I can only get from a 
`    image_path = cl.user_session.get("image_path")`
where the image generator function  set it as
`    cl.user_session.set("image_path", image_path)`

any thoughts on how to get response
```
[I have generated an image of a lion for you. Here it is:
![lion](sandbox:/images/new_image_image-0_2937c3b9-5eb6-4808-9dc5-903ac1b8fd83.png)
Let me know if there's anything else I can help with!]
```
to show the image in chainlit?

could I translate the sandbox (to relative, stripped out) path somehow?

**Comment by urbanscribe** [comment]
any chance you guys can give me a little guidance on this.  I've tried a number of workaround but how do you suggested I get the agent finished chain and have chainlit display the image 

here is another example

`> Entering new AgentExecutor chain...
Action:
```
{
  "action": "image_generate",
  "action_input": {
    "prompt": "A beautiful sunset over the ocean"
  }
}
```Calling generate_image function...

 GEN: Generating image...
GEN: Sending request to API...
GEN: apiurl: http://192.168.2.80:7860/sdapi/v1/txt2img


GEN: Image create PAYLOAD: {'prompt': 'A beautiful sunset over the ocean', 'steps': 25, 'seed': -1, 'cfg_scale': 8.0, 'width': 640, 'height': 512, 'samples': 1, 'sampler': 'k_euler'}


GEN: Parsing the response...
GEN: attributes of r: ['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']
GEN: Creating 'images' directory if not exist...
GEN: Looping through the images...
GEN: Processing image 0...
GEN: Assuming the entire string is the Base64-encoded image for image 0
GEN: type of image_data: <class 'bytes'>
GEN: type of image: <class 'PIL.PngImagePlugin.PngImageFile'>
GEN: Image object after opening: <PIL.PngImagePlugin.PngImageFile image mode=RGB size=640x512 at 0x7FE0D0097850>
GEN: Retrieved image object from session: <PIL.PngImagePlugin.PngImageFile image mode=RGB size=640x512 at 0x7FE0D0097850>
SAVE: Saved image: images/new_image_image-0_cde2d253-00d2-40c8-9631-a3324a5fe4d8.png
filename 2:new_image_image-0_cde2d253-00d2-40c8-9631-a3324a5fe4d8.png

Observation: Here is images/new_image_image-0_cde2d253-00d2-40c8-9631-a3324a5fe4d8.png.
Thought:I generated an image of a beautiful sunset over the ocean. Here it is:

![sunset over the ocean](sandbox:/images/new_image_image-0_cde2d253-00d2-40c8-9631-a3324a5fe4d8.png)

Is there anything else I can help you with?


> Finished chain.`

![Screenshot 2023-08-05 at 4 19 11 PM](https://github.com/Chainlit/chainlit/assets/2935311/04d0b7ed-abd1-46d5-b2e3-bba844a56789)

**Comment by urbanscribe** [comment]
![Screenshot 2023-08-05 at 4 19 11 PM](https://github.com/Chainlit/chainlit/assets/2935311/ef411380-dbfd-4e0b-b1ac-3fd6945aa25b)

**Comment by urbanscribe** [comment]
gents

it seems that server.py is not setup to let the browser get access to a custom folder and redirects non root links.

for my purpose if I add a fastapi route to server.py to let the browser access the images instead of redirecting
app.mount("/images", StaticFiles(directory="images", check_dir=False), name="images")

then I can see my images

not sure how you would want to let chainlit allow access to non route addresses

**Comment by willydouhard** [comment]
Hey, you can serve your images from a directory named `public`. This is not documented yet but it's the correct way to do it.
