### ISSUE TITLE
Could not reach the server

### ISSUE THREAD

**Issue by AIAnytime** [Chainlit/chainlit#274]
Why do I am getting "Could not reach the server"?

**Comment by willydouhard** [comment]
It means that the UI can't connect to the server, either the server crashed or is not started.

**Comment by willydouhard** [comment]
Are you running local llms?

**Comment by nysagarg** [comment]
im getting the same issue

**Comment by Skisquaw** [comment]
I worked on this more last night. It appears to be something timing out in the chainlit app. When I switched the llm inference to gpt-3.5-turbo (a few secs response time), it worked fine. My local LLM takes like 5 mins to respond and the message "Could not reach the server" appears while waiting. My python code is using async def function with await which has no timeout

**Comment by willydouhard** [comment]
Yes we might hit a default timeout here. Will investigate

**Comment by AnirudhKabra** [comment]
> im getting the same issue. Yes I am running local llm

I am also getting same issue

**Comment by willydouhard** [comment]
Also are you calling your local llm in a synchronous way? If so that would explain the issue. If you are blocking the event loop for 5 minutes the client would think that the server is dead.

you could use cl.make_async to make that long running call in a separate thread.

**Comment by bsurya27** [comment]
Even I am having the same issue. I am running a LLM locally and I get this error message after I give a prompt. It takes around 2-5 mins  before it can connect to the server. How do I resolve this?

**Comment by willydouhard** [comment]
Are you using a LLM that runs locally? Would need more context to help

**Comment by bsurya27** [comment]
Yes, I am using a LLM that runs locally, I've already mentioned that. Any other details you need to know?

**Comment by willydouhard** [comment]
Would be helpful how you "load" your llm in the python process

**Comment by bsurya27** [comment]
I am using ggml llama -2 via Ctransformers. I am using llamachain to run them together

**Comment by willydouhard** [comment]
Can I see your Chainlit code? Are you instantiating the LLM un `on_chat_start` or at the beginning of your app file?

**Comment by AnirudhKabra** [comment]
import os

import chainlit as cl
from dotenv import load_dotenv
from langchain.chains import RetrievalQA
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.llms import CTransformers
from langchain.prompts import PromptTemplate
from langchain.vectorstores import FAISS

# Load environment variables from .env file
load_dotenv()

HUGGINGFACEHUB_API_TOKEN = os.getenv("HUGGINGFACEHUB_API_TOKEN")

DB_FAISS_PATH = "./../vectorstore/db_faiss"
MODEL_PATH = "./../model/llama-2-7b-chat.ggmlv3.q8_0.bin"


prompt_template = """Use the following pieces of context to answer the users question.
If you don't know the answer, just say that you don't know, don't try to make up an answer.
ALWAYS return a "SOURCES" part in your answer.
The "SOURCES" part should be a reference to the source of the document from which you got your answer.
Example of your response should be as follows:

Context: {context}
Question: {question}

Only return the helpful answer below and nothing else.
Helpful answer:
"""


def set_custom_prompt():
    """
    Prompt template for QA retrieval for each vectorstore
    """
    prompt = PromptTemplate(
        template=prompt_template, input_variables=["context", "question"]
    )
    return prompt


def create_retrieval_qa_chain(llm, prompt, db):
    """
    Creates a Retrieval Question-Answering (QA) chain using a given language model, prompt, and database.

    This function initializes a RetrievalQA object with a specific chain type and configurations,
    and returns this QA chain. The retriever is set up to return the top 3 results (k=3).

    Args:
        llm (any): The language model to be used in the RetrievalQA.
        prompt (str): The prompt to be used in the chain type.
        db (any): The database to be used as the retriever.

    Returns:
        RetrievalQA: The initialized QA chain.
    """
    qa_chain = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=db.as_retriever(search_kwargs={"k": 3}),
        return_source_documents=True,
        chain_type_kwargs={"prompt": prompt},
    )
    return qa_chain


def load_model(
    model_path=MODEL_PATH,
    model_type="llama",
    max_new_tokens=512,
    temperature=0.7,
):
    """
    Load a locally downloaded model.

    Parameters:
        model_path (str): The path to the model to be loaded.
        model_type (str): The type of the model.
        max_new_tokens (int): The maximum number of new tokens for the model.
        temperature (float): The temperature parameter for the model.

    Returns:
        CTransformers: The loaded model.

    Raises:
        FileNotFoundError: If the model file does not exist.
        SomeOtherException: If the model file is corrupt.
    """
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"No model file found at {model_path}")

    # Additional error handling could be added here for corrupt files, etc.

    llm = CTransformers(
        model=model_path,
        model_type=model_type,
        max_new_tokens=max_new_tokens,  # type: ignore
        temperature=temperature,  # type: ignore
    )

    return llm


def create_retrieval_qa_bot(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    persist_dir=DB_FAISS_PATH,
    device="cpu",
):
    """
    This function creates a retrieval-based question-answering bot.

    Parameters:
        model_name (str): The name of the model to be used for embeddings.
        persist_dir (str): The directory to persist the database.
        device (str): The device to run the model on (e.g., 'cpu', 'cuda').

    Returns:
        RetrievalQA: The retrieval-based question-answering bot.

    Raises:
        FileNotFoundError: If the persist directory does not exist.
        SomeOtherException: If there is an issue with loading the embeddings or the model.
    """

    if not os.path.exists(persist_dir):
        raise FileNotFoundError(f"No directory found at {persist_dir}")

    try:
        embeddings = HuggingFaceEmbeddings(
            model_name=model_name,
            model_kwargs={"device": device},
        )
    except Exception as e:
        raise Exception(
            f"Failed to load embeddings with model name {model_name}: {str(e)}"
        )

    db = FAISS.load_local(folder_path=DB_FAISS_PATH, embeddings=embeddings)

    try:
        llm = load_model()  # Assuming this function exists and works as expected
    except Exception as e:
        raise Exception(f"Failed to load model: {str(e)}")

    qa_prompt = (
        set_custom_prompt()
    )  # Assuming this function exists and works as expected

    try:
        qa = create_retrieval_qa_chain(
            llm=llm, prompt=qa_prompt, db=db
        )  # Assuming this function exists and works as expected
    except Exception as e:
        raise Exception(f"Failed to create retrieval QA chain: {str(e)}")

    return qa


def retrieve_bot_answer(query):
    """
    Retrieves the answer to a given query using a QA bot.

    This function creates an instance of a QA bot, passes the query to it,
    and returns the bot's response.

    Args:
        query (str): The question to be answered by the QA bot.

    Returns:
        dict: The QA bot's response, typically a dictionary with response details.
    """
    qa_bot_instance = create_retrieval_qa_bot()
    bot_response = qa_bot_instance({"query": query})
    return bot_response


@cl.on_chat_start
async def initialize_bot():
    """
    Initializes the bot when a new chat starts.

    This asynchronous function creates a new instance of the retrieval QA bot,
    sends a welcome message, and stores the bot instance in the user's session.
    """
    qa_chain = create_retrieval_qa_bot()
    welcome_message = cl.Message(content="Starting the bot...")
    await welcome_message.send()
    welcome_message.content = (
        "Hi, Welcome to Chat With Documents using Llama2 and LangChain."
    )
    await welcome_message.update()

    cl.user_session.set("chain", qa_chain)


@cl.on_message
async def process_chat_message(message):
    """
    Processes incoming chat messages.

    This asynchronous function retrieves the QA bot instance from the user's session,
    sets up a callback handler for the bot's response, and executes the bot's
    call method with the given message and callback. The bot's answer and source
    documents are then extracted from the response.
    """
    qa_chain = cl.user_session.get("chain")
    callback_handler = cl.AsyncLangchainCallbackHandler(
        stream_final_answer=True, answer_prefix_tokens=["FINAL", "ANSWER"]
    )
    callback_handler.answer_reached = True
    response = await qa_chain.acall(message, callbacks=[callback_handler])
    bot_answer = response["result"]
    source_documents = response["source_documents"]

    if source_documents:
        bot_answer += f"\nSources:" + str(source_documents)
    else:
        bot_answer += "\nNo sources found"

    await cl.Message(content=bot_answer).send()

**Comment by AnirudhKabra** [comment]
"""
import os

import chainlit as cl
from dotenv import load_dotenv
from langchain.chains import RetrievalQA
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.llms import CTransformers
from langchain.prompts import PromptTemplate
from langchain.vectorstores import FAISS

# Load environment variables from .env file
load_dotenv()

HUGGINGFACEHUB_API_TOKEN = os.getenv("HUGGINGFACEHUB_API_TOKEN")

DB_FAISS_PATH = "./../vectorstore/db_faiss"
MODEL_PATH = "./../model/llama-2-7b-chat.ggmlv3.q8_0.bin"


prompt_template = """Use the following pieces of context to answer the users question.
If you don't know the answer, just say that you don't know, don't try to make up an answer.
ALWAYS return a "SOURCES" part in your answer.
The "SOURCES" part should be a reference to the source of the document from which you got your answer.
Example of your response should be as follows:

Context: {context}
Question: {question}

Only return the helpful answer below and nothing else.
Helpful answer:
"""


def set_custom_prompt():
    """
    Prompt template for QA retrieval for each vectorstore
    """
    prompt = PromptTemplate(
        template=prompt_template, input_variables=["context", "question"]
    )
    return prompt


def create_retrieval_qa_chain(llm, prompt, db):
    """
    Creates a Retrieval Question-Answering (QA) chain using a given language model, prompt, and database.

    This function initializes a RetrievalQA object with a specific chain type and configurations,
    and returns this QA chain. The retriever is set up to return the top 3 results (k=3).

    Args:
        llm (any): The language model to be used in the RetrievalQA.
        prompt (str): The prompt to be used in the chain type.
        db (any): The database to be used as the retriever.

    Returns:
        RetrievalQA: The initialized QA chain.
    """
    qa_chain = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=db.as_retriever(search_kwargs={"k": 3}),
        return_source_documents=True,
        chain_type_kwargs={"prompt": prompt},
    )
    return qa_chain


def load_model(
    model_path=MODEL_PATH,
    model_type="llama",
    max_new_tokens=512,
    temperature=0.7,
):
    """
    Load a locally downloaded model.

    Parameters:
        model_path (str): The path to the model to be loaded.
        model_type (str): The type of the model.
        max_new_tokens (int): The maximum number of new tokens for the model.
        temperature (float): The temperature parameter for the model.

    Returns:
        CTransformers: The loaded model.

    Raises:
        FileNotFoundError: If the model file does not exist.
        SomeOtherException: If the model file is corrupt.
    """
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"No model file found at {model_path}")

    # Additional error handling could be added here for corrupt files, etc.

    llm = CTransformers(
        model=model_path,
        model_type=model_type,
        max_new_tokens=max_new_tokens,  # type: ignore
        temperature=temperature,  # type: ignore
    )

    return llm


def create_retrieval_qa_bot(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    persist_dir=DB_FAISS_PATH,
    device="cpu",
):
    """
    This function creates a retrieval-based question-answering bot.

    Parameters:
        model_name (str): The name of the model to be used for embeddings.
        persist_dir (str): The directory to persist the database.
        device (str): The device to run the model on (e.g., 'cpu', 'cuda').

    Returns:
        RetrievalQA: The retrieval-based question-answering bot.

    Raises:
        FileNotFoundError: If the persist directory does not exist.
        SomeOtherException: If there is an issue with loading the embeddings or the model.
    """

    if not os.path.exists(persist_dir):
        raise FileNotFoundError(f"No directory found at {persist_dir}")

    try:
        embeddings = HuggingFaceEmbeddings(
            model_name=model_name,
            model_kwargs={"device": device},
        )
    except Exception as e:
        raise Exception(
            f"Failed to load embeddings with model name {model_name}: {str(e)}"
        )

    db = FAISS.load_local(folder_path=DB_FAISS_PATH, embeddings=embeddings)

    try:
        llm = load_model()  # Assuming this function exists and works as expected
    except Exception as e:
        raise Exception(f"Failed to load model: {str(e)}")

    qa_prompt = (
        set_custom_prompt()
    )  # Assuming this function exists and works as expected

    try:
        qa = create_retrieval_qa_chain(
            llm=llm, prompt=qa_prompt, db=db
        )  # Assuming this function exists and works as expected
    except Exception as e:
        raise Exception(f"Failed to create retrieval QA chain: {str(e)}")

    return qa


def retrieve_bot_answer(query):
    """
    Retrieves the answer to a given query using a QA bot.

    This function creates an instance of a QA bot, passes the query to it,
    and returns the bot's response.

    Args:
        query (str): The question to be answered by the QA bot.

    Returns:
        dict: The QA bot's response, typically a dictionary with response details.
    """
    qa_bot_instance = create_retrieval_qa_bot()
    bot_response = qa_bot_instance({"query": query})
    return bot_response


@cl.on_chat_start
async def initialize_bot():
    """
    Initializes the bot when a new chat starts.

    This asynchronous function creates a new instance of the retrieval QA bot,
    sends a welcome message, and stores the bot instance in the user's session.
    """
    qa_chain = create_retrieval_qa_bot()
    welcome_message = cl.Message(content="Starting the bot...")
    await welcome_message.send()
    welcome_message.content = (
        "Hi, Welcome to Chat With Documents using Llama2 and LangChain."
    )
    await welcome_message.update()

    cl.user_session.set("chain", qa_chain)


@cl.on_message
async def process_chat_message(message):
    """
    Processes incoming chat messages.

    This asynchronous function retrieves the QA bot instance from the user's session,
    sets up a callback handler for the bot's response, and executes the bot's
    call method with the given message and callback. The bot's answer and source
    documents are then extracted from the response.
    """
    qa_chain = cl.user_session.get("chain")
    callback_handler = cl.AsyncLangchainCallbackHandler(
        stream_final_answer=True, answer_prefix_tokens=["FINAL", "ANSWER"]
    )
    callback_handler.answer_reached = True
    response = await qa_chain.acall(message, callbacks=[callback_handler])
    bot_answer = response["result"]
    source_documents = response["source_documents"]

    if source_documents:
        bot_answer += f"\nSources:" + str(source_documents)
    else:
        bot_answer += "\nNo sources found"

    await cl.Message(content=bot_answer).send()
"""

**Comment by AnirudhKabra** [comment]
import os

import chainlit as cl
from dotenv import load_dotenv
from langchain.chains import RetrievalQA
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.llms import CTransformers
from langchain.prompts import PromptTemplate
from langchain.vectorstores import FAISS

# Load environment variables from .env file
load_dotenv()

HUGGINGFACEHUB_API_TOKEN = os.getenv("HUGGINGFACEHUB_API_TOKEN")

DB_FAISS_PATH = "./../vectorstore/db_faiss"
MODEL_PATH = "./../model/llama-2-7b-chat.ggmlv3.q8_0.bin"


prompt_template = """Use the following pieces of context to answer the users question.
If you don't know the answer, just say that you don't know, don't try to make up an answer.
ALWAYS return a "SOURCES" part in your answer.
The "SOURCES" part should be a reference to the source of the document from which you got your answer.
Example of your response should be as follows:

Context: {context}
Question: {question}

Only return the helpful answer below and nothing else.
Helpful answer:
"""


def set_custom_prompt():
    """
    Prompt template for QA retrieval for each vectorstore
    """
    prompt = PromptTemplate(
        template=prompt_template, input_variables=["context", "question"]
    )
    return prompt


def create_retrieval_qa_chain(llm, prompt, db):
    
    qa_chain = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=db.as_retriever(search_kwargs={"k": 3}),
        return_source_documents=True,
        chain_type_kwargs={"prompt": prompt},
    )
    return qa_chain


def load_model(
    model_path=MODEL_PATH,
    model_type="llama",
    max_new_tokens=512,
    temperature=0.7,
):
   
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"No model file found at {model_path}")

    # Additional error handling could be added here for corrupt files, etc.

    llm = CTransformers(
        model=model_path,
        model_type=model_type,
        max_new_tokens=max_new_tokens,  # type: ignore
        temperature=temperature,  # type: ignore
    )

    return llm


def create_retrieval_qa_bot(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    persist_dir=DB_FAISS_PATH,
    device="cpu",
):
    

    if not os.path.exists(persist_dir):
        raise FileNotFoundError(f"No directory found at {persist_dir}")

    try:
        embeddings = HuggingFaceEmbeddings(
            model_name=model_name,
            model_kwargs={"device": device},
        )
    except Exception as e:
        raise Exception(
            f"Failed to load embeddings with model name {model_name}: {str(e)}"
        )

    db = FAISS.load_local(folder_path=DB_FAISS_PATH, embeddings=embeddings)

    try:
        llm = load_model()  # Assuming this function exists and works as expected
    except Exception as e:
        raise Exception(f"Failed to load model: {str(e)}")

    qa_prompt = (
        set_custom_prompt()
    )  # Assuming this function exists and works as expected

    try:
        qa = create_retrieval_qa_chain(
            llm=llm, prompt=qa_prompt, db=db
        )  # Assuming this function exists and works as expected
    except Exception as e:
        raise Exception(f"Failed to create retrieval QA chain: {str(e)}")

    return qa


def retrieve_bot_answer(query):
    
    qa_bot_instance = create_retrieval_qa_bot()
    bot_response = qa_bot_instance({"query": query})
    return bot_response


@cl.on_chat_start
async def initialize_bot():
   
    qa_chain = create_retrieval_qa_bot()
    welcome_message = cl.Message(content="Starting the bot...")
    await welcome_message.send()
    welcome_message.content = (
        "Hi, Welcome to Chat With Documents using Llama2 and LangChain."
    )
    await welcome_message.update()

    cl.user_session.set("chain", qa_chain)


@cl.on_message
async def process_chat_message(message):
    
    qa_chain = cl.user_session.get("chain")
    callback_handler = cl.AsyncLangchainCallbackHandler(
        stream_final_answer=True, answer_prefix_tokens=["FINAL", "ANSWER"]
    )
    callback_handler.answer_reached = True
    response = await qa_chain.acall(message, callbacks=[callback_handler])
    bot_answer = response["result"]
    source_documents = response["source_documents"]

    if source_documents:
        bot_answer += f"\nSources:" + str(source_documents)
    else:
        bot_answer += "\nNo sources found"

    await cl.Message(content=bot_answer).send()

**Comment by willydouhard** [comment]
If i understand correctly you are trying to run llama 2 7B on CPU? If that's the case I think the token per second throughput is going to be extremely slow, with or without chainlit.

**Comment by Skisquaw** [comment]
There seems to a timeout right around 30 seconds where I get a response back from chatgpt and then call await cl.Message(content=answer).send() and no data shows up on the UI (since OpenAI has lags, one took 44.24 seconds and the send did not show up in the UI. i typed in the same question and it took 21.75 seconds and the send did show up in the UI

**Comment by Skisquaw** [comment]
Is there some default timeout setting I'm missing that is automatically set to 30 seconds?

**Comment by willydouhard** [comment]
I don't think so. "Could not reach the server" always happen because the event loop of the server is stuck. This is often caused by a long running synchronous task on the main thread. The solution is either to run async tasks or to wrap the task in [make_async](https://docs.chainlit.io/api-reference/make-async).

**Comment by Skisquaw** [comment]
There is seems to be some default timeout of 30 secs (or my code is wrong). This is a snippet of my code. If the chat completion takes more than 30 secs, then the send is ignored and nothing appears on the chainlit screen. I was running tests, and 32.57 seconds was the closest one that failed to send. Anything under 30 secs was fine. The chat completion is definitely returning data. Note that there is no "Could not reach the server" message. The chainlit screen is still working and I can type the request again.

In my @cl.on_message
async def main(message):
print("Sending ",user_message)
            start_time = time.time()
            res = openai.ChatCompletion.create(
                model=model_name,
                messages=[
                    {"role": "user", "content": user_message}
                ]
            )
            end_time = time.time()
            elapsed_time = end_time - start_time
            print(f"The function took {elapsed_time:.2f} seconds to execute.")
answer = res['choices'][0]['message']['content']
await cl.Message(content=answer).send()

**Comment by willydouhard** [comment]
the problem is that you use the sync implem of openai.ChatCompletion on the main thread. Two solutions here, run this function in a different thread (with cl.make_async) or use the async implementation (example [here](https://github.com/Chainlit/chainlit/blob/main/src/chainlit/playground/providers/openai.py#L123)).

**Comment by Skisquaw** [comment]
That fixed it, thank you Willy! I even get the nice "Running..." spinning animation.

**Comment by jerem64** [comment]
> The problem is that you use the sync implem of openai.ChatCompletion on the main thread. Two solutions here, run this function in a different thread (with cl.make_async) or use the async implementation (example [here](https://github.com/Chainlit/chainlit/blob/main/src/chainlit/playground/providers/openai.py#L123)).

The link is dead 😭

**Comment by cigotete** [comment]
> The problem is that you use the sync implem of openai.ChatCompletion on the main thread. Two solutions here, run this function in a different thread (with cl.make_async) or use the async implementation (example [here](https://github.com/Chainlit/chainlit/blob/main/src/chainlit/playground/providers/openai.py#L123)).

I am having the same issues, if the prompt takes more than 30 seconds, there is no output. In my humble opinion, the cause can not be only explained with sync implementation of openai completion. In my opinion, the cause could be related with Chainlit and how is supporting queries that take more than 30 seconds. Please let me know if I am wrong.

**Comment by cigotete** [comment]
> > The problem is that you use the sync implem of openai.ChatCompletion on the main thread. Two solutions here, run this function in a different thread (with cl.make_async) or use the async implementation (example [here](https://github.com/Chainlit/chainlit/blob/main/src/chainlit/playground/providers/openai.py#L123)).
> 
> The link is dead 😭

Hello, I think the link is [this](https://github.com/Chainlit/chainlit/blob/3179d2928a4bafbc2d6e46b220ad44072753082c/backend/chainlit/playground/providers/openai.py#L122C15-L122C32) now.

I confirm the issue about 30 seconds. About the issue, I am not sure what is the reason of this 30 seconds limit. I think that, in the short term, processes that exceed that time window will be more common (I have processes with gpt4 that take about a minute or more).

In my case, the issue was surpassed with the cl.make_async @willydouhard allusion. Following the documentation is more clear about how to implement the change https://docs.chainlit.io/api-reference/make-async, this is the example:
```
import time
import chainlit as cl

def sync_func():
    time.sleep(5)
    return "Hello!"

@cl.on_message
async def main(message: cl.Message):
    answer = await cl.make_async(sync_func)()
    await cl.Message(
        content=answer,
    ).send()

```

**Comment by httplups** [comment]
I am facing the same issue, but I am running all async functions from llama index. The LLM takes a long time to respond due to the amount of documents.

**Comment by chrisputzu** [comment]
> I am facing the same issue, but I am running all async functions from llama index. The LLM takes a long time to respond due to the amount of documents.

I resolved the issue using concurrent.futures, which creates a separate thread to run the task.

Here is a simple code example to run a text_to_speech function that takes a long time to execute. This solution fixed the 'Could not reach the server' error for me:

import asyncio
import concurrent.futures

async def speak_async(answer: str): 
    loop = asyncio.get_running_loop()
    with concurrent.futures.ThreadPoolExecutor() as pool:
        await loop.run_in_executor(pool, text_to_speech, answer)

**Comment by Bachal78** [comment]
uv init --package hello_chainllit 
uv run add 
i have run above commands to make project of chainlit but when I use blow command 
uv run chainlit hello
Its showing this error:
error: Failed to spawn: `chainlit`
  Caused by: Access is denied. (os error 5)
how i can avoid this error as i have tried a lot of
