### ISSUE TITLE
Speed up the building time?

### ISSUE THREAD

**Issue by chenjuneking** [Chainlit/chainlit#276]
Was there any way to speed up the building time? I found it took too much time to build the wheel package, it tooks more than 30 minutes each time.

**Comment by ramnes** [comment]
What build time exactly? How to reproduce the behavior you're mentioning?

**Comment by willydouhard** [comment]
In my understand probably `poetry build`?

**Comment by chenjuneking** [comment]
> In my understand probably `poetry build`?

Yes, it took about 40 minutes to build the package on my laptop(Lenovo R9000K with windows 11, Git-Bash).

**Comment by ramnes** [comment]
Alright, so the workaround is to remove `src/chainlit/frontend/node_modules` before building.

On a typical setup, we have a lot of files in this directory, and Poetry doesn't like this: https://github.com/python-poetry/poetry/issues/7644

We probably should move the frontend somewhere else while still including it in the distribution somehow?

**Comment by chenjuneking** [comment]
I agree to move the frontend out of the scope of poetry, like this:

```txt
- chainlit
  - cypress
  - chainlit
    - chainlit
      - db
      - client
      - __init__.py
      - __main__.py
    - pyproject.toml
    - poetry.lock
  - frontend
    - public
    - src
      - App.tsx
```

What do you think?

**Comment by willydouhard** [comment]
I agree but we would have to add some logic in the build to move the built front end folder in the wheel
