### ISSUE TITLE
Unable to connect to remote host. lynx: Can't access startfile http://localhost:8000

### ISSUE THREAD

**Issue by LiuKay** [Chainlit/chainlit#278]
Hi there,

I'm running chainlit on Ubuntu 22.04.2 LTS, when I start my app with "chainlit run app.py", got the messages and the app is blocking here.
![image](https://github.com/Chainlit/chainlit/assets/21058165/192c5a0f-f144-45ec-b295-ee7af0c84796)

Anyone can help?

**Comment by ramnes** [comment]
I think we just open your default browser, try changing that to something more modern than Lynx (e.g. Chrome / Firefox / etc.)
