### ISSUE TITLE
How to access database from deployed chainlit app on fly io ? 

### ISSUE THREAD

**Issue by VinayChaudhari1996** [Chainlit/chainlit#282]
Hello Team,

I successfully deployed the chainlit app on fly.io cloud provider and it is working fine.

Now on dashboard I am able to see 2 instance one for webapp url and another is postgresdb instance.

on local machine I was able to access chatdb sqllite database programmatically. 

So how I can achieve the same using fly.io on google colab or any other machine ??

Thanks

**Comment by willydouhard** [comment]
So you deployed with the local db mode? If so you would need to ssh to your fly instance and download the sqlite db file. Local db mode was imagined for local development, not remote deployments.

**Comment by VinayChaudhari1996** [comment]
I am not very sure , but please refer to my **config.toml**  where my database is "cloud"

![image](https://github.com/Chainlit/chainlit/assets/42869040/e79ee5da-fca7-4991-8e13-673a0ebccd8d)

**Comment by willydouhard** [comment]
Right now we do not have a clean solution for that. The best way would be to provide API access. In the meantime you can check your chrome console network tab to get the http request the client is making when loading the history page and copy that to pull data.

**Comment by VinayChaudhari1996** [comment]
> Right now we do not have a clean solution for that. The best way would be to provide API access. In the meantime you can check your chrome console network tab to get the http request the client is making when loading the history page and copy that to pull data.

For now It is working for me using Curl request. But looking for some scalable programmatic approach

Thanks @willydouhard

**Comment by willydouhard** [comment]
> > So you deployed with the local db mode? If so you would need to ssh to your fly instance and download the sqlite db file. Local db mode was imagined for local development, not remote deployments.
> 
> @willydouhard, thanks so much for your prompt reply in both Discord and here. I tried local db mode with a Supabase Url in prisma schema. It actually works.
> 
> I commented out # os.environ[ # "LOCAL_DB_PATH" # ] = f"file:{local_db_path}?socket_timeout=10&connection_limit=1"
> 
> in config.py then set this directly in .env with my Supabase db uri. I assume if one deploys this to fly or GCP, it will still works.
> 
> But my question is 'socket_timeout=10&connection_limit=1', does it mean there can only be one websocket connection at any given time? would this have any scalability issues when deployed to self-hosted cloud instance?
> 
> You also mentioned there will be a custom db instance feature later. Happy to contribute if you need any of my input.

I think this was mostly a limitation of SQLite, you can change these parameters if you are using a production ready DB

**Comment by willydouhard** [comment]
> > Right now we do not have a clean solution for that. The best way would be to provide API access. In the meantime you can check your chrome console network tab to get the http request the client is making when loading the history page and copy that to pull data.
> 
> For now It is working for me using Curl request. But looking for some scalable programmatic approach
> 
> Thanks @willydouhard

Definitely. This is a currently unstable part of Chainlit. We are working hard on making the data persistence layer right for the diversity of use cases the community has. Once this is done, we will invest the time to make sure everything is doable through the API.
