### ISSUE TITLE
-w argument in the chainlit run command doesn't work yet

### ISSUE THREAD

**Issue by lovishescobar** [Chainlit/chainlit#29]
As title, it's an honor to start developing chat based UIs swiftly through chainlit, it would be great if -w argument starts working in the windows in the upcoming updates.

**Comment by willydouhard** [comment]
Glad to hear Chainlit fits your needs! I still remember our conversation and I did not forget about this issue 😄. We will dig into it and hopefully fix it soon!

**Comment by lovishescobar** [comment]
I am in no hurry and this issue has been opened as suggested while other one was closed.

**Comment by willydouhard** [comment]
Could you try to:

1. install chainlit from the wheel provided in this PR https://github.com/Chainlit/chainlit/pull/40
2. run `chainlit hello`

I would like to see if the rework fix those issues. Note that this version is not merged yet. The infos to install are at the end of the PR's description.

**Comment by lovishescobar** [comment]
-w argument still doesn't work

**Comment by lovishescobar** [comment]
-w argument works! but there's a problem with async while running llms locallly

With
@cl.langchain_factory(use_async=True)

the following error appears

![Screenshot 2023-06-14 055114](https://github.com/Chainlit/chainlit/assets/134267736/651d3a2f-fe6c-4cf0-a925-49c09df316b4)

**Comment by willydouhard** [comment]
This means the LLM you are using does not have an async implementation (at the langchain level, not chainlit). Whenever possible you should use the async implementation, but in that case you will have to fallback to the sync implementation as it is the only one available. To do that change your factory with `@cl.langchain_factory(use_async=False)`
