### ISSUE TITLE
Chain of Thought UI crashes when langchain steps output dicts instead of strings

### ISSUE THREAD

**Issue by mpartel** [Chainlit/chainlit#291]
With `[Async]LangchainCallbackHandler`, when my intermediate steps output dicts instead of strings, the UI crashes.

Repro:
- Use the following code.
- Input a message.
- Click on "Took 1 step".
- Get "Something went wrong." with JS console saying "TypeError: r.trim is not a function".

```python
import chainlit as cl
from langchain.chains import TransformChain

@cl.on_message
async def main(message: str):
    def transform(inputs):
        return {
            'output': {
                'structured': {
                    'report': 'Done'
                }
            }
        }
    chain = TransformChain(
        input_variables=['text'],
        output_variables=['output'],
        transform=transform,
    )
    result = chain.run({'text': message}, callbacks=[cl.LangchainCallbackHandler()])
    return await cl.Message(content=result['structured']['report']).send()

```

(Possibly related [typing bug](https://github.com/langchain-ai/langchain/issues/9440) in LangChain 0.0.267, but I'm almost certain their intention is to allow intermediate steps to output whatever.)

**Comment by willydouhard** [comment]
Interesting, will investigate

**Comment by willydouhard** [comment]
<img width="322" alt="Screenshot 2023-08-18 at 17 10 22" src="https://github.com/Chainlit/chainlit/assets/13104895/fb757762-bf7a-4229-a8d0-86768163e17a">
Okay so this chain outputs a json object. Currently the Message component in the UI only accept strings. What would be the expected behavior here? Display the json object in a code block?

**Comment by mpartel** [comment]
Yes, that sounds good :+1:
