### ISSUE TITLE
Didn't get a response on even `chainlit hello` program on windows 11 system with VScode 

### ISSUE THREAD

**Issue by ashishpatel26** [Chainlit/chainlit#293]
```python

import chainlit as cl # type: GUI label

@cl.on_message
async def main(message: str):
    '''
    Print the message you sent
    '''
    # Your custom logic goes here

    # Send a response back to the user
    await cl.Message(
        content=f"Received: {message}",
    ).send()
```

when Run with below code:

```bash
chainlit hello
```
### Code Snap:

![image](https://github.com/Chainlit/chainlit/assets/3095771/818e9e19-6cd6-4328-8769-f2e0d48a8b5b)

### Browser Snapshot
![image](https://github.com/Chainlit/chainlit/assets/3095771/9eb83a9f-7e12-4a3a-b406-922d3f923aa1)

**Comment by ashishpatel26** [comment]
Code is also mentioned there @ramnes I am using version chainlit 0.6.2 latest one.

**Comment by ramnes** [comment]
`chainlit hello` doesn't run any code so it's irrelevant. If you want me to help I need you tell me how to reproduce this issue reliably. Running `chainlit hello` on my computer does give an answer when I type my name.
