### ISSUE TITLE
Chainlit run command doesn't work at all

### ISSUE THREAD

**Issue by lovishescobar** [Chainlit/chainlit#3]
`chainlit run app.py -w `
doesn't work at all

`chainlit hello` opens a blank window though

**Comment by constantinidan** [comment]
looking into it now

**Comment by willydouhard** [comment]
Thanks to @lovishescobar I was able to identify the root cause (https://stackoverflow.com/questions/59355194/python-flask-error-failed-to-load-module-script-strict-mime-type-checking-i). This will be most likely fixed in the `0.2.107` release 👍

**Comment by willydouhard** [comment]
Fixed in the `0.2.107` release! You can upgrade with `pip install -U chainlit`. Let us now if that fixes the issue for you :)

**Comment by Anjum48** [comment]
`0.2.107` fails to show anything for me. A browser pops up, but I get:

```
This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```
Running on Windows

**Comment by lovishescobar** [comment]
doesn't work with -w argument
