### ISSUE TITLE
not able to run chainlit hello in Visual Studio Code

### ISSUE THREAD

**Issue by ianyian** [Chainlit/chainlit#305]
after run the command: pip install chainlit , when i try to test the command: chainlit hello but failed. error shown below,
can any expert help me on this ?
my enviroment: win11 pro
IDE: visual studio code

chainlit : The term 'chainlit' is not recognized as the name of a cmdlet, function, script file, or operable program. Check     
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ chainlit hello
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (chainlit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by willydouhard** [comment]
Check this [discord post](https://discord.com/channels/1088038867602526210/1133987998996897913). It should resolve your issue.

**Comment by ianyian** [comment]
Hi @willydouhard  it seen like discord link is broken, nothing inside the page, appreciate you could help to route to a correct link
thanks.

**Comment by willydouhard** [comment]
Weird, it works for me, attaching a screenshot instead:

sometimes on windows the chainlit executable path is not registered automatically in the $PATH variable

<img width="1150" alt="Screenshot 2023-08-22 at 12 08 10" src="https://github.com/Chainlit/chainlit/assets/13104895/1e30f16d-7578-4067-a805-a0599babf962">

**Comment by ianyian** [comment]
thanks ! finally i managed to find the file ! thanks !
C:\Users\james\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\chainlit.exe
