### ISSUE TITLE
alternate for @cl.langchain_factory(use_async=True) , streaming

### ISSUE THREAD

**Issue by poojitharamachandra** [Chainlit/chainlit#313]
hi, what is the alternate/substitute for @cl.langchain_factory(use_async=False) in version 0.6.3?

**Comment by willydouhard** [comment]
Hello, here is the migration guide https://docs.chainlit.io/guides/migration/0.6.0

**Comment by willydouhard** [comment]
Then you can fallback to the sync implementation like so:

```py
cl.user_session.set("llm_chain", qa_generator.qa_chain)
cb = cl.LangchainCallbackHandler(
    stream_final_answer=True, answer_prefix_tokens=["FINAL", "ANSWER"]
)

# Retrieve the chain from the user session
llm_chain = cl.user_session.get("llm_chain")
acall = cl.make_async(llm_chain)
res = await acall(
    input_str,callbacks = [cb] )
```

**Comment by poojitharamachandra** [comment]
hi thanks,  but i still cannot get the streaming of final answer
there is no error while running the code, but streaming is not hapenning

**Comment by willydouhard** [comment]
Final answer streaming is conditioned by the `answer_prefix_tokens`. Which means your chain has to always include this prefix before the final answer. If it does not and your chain has a single step you can [manually force ](https://github.com/Chainlit/cookbook/blob/main/pdf-qa/app.py#L109) streaming.

**Comment by poojitharamachandra** [comment]
hi, i am still unable to get the streaming running.

here is my code.please suggest if i need to do something more
        model = AutoGPTQForCausalLM.from_quantized(model_path,
                                                   model_basename=model_basename,
                                                   use_safetensors=True,
                                                   trust_remote_code=True,
                                                   device_map='auto',
                                                   use_triton=False,
                                                   load_in_8bit=True,
                                                   quantize_config=None,
                                                   streaming=True)
                streamer = TextStreamer(tokenizer)
pipe = pipeline(
            "text-generation",
            model=model,
            tokenizer=tokenizer,
            max_new_tokens=512,
            temperature=0.0,
            top_p=0.95,
            repetition_penalty=1.15,
            streamer=streamer
        )

@cl.on_message
async def run(input_str):
    cb = cl.LangchainCallbackHandler(
        stream_final_answer=True, answer_prefix_tokens=["Helpful Answer:","result"]
    )
    cb.answer_reached = True
    print('user question',input_str)

    # Retrieve the chain from the user session
    llm_chain = cl.user_session.get("llm_chain") 
    res = await cl.make_async(llm_chain)(
        input_str,callbacks = [cb] #callbacks=[cl.ChainlitCallbackHandler()]
    )
    
    for i in res["source_documents"]:
        print(f"***Page***: {i.metadata['page']} \n***Source***: {i.metadata['source']} \n***Context***:{i.page_content}")
    await cl.Message(content=res["result"]).send()

**Comment by willydouhard** [comment]
What is the behavior you observe? Are the intermediate steps streamed and only the final answer is not streamed? Or is streaming not working at all?

**Comment by poojitharamachandra** [comment]
both intermediate and final answers are not streamed

**Comment by willydouhard** [comment]
I see, as I said in my previous message could you provide the full snippet of code? I would like to reproduce on my machine to help you resolve this issue.

**Comment by poojitharamachandra** [comment]
unfortunately i cannot share the complete code as it contains some sensitive information :(

**Comment by willydouhard** [comment]
I understand, a minimum reproducible case then? Like the imports, the llm instantiation with a random llm chain?

**Comment by willydouhard** [comment]
Chainlit does not force a specific langchain version. You can freely upgrade your langchain installation independently of chainlit's

**Comment by poojitharamachandra** [comment]
> I understand, a minimum reproducible case then? Like the imports, the llm instantiation with a random llm chain?



from gc import callbacks
import os
import langchain
import langchain.text_splitter
import torch
from transformers import LlamaTokenizer, LlamaForCausalLM, pipeline, TextStreamer, AutoTokenizer,AutoModelForCausalLM
from langchain.llms import HuggingFacePipeline, llamacpp
from langchain.vectorstores import Chroma, FAISS
from langchain.text_splitter import (
    RecursiveCharacterTextSplitter,
    CharacterTextSplitter,
    TokenTextSplitter,
)

from langchain import PromptTemplate, LLMChain

from langchain.schema import Document
from langchain.chains import RetrievalQA
from langchain.document_loaders import DirectoryLoader, PyPDFLoader
from langchain.embeddings import HuggingFaceInstructEmbeddings
import textwrap
import chainlit as cl
from chainlit.sync import asyncify
from typing import List


template = """
You are a helpful AI assistant. Provide the answer for the following question:

Question: {question}
Answer: 
"""

model_basename = "longchat-7b-16k-GPTQ-4bit-128g.no-act.order"
model = AutoGPTQForCausalLM.from_quantized(model_path,
                                                   model_basename=model_basename,
                                                   use_safetensors=True,
                                                   trust_remote_code=True,
                                                   device_map='auto',
                                                   use_triton=False,
                                                   load_in_8bit=True,
                                                   quantize_config=None,
                                                   streaming=True)


tokenizer = AutoTokenizer.from_pretrained(model_path)

streamer = TextStreamer(tokenizer)

pipe = pipeline(
    "text-generation", model=model, tokenizer=tokenizer, max_new_tokens=50, batch_size=8, streamer=streamer
)
llm = HuggingFacePipeline(pipeline=pipe)


@cl.on_chat_start
async def main():
    
    prompt = PromptTemplate(template=template, input_variables=["question"])
    llm_chain = LLMChain(prompt=prompt, llm=llm)
    cl.user_session.set("llm_chain", llm_chain) 

    return llm_chain
 



#@cl.langchain_run
@cl.on_message
async def run(input_str):

    # res = agent(input_str)
    cb = cl.LangchainCallbackHandler(
        stream_final_answer=True, stream_prefix=True, answer_prefix_tokens=["Answer"]
    )
    cb.answer_reached = True
    print('user question :',input_str)

    # Retrieve the chain from the user session
    llm_chain = cl.user_session.get("llm_chain") 
    res = await cl.make_async(llm_chain)(
        input_str,callbacks = [cb] #callbacks=[cl.ChainlitCallbackHandler()]
    )
    print(res)
    await cl.Message(content=res["text"]).send()

**Comment by poojitharamachandra** [comment]
The answer is streamed to stdout, but not onto chainlit UI

**Comment by poojitharamachandra** [comment]
the model is taken from https://huggingface.co/TheBloke/LongChat-7B-GPTQ

**Comment by willydouhard** [comment]
I am able to reproduce with the following code:

```py
from langchain.llms import HuggingFacePipeline
from transformers import AutoTokenizer, TextStreamer
from langchain import PromptTemplate, LLMChain
import transformers
import torch

import chainlit as cl

template = """
You are a helpful AI assistant. Provide the answer for the following question:

Question: {question}
Answer:
"""


@cl.cache
def load_llama():
    model = "meta-llama/Llama-2-7b-chat-hf"
    tokenizer = AutoTokenizer.from_pretrained(model)
    streamer = TextStreamer(tokenizer, skip_prompt=True)
    pipeline = transformers.pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        torch_dtype=torch.float16,
        trust_remote_code=True,
        device_map="auto",
        max_length=1000,
        do_sample=True,
        top_k=10,
        num_return_sequences=1,
        eos_token_id=tokenizer.eos_token_id,
        streamer=streamer,
        use_auth_token=True,
    )

    llm = HuggingFacePipeline(
        pipeline=pipeline,
        model_kwargs={"temperature": 0},
    )
    return llm


llm = load_llama()


@cl.on_chat_start
async def main():
    prompt = PromptTemplate(template=template, input_variables=["question"])
    llm_chain = LLMChain(prompt=prompt, llm=llm)
    cl.user_session.set("llm_chain", llm_chain)

    return llm_chain


@cl.on_message
async def run(input_str):
    cb = cl.AsyncLangchainCallbackHandler(
        stream_final_answer=True, answer_prefix_tokens=["Answer"]
    )
    cb.answer_reached = True

    # Retrieve the chain from the user session
    llm_chain = cl.user_session.get("llm_chain")  # type: LLMChain
    res = await llm_chain.acall(input_str, callbacks=[cb])
```

The problem is that the langchain callback `on_llm_new_token` method is never called, only `on_llm_start` and `on_llm_end`. However the response is correctly streamed to the stdout. It seems to be a langchain issue.
