### ISSUE TITLE
Safari reports Unexpected Application Error! This error will appear from chainlit==0.5.1

### ISSUE THREAD

**Issue by a327958099** [Chainlit/chainlit#314]
Unexpected Application Error!

a.findLast is not a function. (In 'a.findLast(v=>v.type==="tasklist")', 'a.findLast' is undefined)

L7e@http://192.168.31.199:8000/assets/index-7813ab71.js:507:1178025
xT@http://192.168.31.199:8000/assets/index-7813ab71.js:38:78073
W4@http://192.168.31.199:8000/assets/index-7813ab71.js:40:130644
j4@http://192.168.31.199:8000/assets/index-7813ab71.js:40:126376
wJ@http://192.168.31.199:8000/assets/index-7813ab71.js:40:126304
J0@http://192.168.31.199:8000/assets/index-7813ab71.js:40:126157
uE@http://192.168.31.199:8000/assets/index-7813ab71.js:40:122522
k$@http://192.168.31.199:8000/assets/index-7813ab71.js:40:123326
k$@[native code]
Jl@http://192.168.31.199:8000/assets/index-7813ab71.js:38:61812
http://192.168.31.199:8000/assets/index-7813ab71.js:40:120852
![QQ20230824-183519](https://github.com/Chainlit/chainlit/assets/26393031/238ed905-5855-4172-8b4d-ad40ff8c30e6)

**Comment by willydouhard** [comment]
What version of Safari are you using? Here is the [CanIUse](https://caniuse.com/?search=findLast) for findLast

**Comment by a327958099** [comment]
> 您使用什么版本的 Safari？这是findLast 的[CanIUse](https://caniuse.com/?search=findLast)

Safari  14.1.3 (16611.3.10.1.19)

**Comment by willydouhard** [comment]
Yep, findLast is supported by >15.4. Any chance you can update Safari?

**Comment by a327958099** [comment]
> Yep, findLast is supported by >15.4. Any chance you can update Safari?

OK, got it, thanks
