### ISSUE TITLE
AskUserMessage always takes the full timeout time to complete

### ISSUE THREAD

**Issue by monaxu1** [Chainlit/chainlit#319]
Version: chainlit==0.6.2

Problem: Time taken to get the response from AskUserMessage is always the full timeout time (60 secs).
```
import time
import chainlit as cl

time_start = time.time()
res = await cl.AskUserMessage(content=question, timeout=60).send()
time_end = time.time()
print(f"Async: Time taken (secs): {time_end - time_start}")
```

**Comment by willydouhard** [comment]
Are you using `AskUserMessage` in either `cl.on_chat_start` or `cl.on_message`?

**Comment by monaxu1** [comment]
It's with @cl.on_chat_start

**Comment by willydouhard** [comment]
This is the code of `chainlit hello`:

```py
# This is a simple example of a chainlit app.

from chainlit import AskUserMessage, Message, on_chat_start


@on_chat_start
async def main():
    res = await AskUserMessage(content="What is your name?", timeout=30).send()
    if res:
        await Message(
            content=f"Your name is: {res['content']}.\nChainlit installation is working!\nYou can now start building your own chainlit apps!",
        ).send()
```

Both this code and `chainlit hello` works on my end, can you confirm?

**Comment by monaxu1** [comment]
Actually, I'm using it in a function that is called by the main fun with cl.on_chat_start

async def async_ask_question(question: str) -> str:
    print("Async: Asking question")
    time_start = time.time()
    res = await cl.AskUserMessage(content=question, timeout=60).send()
    time_end = time.time()
    print(f"Async: Time taken (secs): {time_end - time_start}")
    if res:
        return res["content"]
    else:
        return "No response"

**Comment by willydouhard** [comment]
does `chainlit hello` work on your end?
