### ISSUE TITLE
"Waiting for thread pool to idle before working"?

### ISSUE THREAD

**Issue by JavedNissar** [Chainlit/chainlit#32]
Hey folks, I'm on Mac OSX Ventura 13.4 and Chainlit 0.2.109. Whenever I run the following command:
```
chainlit hello
```
I get a stream of the following error repeatedly (I can't even control-c out of it):
```
E0603 21:07:29.252949000 8303107584 thread_pool.cc:230]                Waiting for thread pool to idle before forking
```

Any chance anyone knows what this means?

**Comment by willydouhard** [comment]
Hello, what version of `grpcio` do you have installed? you can run `pip show grpcio` to find out. Then if you do not have `1.53.0` try to install it.
