### ISSUE TITLE
How to control image size?

### ISSUE THREAD

**Issue by liebkne** [Chainlit/chainlit#326]
I tried 

```
<img src="public/market/357b5d47f5cb45669cf88b89c38e6559.png" height="700" width="500"/>
```

but it did not work. Thanks.

**Comment by willydouhard** [comment]
Do you mean the [Image element](https://docs.chainlit.io/api-reference/elements/image) or in the readme? The image element has a `size` parameter.

**Comment by liebkne** [comment]
Oh, sorry I missed that. I use `markdown` to send images. Is using markdown to send image not a recommended way?

**Comment by willydouhard** [comment]
The rule of thumb is to use Element when possible :)

**Comment by liebkne** [comment]
Thanks!
