### ISSUE TITLE
How to embed plotly figures?

### ISSUE THREAD

**Issue by failable** [Chainlit/chainlit#327]
The title says it all...

**Comment by willydouhard** [comment]
Have you checked the [documentation](https://docs.chainlit.io/api-reference/elements/pyplot)?

**Comment by liebkne** [comment]
The documentation is about `pyplot`, not `plotly`.

**Comment by willydouhard** [comment]
My bad, currently we don't have an integration for plotly. What you can do is to convert your plot in an image and use the Image element. It will not be interactive though.

**Comment by Rictus** [comment]
This issue can be closed
