### ISSUE TITLE
Really bad memory leak

### ISSUE THREAD

**Issue by Banbury** [Chainlit/chainlit#35]
Version: 0.2.109

When I start chainlit with a completely empty file, there is a constant load on the CPU and the RAM usage goes constantly up at a very quick rate. After a few minutes the Python process fills up all RAM.
This only seems to happen with the watch mode (-w).

### Steps to reproduce:
* Create an empty file app.py
* Start chainlit with the code below.
```
chainlit run app.py -w
```

**Comment by willydouhard** [comment]
Thank you for letting me know, will investigate that tomorrow

**Comment by willydouhard** [comment]
Could you try to:

1. install chainlit from the wheel provided in this PR https://github.com/Chainlit/chainlit/pull/40
2. run `chainlit hello`

I would like to see if the rework fix this issue. Note that this version is not merged yet. The infos to install are at the end of the PR's description.
