### ISSUE TITLE
Error: Invalid value: File does not exist: target.py

### ISSUE THREAD

**Issue by Sheldenburg** [Chainlit/chainlit#36]
tried to set up the server. 
When I run chainlit run target.py -h
it says Error: Invalid value: File does not exist: target.py

**Comment by willydouhard** [comment]
Sorry to ask the question but does the file `target.py` exists in the folder you run the command in?

**Comment by Sheldenburg** [comment]
> Sorry to ask the question but does the file `target.py` exists in the folder you run the command in?

Thanks for your reply. no, I couldn't find target.py anywhere in the whole repo.
