### ISSUE TITLE
Right align user Messsages 

### ISSUE THREAD

**Issue by SathishNaqel** [Chainlit/chainlit#379]
How can i align the user messages to right ? Any help would be much appreciated?

**Comment by willydouhard** [comment]
Good question, we just merged a PR that allows for custom CSS so that might be a good candidate. It will be available and documented in the next release.

**Comment by ModEnter** [comment]
Hello, you can achieve this by using the [Custom CSS](https://docs.chainlit.io/customisation/custom-css#css) functionnality, as @willydouhard mentionned.
