### ISSUE TITLE
File Element raise error when use local database

### ISSUE THREAD

**Issue by LiuKay** [Chainlit/chainlit#387]
The databse config set to "local":
![image](https://github.com/Chainlit/chainlit/assets/21058165/76e738a5-26c0-4cf2-8489-d586184f8ac6)

app code:
```python
@cl.on_chat_start
async def start():
    elements = [
        cl.File(
            name="test.py",
            path="./test.py",
            display="inline",
        ),
    ]

    await cl.Message(
        content="This message has a file element", elements=elements
    ).send()
```
Result:
![image](https://github.com/Chainlit/chainlit/assets/21058165/1cb943e4-08c1-46a2-847f-516f30014bec)

**when I conmment the database config, it works well.**

**Comment by willydouhard** [comment]
Hello, with the latest release the `database` settings as well as `local` db were [removed](https://docs.chainlit.io/guides/migration/0.7.0). Would love to know if that issue persists with the [new](https://docs.chainlit.io/cloud/persistence/overview) data persistence layer.
