### ISSUE TITLE
Command to stop chainlit running on local machine.

### ISSUE THREAD

**Issue by ashusnapx** [Chainlit/chainlit#388]
their should be a command to stop chainlit, same as control + c on mac to stop many things

**Comment by SiddhantSadangi** [comment]
ctrl/cmd + c stops it everywhere

**Comment by ashusnapx** [comment]
> ctrl/cmd + c stops it everywhere

but its not working on mac, i tried and then only i've raised this issue.

**Comment by SiddhantSadangi** [comment]
Sorry, I misunderstood the Q.
It's been a while since I used a Mac. Can you try `ctrl` + `d`?
https://stackoverflow.com/a/18047735/9792001

**Comment by ashusnapx** [comment]
that too didn't worked!

**Comment by willydouhard** [comment]
ctrl+c should work on mac. For instance if you run `chainlit hello` and try to shut it down, does it work?
