### ISSUE TITLE
Is it possible to access the full request object, in particular the headers?

### ISSUE THREAD

**Issue by Midnighter** [Chainlit/chainlit#393]
When I include a request parameter in my message handler

```py
import chainlit as cl
from fastapi import Request

@cl.on_message
def handle_message(message: str, request: Request):
    print(request)
```

It turns out that the request object is just a string with presumably the session id. Is it at all possible to access the full object or at least the headers of the request?

**Comment by willydouhard** [comment]
This is not possible since on_message is a websocket message, not an http request. Do you want to access the headers for authentication purposes?

**Comment by Midnighter** [comment]
> This is not possible since on_message is a websocket message, not an http request.

I was afraid that's the case.

We have [Posit Connect](https://docs.posit.co/rsc/) running to handle authentication. However, I was still hoping to grab some kind of user identifier from the headers. It was just a try, I'm not sure there even would be useful information there.

**Comment by willydouhard** [comment]
we could expose the handshake headers. However we are going to release today or tomorrow a completely overhauled authentication system. It will include a `header_auth` for companies running chainlit through a reverse proxy. Would love to get your feedback before considering exposing the headers :)

**Comment by Midnighter** [comment]
Happy to test something. Just let me know which branch or release candidate you would like me to test.

**Comment by willydouhard** [comment]
Here is the [announcement](https://discord.com/channels/1088038867602526210/1096367751481802812/1151915856977203230) with all the details

**Comment by Midnighter** [comment]
I'll give it a whirl. Thanks.

**Comment by Midnighter** [comment]
Okay, I've tried the new versions and successfully accessed the headers using the `@cl.header_auth_callback` handler.

My main question now is, can I somehow access the current user in a `cl.on_message` handler? You must somehow know the correct user since you are exposing the specific `cl.user_session` object. I would very much like to get a user identifier.

**Comment by willydouhard** [comment]
Yes, this is not documented enough but you can see an example in the[ password test](https://github.com/Chainlit/chainlit/blob/main/cypress/e2e/password_auth/main.py)

**Comment by Midnighter** [comment]
Perfect, thank you! 😃

**Comment by Siddhijain16** [comment]
> Okay, I've tried the new versions and successfully accessed the headers using the `@cl.header_auth_callback` handler.
> 
> My main question now is, can I somehow access the current user in a `cl.on_message` handler? You must somehow know the correct user since you are exposing the specific `cl.user_session` object. I would very much like to get a user identifier.

Hi @Midnighter 
I have tried to apply password auth but it didn't work for me.Might be I am not calling properly, Not sure. If possible can you please share your code/file on which you apply authentication.

**Comment by willydouhard** [comment]
password auth or header auth? Can you share a snippet of code?

**Comment by Siddhijain16** [comment]
> password auth or header auth? Can you share a snippet of code?

Thanks for the reply. I resolved it.

**Comment by JaredChung** [comment]
Follow up on this conversation, I was wondering if there was any change in allowing access to the Request object in the @on_chat_start. There is information in the header I want to get access beyond the authorisation level.
