### ISSUE TITLE
LlamaIndex integration requirement

### ISSUE THREAD

**Issue by mintisan** [Chainlit/chainlit#4]
as title...

**Comment by badcom** [comment]
+1 to this.

**Comment by willydouhard** [comment]
I would be interested to see a snippet of code showcasing your use case and what you would expect from the Chainlit integration.

It would help to make the requirements of the integration explicit :)

**Comment by msorea** [comment]
Hi. I am using LlamaIndex and for the past 2 days it has been giving errors in the output string. It repeats the content of the previous output in the response. Have the latest LlamaIndex enhancements affected the outputs? Please help/ advise. thanks

**Comment by ipullrank** [comment]
+1

**Comment by willydouhard** [comment]
We are starting to think about this integration. If you guys could provide more context about your use cases that would help us a lot!

**Comment by willydouhard** [comment]
Hello guys, we are starting to work on this. Draft PR [here](https://github.com/Chainlit/chainlit/pull/87). Would love some feedback!

**Comment by willydouhard** [comment]
The latest release is introducing a first version of our Llama Index integration!
