### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by yaacine** [Chainlit/chainlit#400]
I'm unable to login using my google account.
Please note that all the users were previously able to login without any issue. I just got this error today when trying to login.

I have self-hosted this app and linked it to a project in https://cloud.chainlit.io/ 

![image](https://github.com/Chainlit/chainlit/assets/32752884/5ce7e62f-8d51-43bf-b4fa-9c89faa23ddc)

**Comment by willydouhard** [comment]
We released yesterday chainlit `0.7.0` which completely changes how auth works. Migration guide available [here](https://docs.chainlit.io/guides/migration/0.7.0).

Long story short chainlit app authentication is now completely decoupled from chainlit cloud. You will be able to directly use your own google oauth app to authenticate users and have complete control over it.

Full authentication documentation [here](https://docs.chainlit.io/authentication/overview).
Data persistence also changed but is really easy to setup, documentation [here](https://docs.chainlit.io/cloud/persistence/overview).
