### ISSUE TITLE
AzureChat Bad Request engine / deployment__id

### ISSUE THREAD

**Issue by johannes-dornheim** [Chainlit/chainlit#412]
Hi

when i try to use the pre-defined AzureChatOpenAI provider in the playground i get the following error:

`Bad Request: OpenAI API request was invalid: Must provide an engine or deployment_id parameter to create a <class ... ChatCompletion>.`

where do i set the deployment_id per model (Ive already set the required environment vars OPENAI_API_BASE, OPENAI_API_KEY, OPENAI_API_TYPE, OPENAI_API_VERSION)?

Best,
Johannes

**Comment by willydouhard** [comment]
You should set `OPENAI_API_DEPLOYMENT_ID`

**Comment by johannes-dornheim** [comment]
tyvm for the fast answer, indeed it works when setting it. I have not seen it in documentation nor in the azure_openai_env_vars.

`azure_openai_env_vars = {
    "api_key": "OPENAI_API_KEY",
    "api_type": "OPENAI_API_TYPE",
    "api_base": "OPENAI_API_BASE",
    "api_version": "OPENAI_API_VERSION",
}`

https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/playground/providers/openai.py

**Comment by willydouhard** [comment]
Yes more documentation on that would not hurt
