### ISSUE TITLE
Azure AD OAuth - incorrect endpoint for getting current logged-in user data

### ISSUE THREAD

**Issue by triantafillos** [Chainlit/chainlit#415]
The correct endpoint to use from MS Graph API to get the current user's data is `https://graph.microsoft.com/v1.0/me`. Instead, in oauth_providers.py (line 177) it is incorrectly set to `https://graph.microsoft.com/v1.0/users/me`.

**Comment by willydouhard** [comment]
@tpatel can you take a look a this?

**Comment by tpatel** [comment]
Thanks for bringing this issue up.

From testing the API, it looks like both option work.
From the documentation side, it looks like `https://graph.microsoft.com/v1.0/me` is indeed the correct option.

Would you be interested in making this change? If not I'll get it done tomorrow!
