### ISSUE TITLE
Having the same issue here. Running on a linux server, no error message, just a blank page. Specifying the host and port did not help in any way.

### ISSUE THREAD

**Issue by SurachaiJaisan** [Chainlit/chainlit#43]
Having the same issue here. Running on a linux server, no error message, just a blank page. Specifying the host and port did not help in any way.

_Originally posted by @sebderhy in https://github.com/Chainlit/chainlit/issues/38#issuecomment-1582755321_

**Comment by willydouhard** [comment]
Could you try to:

1. install chainlit from the wheel provided in this PR https://github.com/Chainlit/chainlit/pull/40
2. run `chainlit hello`

I would like to see if the rework fix those issues. Note that this version is not merged yet. The infos to install are at the end of the PR's description.

**Comment by ruidongtd** [comment]
> Could you try to:
> 
> 1. install chainlit from the wheel provided in this PR [Experiment with FastAPI (async architecture by default) #40](https://github.com/Chainlit/chainlit/pull/40)
> 2. run `chainlit hello`
> 
> I would like to see if the rework fix those issues. Note that this version is not merged yet. The infos to install are at the end of the PR's description.

#44

**Comment by Cenrax** [comment]
> ```
>           Having the same issue here. Running on a linux server, no error message, just a blank page. Specifying the host and port did not help in any way.
> ```
> 
> _Originally posted by @sebderhy in [#38 (comment)](https://github.com/Chainlit/chainlit/issues/38#issuecomment-1582755321)_

I am also facing the same problem

**Comment by willydouhard** [comment]
Should be fixed in the latest version `0.3.0`. Please note that it contains breaking changes. We prepared a [migration guide](https://docs.chainlit.io/migration/0.3.0) to make it easy for everyone.

**Comment by ruidongtd** [comment]
I tried version 0.3.0 and it didn't fix the problem


> Should be fixed in the latest version `0.3.0`. Please note that it contains breaking changes. We prepared a [migration guide](https://docs.chainlit.io/migration/0.3.0) to make it easy for everyone.

**Comment by willydouhard** [comment]
Interesting, can you dm me on discord so we can debug this live? Will be easier

**Comment by willydouhard** [comment]
see https://github.com/Chainlit/chainlit/issues/38
