### ISSUE TITLE
LAN SSL requirement

### ISSUE THREAD

**Issue by urbanscribe** [Chainlit/chainlit#44]
when trying to access a running chainlit over LAN (one box to another) an SSL transport is required

auth0-spa-js must run on a secure origin. See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.

would it be possible to add a --share flag or other method to allow a LAN server to serve pages on a LAN without SSL requirement?

**Comment by ruidongtd** [comment]
same issue

**Comment by willydouhard** [comment]
Should be fixed in the latest version `0.3.0`. Please note that it contains breaking changes. We prepared a [migration guide](https://docs.chainlit.io/migration/0.3.0) to make it easy for everyone.
