### ISSUE TITLE
WSL not correctly initializing, not accessible on host and inside WSL

### ISSUE THREAD

**Issue by ghillb** [Chainlit/chainlit#449]
chainlit version: 0.7.1

Setup: chainlit installed inside WSL2 Ubuntu 22.04 conda environment.

Procedure:
- execute `chainlit hello` 
- can't open localhost:8000 in windows host, even though port 8000 is forwared
```
Unable to connect
Can’t establish a connection to the server at localhost:8000.
```
- also `curl localhost:8000` inside wsl yields 
```
curl localhost:8000
curl: (7) Failed to connect to localhost port 8000 after 0 ms: Connection refused
```

In contrast, both works with `streamlit hello`.

It seems chainlit fails initialization, when starting from a wsl terminal. 

There is no such problem when chainlit is started from a native windows termina on this machinel.

**Comment by ghillb** [comment]
This is the output. Notice how after executing the command, it stops at
```
2023-10-03 21:57:24 - Your app is available at http://localhost:1334
```
After pressing ctrl-c, it hangs at (have to kill the terminal to kill the process).
```
 INFO:     Uvicorn running on http://0.0.0.0:1334 (Press CTRL+C to quit)
```
![image](https://github.com/Chainlit/chainlit/assets/35503959/b83ef5af-533b-47b1-b288-bd07b971a309)

I used `chainlit run demo.py --port 1334 -w -d` because there is no `-d` flag with `chainlit hello`.

**Comment by willydouhard** [comment]
is http://localhost:1334 accessible from wsl? What happens if you curl it

**Comment by ghillb** [comment]
After uvicorn is running curl produces this:
![image](https://github.com/Chainlit/chainlit/assets/35503959/6d8f6f1e-539e-4b46-9228-b970fe455719)

I think it may is related to the behavior that chainlit tries to open the browser automatically after starting. At least I got some xdg-open errors (but I was not able to reproduce it).

**Comment by MathiasSpanhove** [comment]
Weird you're having this issue, I'm also using chainlit in WSL2 and don't have these issues.

**Comment by willydouhard** [comment]
For the browser issue you can add `-h` (headless) to the run command.

**Comment by ghillb** [comment]
With `-h` it does not hang anymore and chainlit is accessible from the windows host! `-h` doesn't work with `chainlit hello` but that's no big deal for me. So I'm good with closing this one, if it's fine for you.

**Comment by willydouhard** [comment]
Good to know, glad it works!
