### ISSUE TITLE
It consumes a significant amount of computer resources.

### ISSUE THREAD

**Issue by wupengfei0904** [Chainlit/chainlit#45]
I start Chainlit, the CPU usage reaches 50%, and the memory gradually increases by 5GB. My computer is equipped with an i7 12700 processor and 32GB of RAM. When I close the program, approximately 6GB of memory is released.

**Comment by willydouhard** [comment]
This is unexpected. Are you running a default example or a heavy task like running a local LLM?

**Comment by wupengfei0904** [comment]
I just reproduced it again. My environment is Win11 + Python 3.11. I used the example from the documentation, and after running it, both the CPU and RAM suddenly spiked.
![微信截图_2023060916432
![微信截图_20230609164333](https://github.com/Chainlit/chainlit/assets/125854485/26da6642-72df-49a4-800a-cce810d88595)
1](https://github.com/Chainlit/chainlit/assets/125854485/e3c42acf-4277-48f2-8ce9-e360c4158a09)
![微信截图_20230609164441](https://github.com/Chainlit/chainlit/assets/125854485/6562f232-0c65-44a0-bf8c-3cad440b2820)
![微信截图_20230609164502](https://github.com/Chainlit/chainlit/assets/125854485/eb10db53-c92e-49aa-978a-375ef7da430b)

**Comment by willydouhard** [comment]
Okay, could you try with the wheel provided in this PR? https://github.com/Chainlit/chainlit/pull/40 you can just pip install it and run `chainlit hello` to see if you see the same resource consumption.

**Comment by wupengfei0904** [comment]
Hello, author. I have resolved the issue using version 0.3.0 of Chainlit. Both the CPU and RAM are stable now, and there are no spikes.

**Comment by willydouhard** [comment]
Amazing! this version is not yet merged (soon hopefully) and the docs are not updated to reflect the changes. So be careful with that while we update everything

**Comment by SurachaiJaisan** [comment]
+

**Comment by SurachaiJaisan** [comment]
O

**Comment by wupengfei0904** [comment]
Hello, author. May I ask when the official release of FastAPI version will be available? Additionally, have you considered supporting the ChatGPT standard plugins, such as ChatGPT UI, which allows for installing and selecting the desired plugins for use?

**Comment by willydouhard** [comment]
I hope to merge it early next week if everything is ok. We thought about the plugins, our first try was with the LangChain integration: https://github.com/Chainlit/cookbook/tree/main/langchain-aiplugins but not every plugin is compatible. Plus not all the plugins are public.

**Comment by willydouhard** [comment]
Should be fixed in the latest version `0.3.0`. Please note that it contains breaking changes. We prepared a [migration guide](https://docs.chainlit.io/migration/0.3.0) to make it easy for everyone.
