### ISSUE TITLE
Make "Login to access the app" text configurable.

### ISSUE THREAD

**Issue by jimmarshall87** [Chainlit/chainlit#450]
Currently the title attribute of the AuthLogin is 'Login to access the app.'.

It would be great to make this a configurable field in the config file to allow for some light customisation/localisation.

**Comment by willydouhard** [comment]
I agree, open to contributions on this!

**Comment by jimmarshall87** [comment]
We can have a crack at this if you like - is there something similar we can copy the pattern for which does the same thing - ie config file entry passed to front end component attribute?
