### ISSUE TITLE
[Bug] Getting spammed with SSL Handshake Error when ru

### ISSUE THREAD

**Issue by leehanchung** [Chainlit/chainlit#46]
The web application runs, but on the terminal I am getting spammed with SSL Certificate Verify Failed errors.

```0608 23:35:42.397180000 6108459008 ssl_transport_security.cc:1420]    Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.```

**Comment by willydouhard** [comment]
Are you running it locally or deployed somewhere?

**Comment by leehanchung** [comment]
> 

Running locally, behind VPN.

Whats this SSL thing about?

**Comment by leehanchung** [comment]
This package currently would not pass any security audit.

**Comment by willydouhard** [comment]
Thank you for your feedback. I agree these things are coupled for now and we definitely want to decouple them to make sure everyone could drop in their own solution!

**Comment by willydouhard** [comment]
Are you using chroma db by any chance?

**Comment by willydouhard** [comment]
Did you try to disable the telemetry? You can set the `enable_telemetry` in your `.chainlit/config.toml` file to `false`.
