### ISSUE TITLE
Document fix

### ISSUE THREAD

**Issue by 315930399** [Chainlit/chainlit#464]
In this example: [https://docs.chainlit.io/examples/qa](url)
`chain_type_kwargs` is not used, I recommend to modify as following:

 `combine_docs_chain_kwargs = {"prompt": prompt}`

```
chain = ConversationalRetrievalChain.from_llm(
        ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0, streaming=True),
        chain_type="stuff",
        retriever=docsearch.as_retriever(),
        memory=memory,
        return_source_documents=True,
        combine_docs_chain_kwargs = combine_docs_chain_kwargs
    )
```

**Comment by ModEnter** [comment]
Hello, the example has been changed since, I'm closing this issue. Thank you for this contribution
