### ISSUE TITLE
chainlit send message not being called in async setup

### ISSUE THREAD

**Issue by poojitharamachandra** [Chainlit/chainlit#466]
hi,

i have a code something like this:

@cl.on_message
async def run(input_str):
 ...........................
...............................
   await play_answer(res['result'])

   await cl.Message(content=fnl_ans).send()

but only play_answer is getting executed, but i dont see the fnl_ans on the chainlit UI. the execution of the whole code is also blocked

**Comment by willydouhard** [comment]
What does the play_answer function look like? Hard to debug without the code.

**Comment by poojitharamachandra** [comment]
async def play_soundfile():

    #playsound.playsound('./ans.wav') 

    # Initialize the mixer module for audio playback
    pygame.mixer.init()

    # Load the audio file
    pygame.mixer.music.load(wavefile)

    # Play the audio
    pygame.mixer.music.play()

    # Wait for the audio to finish playing (optional)
    while pygame.mixer.music.get_busy():
        pygame.time.Clock().tick(10)
        

    # Release the audio resources
    pygame.mixer.quit()

**Comment by willydouhard** [comment]
Can you try to wrap the function call like this `await cl.make_async(play_answer)(res['result'])`?

**Comment by poojitharamachandra** [comment]
if i wrap the function, the soundclip is not being played  and i get the following error :

RuntimeWarning: coroutine 'play_answer' was never awaited
  self.run()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by willydouhard** [comment]
is the play_answer function marked as async? If that is the case are you doing any await in it?

**Comment by poojitharamachandra** [comment]
async def play_answer(text):
    await play_soundfile()
