### ISSUE TITLE
Issue #430 comes back in version 0.7.2

### ISSUE THREAD

**Issue by wxp16** [Chainlit/chainlit#467]
Hello @willydouhard, I manually added base_url in the [UI] part of file `config.toml`. Maybe I did something wrong, pls advise..
```
[UI]
# Name of the app and chatbot.
name = "Chatbot"
# If the app is served behind a reverse proxy (like cloud run) we need to know the base url for oauth
base_url = "https://preprod-xxxxx"
```
But got the 
![image](https://github.com/Chainlit/chainlit/assets/18211419/aec8731f-d750-4b5d-9940-8a87e165d5c5)

**Comment by willydouhard** [comment]
Did you update to `0.7.2`? In that case the `config.ui.base_url` has been moved to an environment variable named `CHAINLIT_URL`.

**Comment by wxp16** [comment]
I checked the updated documentaion  and set CHAINLIT_URL. All works as expected. So closed this isue.
