### ISSUE TITLE
LaTex support

### ISSUE THREAD

**Issue by KulikDM** [Chainlit/chainlit#471]
Hi, great app.

I've tested the element Text class and it works well with Markdown. However, when I have equations in the Markdown string that are LaTex format it does not render the equations. This functionality would be a great addition to this library.

Much appreciated.

**Comment by willydouhard** [comment]
Thank you, opened to contributions on this one. We currently use ReactMarkdown and remarkGfm. There might be an out of the box plugin for LaTex.

**Comment by KulikDM** [comment]
Hi @willydouhard appreciate the speedy response. There are actually a few possible options remark-math, react-katex, react-mathjax. Perhaps one these could be employed? Here is a nice simple example of its use https://medium.com/@MatDrinksTea/rendering-markdown-and-latex-in-react-dec355e74119

**Comment by KulikDM** [comment]
Hi @willydouhard appreciate the speedy response. There are actually a few possible options remark-math, react-katex, react-mathjax. Perhaps one these could be employed? Here is a nice simple example of its use https://medium.com/@MatDrinksTea/rendering-markdown-and-latex-in-react-dec355e74119

**Comment by KulikDM** [comment]
Hi @willydouhard any updates on this?

**Comment by ventz** [comment]
Having LaTeX would be fantastic!
(per @KulikDM link - it seems incredibly easy to implement)

More and more answers from the LLMs are coming back as LaTeX
There is a big difference between seeing

## This:

![image](https://github.com/Chainlit/chainlit/assets/901168/0cfcd84a-9c2b-43d3-b706-0ecc545d23a8)

## vs This

![image](https://github.com/Chainlit/chainlit/assets/901168/002f0173-90a9-4017-9404-b4291225ba8e)

**Comment by willydouhard** [comment]
Will try to add it in the next release.

**Comment by ventz** [comment]
Thank you!

**Comment by willydouhard** [comment]
See https://github.com/Chainlit/cookbook/issues/40. We will only support the `$$` notation.

**Comment by ventz** [comment]
@willydouhard This is great!
Let us know when the RC is built and would be more than happy to test if helpful.

I have a version already with the new OpenAI Assistant API, so that's where we are seeing a lot of this return.

**Comment by willydouhard** [comment]
It is already released! `pip install --pre chainlit`

**Comment by ventz** [comment]
Just deployed.

Just FYI - noticed the `copy` block is not copying the text, but instead getting `undefined`
<img width="852" alt="image" src="https://github.com/Chainlit/chainlit/assets/901168/588c4b61-1f82-4883-abd1-e71323329f87">

One question - any plans to support the more modern notations?

Seeing:
> using the $$ method to initiate and terminate display-math mode in LaTeX documents is nowadays heavily deprecated

Also, it seems the $$ notation would not fix the output from OpenAI's GPT4/GPT4-turbo/Code Interpreter/etc.

**Comment by willydouhard** [comment]
Will fix the copy block. For the notation this is tricky, react-markdown is not supporting it.

**Comment by ventz** [comment]
I was just looking, and it seems this may be the right package for the formulas: https://github.com/SamyPesse/react-mathjax#readme

But for the multi notions, it seems `react-katex` is the way to go? https://www.npmjs.com/package/react-katex

(this may be of interest too: https://npmtrends.com/latex-vs-react-katex-vs-react-latex-vs-react-mathlive-vs-react-mathquill)

**Comment by willydouhard** [comment]
We are currently using katex. However the issue is more about how markdown is parsed. The issue is not to only have a latex parser, but to make it work with the reste of the markdown.

**Comment by willydouhard** [comment]
@ventz One trick I use to make it work with code interpreter is to prompt it to use the $$ notation. Example [here](https://github.com/Chainlit/cookbook/blob/main/openai-assistant/create_assistant.py#L17).

**Comment by ventz** [comment]
@willydouhard Thats really smart!! Thanks for sharing it!

**Comment by ventz** [comment]
For some reason I am only getting it on the input:

<img width="787" alt="image" src="https://github.com/Chainlit/chainlit/assets/901168/55b4e882-dcd4-412e-b337-33844eae0d2b">

Where it gets curious is that if you pre-prompt the run threads run creation, then you get one more level, but not all:

<img width="825" alt="image" src="https://github.com/Chainlit/chainlit/assets/901168/769283cf-b3d3-4cc1-9768-a4079e414f2c">

**Comment by barun-saha** [comment]
Hi Willy,

I have some LaTex equations added in the `chainlit.md` file. However, when I run the app, the readme section does not render the LaTex code:

![image](https://github.com/Chainlit/chainlit/assets/3896258/8deac88e-0d1a-420e-bb3f-327a836be40f)

As you can see, I tried enclosing them using both single and double $ symbols. However, the raw text is displayed as it is. The LaTex setting is also enabled in `chainlit.toml`:
```
# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = true
```

Do I need to add/install anything more? I'm using Chainlit v0.7.700.

Thanks for your time.

**Comment by willydouhard** [comment]
Latex support is now disabled by default, you can enable it in your [config.toml file ](https://docs.chainlit.io/backend/config/features).
