### ISSUE TITLE
how to add thumb up/down icon on the Chainlit UI to collect users' feedbck?

### ISSUE THREAD

**Issue by wxp16** [Chainlit/chainlit#472]
not sure if Chainlit has this feauter or not. If yes, doesn anyone know how ?

**Comment by willydouhard** [comment]
https://docs.chainlit.io/chat-data/feedback

**Comment by wxp16** [comment]
hello @willydouhard  Regarding the data persistence, how to deploy in a coporate GCP enviroment? FYI, We are able to deploy our own postsql database. Any otherthing we need to do?

**Comment by willydouhard** [comment]
If you don't want to use the [SaaS](https://cloud.chainlit.io/), you will have to fill the [enterprise form](https://forms.gle/BX3UNBLmTF75KgZVA) to get access to the commercial docker image.
