### ISSUE TITLE
Enable previous chats to be continued

### ISSUE THREAD

**Issue by jimmarshall87** [Chainlit/chainlit#475]
Undoubtedly the Chat History is a great addition to the product!

However, it misses one crucial feature that ChatGPT has which is the ability to continue from where you left off. As far as I can tell, at present, you can use it to view old chats, but not continue them?

This would be a nice improvement.

**Comment by willydouhard** [comment]
We were discussing this with @MathiasSpanhove. We could add an `cl.on_chat_resume` callback with all the history as a parameter. It would then be  up to the developer to reset the user session in the right state.

**Comment by willydouhard** [comment]
Added in chainlit `0.7.500`! See the [docs](https://docs.chainlit.io/chat-data/history).
