### ISSUE TITLE
How can we change the name of the text on the new chat button ("+ New Chat") to a different text? (In the chainlit open-source Python package)

### ISSUE THREAD

**Issue by Byusa** [Chainlit/chainlit#477]
How can we change the name of the text on the new chat button ("+ New Chat") to a different text?
In the chainlit open-source Python package

**Comment by willydouhard** [comment]
Currently we do not provide this level of customisation. You can fork the UI and bundle it yourself. The[ contributing guide](https://github.com/Chainlit/chainlit/blob/main/.github/CONTRIBUTING.md) is a good place to start!

**Comment by Byusa** [comment]
> Currently we do not provide this level of customisation. You can fork the UI and bundle it yourself. The[ contributing guide](https://github.com/Chainlit/chainlit/blob/main/.github/CONTRIBUTING.md) is a good place to start!
Thank you. 
Another quick question, can you help answering this question too?
https://github.com/Chainlit/chainlit/issues/476
