### ISSUE TITLE
Initialize chat from messages?

### ISSUE THREAD

**Issue by GabeDottl** [Chainlit/chainlit#478]
It'd be super useful if one could initialize a chat or rewrite a chat from a list of messages. E.g. to support loading chats from memory, replacing a chat in place, pre-filling a chat with starting conversation

**Comment by willydouhard** [comment]
I am not sure what you exactly mean by that. You can already pre-fill a conversation by sending message in `on_chat_start` or update existing message with `cl.Message().update()`. Can you provide an example of what you have in mind that is not possible as of today?
