### ISSUE TITLE
Chat settings with dynamic InputWidget

### ISSUE THREAD

**Issue by Ru13en** [Chainlit/chainlit#482]
Hi,
I am trying this awesome tool, but I feel that is lacking the possibility to have a dynamic form in the Chat settings.
I would like to hide, show or modify visual InputWidgets depending of other InputWidget options.

For instance I would like to have an Switch InputWidget with the label "Advanced options" and depending of True or False, it hides or shows other InputWidgets in its group.
Or other excellent option would be to have a Select InputWidget that shows/hides a group of InputWidgets and even sets the initial value of certain InputWidget depending on the selected option.

Thank you for this awesome tool.
BR

**Comment by JCF-SES** [comment]
What I understood you want to do can be achieved in current version. Here is an example of how I interpreted it.

```python
import chainlit as cl


@cl.on_chat_start
async def chat_start():
    # noinspection PyArgumentList
    await cl.ChatSettings([cl.input_widget.Switch(id='advanced-settings',
                                                  label='Advanced Settings',
                                                  initial=False)]).send()


@cl.on_settings_update
async def update_settings(settings: dict[str, str]):
    if settings.get("advanced-settings"):
        # noinspection PyArgumentList
        await cl.ChatSettings([cl.input_widget.Switch(id='advanced-settings',
                                                      label='Advanced Settings',
                                                      initial=True),
                               cl.input_widget.Switch(id='new-settings',
                                                      label='New Advanced Settings',
                                                      initial=True)]).send()
    else:
        # Add this to revert back to default state
        # noinspection PyArgumentList
        await cl.ChatSettings([cl.input_widget.Switch(id='advanced-settings',
                                                      label='Advanced Settings',
                                                      initial=False)]).send()

```

The approach is basically to create the chat setting and if it's modified, modify all chat settings available to the user back and forth.

You could go crazier with the logic by checking what is available for [input widgets](https://docs.chainlit.io/api-reference/chat-settings).

Hope that helped.

**Comment by Ru13en** [comment]
Thank you for this excellent example, this is a good workaround for the issue.

However, I would like to have the form reactive, so it means that if I click in the switch button, it automatically shows or hides the other input widgets that could be hidden or shown by the group without needing to close and open the settings.

Something like having a @cl.on_settings_interaction, and then I can apply logic to modify the ChatSettings on the fly without clicking in the confirm button.

**Comment by willydouhard** [comment]
Thank you @JCF-SES for this great example! Interaction callback is not planned on the short term @Ru13en, we are opened to contributions on this however.
