### ISSUE TITLE
Chat History with long(ish) prompts means the Chat History dialog cannot be closed on mobile

### ISSUE THREAD

**Issue by jimmarshall87** [Chainlit/chainlit#483]
Thought the latest updates in 0.7.3 might fix this as I saw you had done some work on the mobile UX, but on mobile, once opened, the Chat History fills the screen and there is no way of closing it on iPhone 14 (at least). Many of the prompts I have in the Chat History window are quite long so extend beyond width of the screen so I think that is what is causing the issue - they either need to wrap or be truncated I think?

**Comment by willydouhard** [comment]
Good catch, going to release a patch for this.

**Comment by willydouhard** [comment]
Should be fixed with the latest release

**Comment by jimmarshall87** [comment]
nice one! Will try soon.
