### ISSUE TITLE
streaming image issue on a k8s service

### ISSUE THREAD

**Issue by monaxu1** [Chainlit/chainlit#494]
I was using the method recommended [here](https://docs.chainlit.io/api-reference/elements/image) for sending image bytes to chainlit. It works fine in localhost, but when the application gets deployed in a k8s service and the service gets exposed to users, the image cannot be displayed (although it could be downloaded via the image icon). There is also a link or ID provided for the plot which cannot be used either.

Do you have any idea on how to display the image from a k8s service?

```
elements = [
            cl.Image(name="image1", display="inline", content=image_data)
        ]
await cl.Message(content=message, elements=elements).send()
```
<img width="876" alt="Screenshot 2023-10-20 at 15 58 45" src="https://github.com/Chainlit/chainlit/assets/77111135/93cbd9cc-be34-4453-ab4a-b34655fbedde">
<img width="876" alt="Screenshot 2023-10-20 at 16 01 40" src="https://github.com/Chainlit/chainlit/assets/77111135/0b277b05-caf3-4854-998f-7674b05d4e19">

**Comment by willydouhard** [comment]
Interesting, I wonder what is the difference between sending bytes from localhost and from a k8s cluster. Not obvious to me.
