### ISSUE TITLE
HTML support in Markdown

### ISSUE THREAD

**Issue by hayescode** [Chainlit/chainlit#495]
The root and ReadMe page in the app displays the `chainlit.md` file which I can edit just fine, but it would be nice if the markdown viewer used supported HTML to allow for greater customization and a polished look. I understand HTML in markdown has security considerations so maybe the necessary package could be a boolean setting that is off by default?

**Comment by willydouhard** [comment]
Yes, we will probably add this down the line (behind a security flag). Can't commit on a date though. Opened to contributions!
