### ISSUE TITLE
Update the Twitter logo to X

### ISSUE THREAD

**Issue by Kaushik080** [Chainlit/chainlit#497]
To Reproduce -
Go to the footer of the website.

In the current version of the website the logo of Twitter is not updated.
![image](https://github.com/Chainlit/chainlit/assets/120493528/c98bb4fe-3052-459a-b098-1168f479335d)

**Comment by Kaushik080** [comment]
I would like to work on this, please assign me this issue

**Comment by ModEnter** [comment]
Hello, I'm closing this issue as it has been fixed
