### ISSUE TITLE
Integrate multiple workflows as tabs or subpaths

### ISSUE THREAD

**Issue by michaelfeil** [Chainlit/chainlit#5]
![image](https://github.com/Chainlit/chainlit/assets/63565275/c0a783f0-f1d3-4268-a6b5-e5c5fa427297)

Idea:
- have multiple chains / workflows running side-by-side

one tab could then be 
- Q&A
- one could be Google Query
- Image Generation with DallE

This would enable also rapid prototyping and side-by-side testing of two versions, without running them in two different containers.

Please add tag:
- enchancement

**Comment by ibicdev** [comment]
Any update on this?  Does the PR above add this feature?

**Comment by ordenador** [comment]
What happened to this feature? I have been following it for a long time. Nowadays, there are many capabilities and I would like to have them all in one place.

**Comment by willydouhard** [comment]
I don't think so, the best way to achieve this atm is to use [chat profiles](https://docs.chainlit.io/advanced-features/chat-profiles)

**Comment by konradbjk** [comment]
I still would like to see - similar to "Compare" function in OpenAI Playground. I do chat profiles, but those do not run in parallel
