### ISSUE TITLE
Setting up the chainlit environment locally

### ISSUE THREAD

**Issue by Cenrax** [Chainlit/chainlit#50]
<img width="664" alt="image" src="https://github.com/Chainlit/chainlit/assets/43017632/78323c30-5c63-4426-a996-230cb78e2863">
It says to run chainlit run target.py -h 

But in the folder there is no such file and it gives an error while running

**Comment by willydouhard** [comment]
`target.py` here would be your own file with your own app code depending on what you want to build. The guide you are following is to install Chainlit from sources. Once it is installed it is up to you to build your app with Chainlit!
