### ISSUE TITLE
Table does not parse correctly if there is a title above it.

### ISSUE THREAD

**Issue by entron** [Chainlit/chainlit#503]
I am using the latest version and the following code to test:

```
@cl.on_chat_start
async def main():
    msg = """Table 1 
    | heading | b  |  c |  d  |
  | - | :- | -: | :-: |
  | cell 1 | cell 2 | 3 | 4 |
"""
    await cl.Message(content=msg).send()
```

The output is not parsed as a table:

```
Table 1
| heading | b  |  c |  d  |
| - | :- | -: | :-: |
| cell 1 | cell 2 | 3 | 4 |
```

Another maybe related problem is if there is markdown list inside a cell. This list will not be parsed either.

**Comment by willydouhard** [comment]
I am able to reproduce with your example. However this works

```py
import chainlit as cl


@cl.on_chat_start
async def main():
    msg = """
  Hello
  | heading | b  |  c |  d  |
  | - | :- | -: | :-: |
  | cell 1 | cell 2 | 3 | 4 | """
    await cl.Message(content=msg).send()
```
<img width="681" alt="Screenshot 2023-10-25 at 10 37 20" src="https://github.com/Chainlit/chainlit/assets/13104895/e8d55438-8fe0-41d6-9759-71a093def034">


Looks like indentation is important.

**Comment by entron** [comment]
Interesting. The problem is the table and text above and below it are generated by LLM and I can not easily control indentation. Is it possible we make the table parsing more robust?

**Comment by willydouhard** [comment]
That is a good question. We use [remark-gfm](https://github.com/remarkjs/remark-gfm) to parse markdown tables. Would have to dig into that.

**Comment by entron** [comment]
Do you know what does ChatGPT and Gradio use? At least ChatGPT can produce beatiful tables robustly.
