### ISSUE TITLE
Support OpenAI functions natively in the prompt playground

### ISSUE THREAD

**Issue by kevinwmerritt** [Chainlit/chainlit#509]
**Problem:** The prompt playground UI doesn't allow you to edit OpenAI function calls.

**Solution:** Include function calling as part of the Prompt Playground UI.

Examples of prompt designers that support OpenAI function calls:
- https://langtail.com/
- https://promptknit.com/

For many use cases it is simpler and more explicit to prompt OpenAI directly with function calls then it is to introduce other packages like LangChain. The ability to visualize function definitions within the Prompt Playground would be a huge benefit of using Chainlit.

**Comment by willydouhard** [comment]
This commit is adding support for functions https://github.com/Chainlit/chainlit/pull/518/commits/43668eed01a917776be530b45afc76376f3c2c80
