### ISSUE TITLE
After running the chainlit run app.py getting the error "Could not reach the server"

### ISSUE THREAD

**Issue by Cenrax** [Chainlit/chainlit#51]
Platform : Windows 11

1. Installed the chainlit from
- Download the [wheel](https://chainlit-cloud.s3.eu-west-3.amazonaws.com/dev-release/chainlit-0.3.0-py3-none-any.whl)
- Run pip uninstall chainlit
- Run pip install PATH_TO_WHEEL
2. After that getting the error:
```
2023-06-11 19:29:28 - Module should at least expose one of @langchain_factory, @on_message or @on_chat_start function
```

**Comment by willydouhard** [comment]
yes, a chainlit app should at lease expose one of those. for instance:

```py
import chainlit as cl

@cl.on_message
async def main(message: str):
   await cl.Message(content=message).send()
```

Is a minimal example

**Comment by Cenrax** [comment]
Hey @willydouhard. Yup that works but I have a followup question regarding the following example in https://docs.chainlit.io/examples/qa

This is not working and it is showing the same error,
```
Module should at least expose one of @langchain_factory, @on_message or @on_chat_start function
```

Even though the code has @langchain_factory function
