### ISSUE TITLE
Login Page: Input Email Only

### ISSUE THREAD

**Issue by darylmoodys** [Chainlit/chainlit#513]
Exploring a use case where users need to only input an email (no password) before using the web app. 

Can't seem to find any configurables to remove the "Password" text field. I have tried brute-forcing by using custom CSS to hide the "Password" text field and also specifying @cl.password_auth_callback to not check any passwords before returning an AppUser.

```
div[class = 'MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-adornedEnd css-19ntyi6']{
    visibility: hidden;
}
```

```
@cl.password_auth_callback
def auth_callback(username: str, password: str) -> Optional[cl.AppUser]:
  return cl.AppUser(username=username, role="USER", provider="credentials")
```

However, the form submission requires some password inputs into the field before submission. (screenshot below)

Would love some advice as to whether such a behaviour (to input email only) on the web app would be possible. Thank you!

<img width="290" alt="image" src="https://github.com/Chainlit/chainlit/assets/110436080/deb441a6-a6b3-474d-b578-a315ed625f09">

**Comment by willydouhard** [comment]
Interesting, did not think of that possibility. We can make the password optional. This would only be a UI change since the real validation happens in the python code and you can already ignore the password if you want to. Opened to contributions!
