### ISSUE TITLE
How to display Unicode encoded strings as Chinese characters？

### ISSUE THREAD

**Issue by miandai** [Chainlit/chainlit#514]
![image](https://github.com/Chainlit/chainlit/assets/4371622/714f8dfe-23ff-4f9d-bb60-d505c86ed799)

**Comment by willydouhard** [comment]
Will look into it!

**Comment by willydouhard** [comment]
Should be fixed with chainlit `0.7.500`!

**Comment by samosun** [comment]
<img width="892" height="542" alt="Image" src="https://github.com/user-attachments/assets/855bc980-dede-4e9f-b0de-5d2b714da176" />

this issue recurs in chainlit 2.7.2
