### ISSUE TITLE
Issue in uploading a .docx file and saving the same 

### ISSUE THREAD

**Issue by amani-acog** [Chainlit/chainlit#516]
I am running chainlit in a docker container and I have an issue while uploading .docx files. As my task needs to save the docx file and process on it which needs styles to be preserved. So I am using following python code to do that

```
import chainlit as cl
from docx import Document
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

def copy_docx_with_styles(input_file, output_file):
    doc = Document(input_file)

    # Create a new Document to copy the styles
    new_doc = Document()

    for paragraph in doc.paragraphs:
        new_paragraph = new_doc.add_paragraph()
        new_paragraph.alignment = paragraph.alignment
        for run in paragraph.runs:
            new_run = new_paragraph.add_run(run.text)
            new_run.bold = run.bold
            new_run.italic = run.italic
            new_run.underline = run.underline
            new_run.font.size = run.font.size
            new_run.font.name = run.font.name

    new_doc.save(output_file)


@cl.on_chat_start
async def start():
    file1 = None

    # Wait for the user to upload a file
    while file1 == None:
        file1 = await cl.AskFileMessage(
            content="Please upload a text file to begin!", accept={"text/plain": [".docx"]}, max_files=1
        ).send()
    # Decode the file
    text_file = file1[0]
    op_file = copy_docx_with_styles(text_file, "temp1.docx")
    # text = text_file.content.decode()

    # Let the user know that the system is ready
    await cl.Message(
        content=f"`{text_file.name}` uploaded, it is saved as {op_file} characters!"
    ).send()
```
But I am facing error as:
```
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/biogen-bddN00OR-py3.11/lib/python3.11/site-packages/chainlit/utils.py", line 39, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/biogen/biogen/chainlit/app.py", line 50, in start
    op_file = copy_docx_with_styles(text_file, "temp1.docx")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/biogen/biogen/chainlit/app.py", line 20, in copy_docx_with_styles
    doc = Document(input_file)
          ^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/biogen-bddN00OR-py3.11/lib/python3.11/site-packages/docx/api.py", line 23, in Document
    document_part = Package.open(docx).main_document_part
                    ^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/biogen-bddN00OR-py3.11/lib/python3.11/site-packages/docx/opc/package.py", line 116, in open
    pkg_reader = PackageReader.from_file(pkg_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/biogen-bddN00OR-py3.11/lib/python3.11/site-packages/docx/opc/pkgreader.py", line 22, in from_file
    phys_reader = PhysPkgReader(pkg_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/biogen-bddN00OR-py3.11/lib/python3.11/site-packages/docx/opc/phys_pkg.py", line 76, in __init__
    self._zipf = ZipFile(pkg_file, "r")
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/zipfile.py", line 1301, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.11/zipfile.py", line 1364, in _RealGetContents
    endrec = _EndRecData(fp)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/zipfile.py", line 292, in _EndRecData
    fpin.seek(0, 2)
    ^^^^^^^^^
AttributeError: 'AskFileResponse' object has no attribute 'seek'

```
Please help or fix issue...

**Comment by willydouhard** [comment]
`text_file` is a `AskFileResponse` which is a chainlit abstraction. You probably need to process the bytes of the file (which you can access with `text_file.content` instead of the `AskFileResponse`.

**Comment by amani-acog** [comment]
I want to save the content of docx file along with the styles used. So I cannot use text_file.content alone

**Comment by willydouhard** [comment]
I don't understand why. Content is not the string content of the file, it is the actual bytes of the file. If you were to save it on your disk and open it again with word, you should see the same file.

**Comment by vivekjainmaiet** [comment]
@amani-acog Is your issue resolved ? Are you able to save user uploaded file to docker container locally for further processing. Please share code as i am also facing same issue.

**Comment by amani-acog** [comment]
Create a new file in 'wb' mode and write the content to the file.

With open('a.txt', 'wb') as f:
      f.write(binary_content)

**Comment by vivekjainmaiet** [comment]
How to get binary_content of uploaded file ? could you correct in your code below "import chainlit as cl
from docx import Document
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

def copy_docx_with_styles(input_file, output_file):
    doc = Document(input_file)

    # Create a new Document to copy the styles
    new_doc = Document()

    for paragraph in doc.paragraphs:
        new_paragraph = new_doc.add_paragraph()
        new_paragraph.alignment = paragraph.alignment
        for run in paragraph.runs:
            new_run = new_paragraph.add_run(run.text)
            new_run.bold = run.bold
            new_run.italic = run.italic
            new_run.underline = run.underline
            new_run.font.size = run.font.size
            new_run.font.name = run.font.name

    new_doc.save(output_file)


@cl.on_chat_start
async def start():
    file1 = None

    # Wait for the user to upload a file
    while file1 == None:
        file1 = await cl.AskFileMessage(
            content="Please upload a text file to begin!", accept={"text/plain": [".docx"]}, max_files=1
        ).send()
    # Decode the file
    text_file = file1[0]
    op_file = copy_docx_with_styles(text_file, "temp1.docx")
    # text = text_file.content.decode()

    # Let the user know that the system is ready
    await cl.Message(
        content=f"`{text_file.name}` uploaded, it is saved as {op_file} characters!"
    ).send()"

**Comment by amani-acog** [comment]
# Wait for the user to upload a file
while file1 == None:
    file1 = await cl.AskFileMessage(
        content="Please upload a text file to begin!", accept={"text/plain": [".docx"]}, max_files=1
    ).send()
# Decode the file
text_file = file1[0]
text = text_file.content # this is binary type of content
# save this 'text' in a file as above said way

**Comment by vivekjainmaiet** [comment]
@amani-acog Which version of python and chainlit are you using. I am getting error AttributeError: 'AskFileResponse' object has no attribute 'content'

text = text_file.content # this is binary type of content
           ^^^^^^^^^^^^^^^^^
AttributeError: 'AskFileResponse' object has no attribute 'content'.

**Comment by vivekjainmaiet** [comment]
@willydouhard I am using latest version of chainlit and i am not able to access file path on docker , it is giving only document name. I am using code provided in example of chainlit document. Could you please help link https://docs.chainlit.io/api-reference/ask/ask-for-file

#code
`import chainlit as cl


@cl.on_chat_start
async def start():
    files = None

    # Wait for the user to upload a file
    while files == None:
        files = await cl.AskFileMessage(
            content="Please upload a text file to begin!", accept=["text/plain"]
        ).send()

    text_file = files[0]

    with open(text_file.path, "r", encoding="utf-8") as f:
        text = f.read()

    # Let the user know that the system is ready
    await cl.Message(
        content=f"`{text_file.name}` uploaded, it contains {len(text)} characters!"
    ).send()

`

**Comment by willydouhard** [comment]
Does your setup allow for chainlit to write to the docker volume? Chainlit persist to disk the uploaded files while the session is running.
