### ISSUE TITLE
Segmentation fault on parallel requests with chainlit cache

### ISSUE THREAD

**Issue by okabe-sama** [Chainlit/chainlit#519]
I am trying to set up a RAG application with langchain - FAISS vector store, LlamaCpp model. I have attached a dummy code snippet to reproduce the error.

The below code works fine (i.e. uses cached vector store and LLM) when I open two sessions from different tabs and send messages **one after the other**, i.e. send message from tab1, wait for response, then send message from tab2.

However, when I send the messages **simultaneously**, i.e. send message from tab1 and tab2 without waiting, segmentation fault occurs and the server shuts down.

**Code snippet:**
```
import chainlit as cl
from langchain.vectorstores import FAISS
from langchain.llms import LlamaCpp
from langchain.chains import RetrievalQA,

@cl.cache
def load_vectorstore():
   # load and return the vectorstore using FAISS
   return vstore


@cl.cache
def load_llm():
   # load and return the LLM using LlamaCpp
   return llm

def create_chain():
   db = load_vectorstore()
   llm = load_llm()
   chain = RetrievalQA.from_chain_type(llm=llm, retriever=db.as_retriever())
   return chain

@cl.on_chat_start
async def start():
   chain = create_chain()
   cl.user_session.set("chain", chain)

@cl.on_message
async def main(message):
   chain = cl.user_session.get("chain")
   answer = await cl.make_async(chain)(message)
   await cl.Message(content=answer).send()
```

**Things I have already tried to avoid the error and failed**:

1. Using CTransformers instead of LlamaCpp
2. Using **@cl.cache** decorator on `create_chain()` instead of the load functions
3. Loading the vector store and LLM as global variables (after the imports) and using them in `create_chain()` without the cache decorator.

**Version details:**
```
OS: Ubuntu 22.04
Python: 3.8.10
Packages:
chainlit==0.7.0
langchain==0.0.317
```

Ignore typos and indentation errors (if any).

**Comment by okabe-sama** [comment]
I don't think that is the case because:

a. without using the chainlit cache decorator, the machine was able to handle up to three parallel sessions, i.e. loading the vector store and model three times in-memory and executing three inferences at a time. At initiating the fourth session, the memory got exhausted and chainlit process was killed.

b. for a different application, I am using a FastAPI backend which loads the model (different model, different wrappers) only once and handles multiple inferences asynchronously (using asyncio under the hood). It works fine on the same machine.

**Comment by willydouhard** [comment]
I see, do you pass any argument to the load_llm function? You do not in your code snippet but maybe you simplified the code before posting it.

**Comment by okabe-sama** [comment]
No I don't. The params are static and are hard-coded in the constructor call within the function. Same is the case with vectorstore.

**Comment by willydouhard** [comment]
I fail to understand why it is happening. This small example works as expected on my machine:
```py
import chainlit as cl


@cl.cache
def get_llm():
    print("CALLED")
    return {}


def create_chain():
    llm = get_llm()
    return llm


@cl.on_chat_start
def foo():
    foo = create_chain()
    bar = create_chain()
    print(foo == bar)
```

### Output

```
CALLED
True
```

The `get_llm` function is called once and the dict is correctly cached (as the ref equality check returns True).

**Comment by willydouhard** [comment]
Actually maybe the issue is that it takes a long time to load the llm in the first place. If you try to access it again while it is still instantiating but not yet cached that might be the issue.

**Comment by willydouhard** [comment]
Can you try to change your code to 
```py
@cl.cache
def load_llm():
   # load and return the LLM using LlamaCpp
   return llm

llm = load_llm()

def create_chain():
   db = load_vectorstore()
   chain = RetrievalQA.from_chain_type(llm=llm, retriever=db.as_retriever())
   return chain
   ```
   
   This will load the llm once but the application will not start until the llm is actually loaded.

**Comment by okabe-sama** [comment]
The `create_chain` is a blocking call and the application doesn't start until the LLM is actually loaded, I've confirmed that. You are also right about cache dict working fine. As mentioned earlier, 

> The below code works fine (i.e. uses cached vector store and LLM) when I open two sessions from different tabs and send messages one after the other, i.e. send message from tab1, wait for response, then send message from tab2.

The issue occurs when multiple threads try to access the cached object (llama_cpp model) simultaneously. I do not understand why parallel read-only accesses would cause segmentation fault.

**Comment by okabe-sama** [comment]
I think the issue might be either in llama_cpp object or in my use of it. I noticed that the vector store retrieval works fine for cached objects, so there's no issue with chainlit as far as I can think. Thanks for looking into it and the prompt responses @willydouhard :)

**Comment by everyfin-in** [comment]
@okabe-sama Did you manage to solve this issue? I have the exact same issue with Chainlit and llama_cpp. I get segmentation fault when multiple threads try and access the llama_cpp cached model.

**Comment by gutmmm** [comment]
Have te same problem with Llamacpp and Chainlit getting - `Segmentation fault (core dumped)`
