### ISSUE TITLE
Serve chainlit app from a subdirectory

### ISSUE THREAD

**Issue by ArthurJahn** [Chainlit/chainlit#521]
The docs says that

> "Currently, you have to serve your Chainlit app from the root of your domain/subdomain. This means that you can’t serve it from a subdirectory like example.com/my-app."

So, I'd like to be able to serve the app from different base path, like setting a [base tag](https://www.w3schools.com/tags/tag_base.asp) or something.

**Comment by willydouhard** [comment]
Yes this is a current limitation. Setting a subdomain and serving the app from the subdomain root is not an option for you?

**Comment by ArthurJahn** [comment]
Yes, we can mitigate that way, but a best solution for us would be to serve the app from a subdir. I can work on that if you guys think it's a nice feature to be added and if there is no known limitations to develop that feature.

**Comment by willydouhard** [comment]
Would love contributions on that topic! I don't think we have any particular requirements except for the http endpoints to work correctly (maybe also oauth redirections). We do have the concept of [CHAINLIT_URL ](https://docs.chainlit.io/authentication/oauth)already to help with tricky oauth redirections.

**Comment by AllenJShi** [comment]
Encountered similar issue - tried run the app at root directory but still displayed empty screen.
