### ISSUE TITLE
Callback handles UTF-8 characters incorrectly

### ISSUE THREAD

**Issue by Enoch2090** [Chainlit/chainlit#525]
When calling a LangChain runnable such as

```Python
runnable.astream(
        {'question': message.content},
        config=RunnableConfig(callbacks=[cl.LangchainCallbackHandler(stream_final_answer=True)]),
    )
```

The UTF-8 characters (such as Chinese characters) are output as:

![msedge_November06-18-15-213b39](https://github.com/Chainlit/chainlit/assets/47914326/d1e7e281-7b8a-437c-bd25-ed51edac6c3e)

Haven't read the source code of Chainlit, I suspect this could be caused by simply dumping the intermediate results with json. Can 100% replicate this with any intermediate results with Chinese language.

**Comment by willydouhard** [comment]
Should be fixed with chainlit `0.7.500`!

**Comment by Enoch2090** [comment]
Updated to `0.7.500` and it is fixed. Thanks!

**Comment by samosun** [comment]
<img width="1664" height="320" alt="Image" src="https://github.com/user-attachments/assets/f900b515-6077-4145-8b05-eb9b64a42304" />

this issue reccurs in chainlit=2.7.2 @Enoch2090
