### ISSUE TITLE
Use of auth0 when auth0 has been configured with a custom domain throws a Service Not Found error

### ISSUE THREAD

**Issue by DBairdME** [Chainlit/chainlit#531]
Hi, I'm using auth0 as the authentication provider for a Chainlit test and note that when I set the OAUTH_AUTH0_DOMAIN to be the custom domain that is defined within Auth0, Chainlit throws a "Service not found" relating to the "audience=https://OAUTH_AUTH0_DOMAIN" query being sent in the authentication request.

A review of the Auth0 site re. custom domains and use of "audience" notes that this is a known issue - see https://auth0.com/docs/troubleshoot/integration-extensibility-issues/troubleshoot-custom-domains for details.

The use of a custom domain in Auth0 would be preferred as this means that users are accessing the auth service at a well-known FQDN (it's a CNAME of the Auth0 defined FQDN).

A possible workaround (as per https://github.com/auth0/node-auth0/issues/292) is noted, with this being to include a second environment variable that uses the auth0 domain for the audience query. This would allow the users still see the Auth0 site as being from the custom domain name, but then have the audience query be processed by the actual Auth0 domain itself.

Is this something that the Chainlit team would look to include to better support Auth0 integration?

Many thanks

**Comment by willydouhard** [comment]
Hi, thank you for your report!

Can you go change[ that line](https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/oauth_providers.py#L308) in your local chainlit installation to:

```py
            "audience": f"YOUR_ORIGINAL_DOMAIN/userinfo",
```
Then restart your chainlit app and try again. If that fixes the issue I will create a PR.

To find your local chainlit installation run `pip show chainlit`.

**Comment by DBairdME** [comment]
Hi, that change has been tested in a lab environment, with the changes in bold made to allow the use of the actual Auth0 authentication domain (it will end in auth0.com).

This new variable should then be added to the local .env file as needed.


class Auth0OAuthProvider(OAuthProvider):
    id = "auth0"
    env = ["OAUTH_AUTH0_CLIENT_ID", "OAUTH_AUTH0_CLIENT_SECRET", "OAUTH_AUTH0_DOMAIN"**, "OAUTH_AUTH0_ORIGINAL_DOMAIN"**]

    def __init__(self):
        self.client_id = os.environ.get("OAUTH_AUTH0_CLIENT_ID")
        self.client_secret = os.environ.get("OAUTH_AUTH0_CLIENT_SECRET")
        # Ensure that the domain does not have a trailing slash
        self.domain = f"https://{os.environ.get('OAUTH_AUTH0_DOMAIN', '').rstrip('/')}"
        **self.original_domain = f"https://{os.environ.get('OAUTH_AUTH0_ORIGINAL_DOMAIN', '').rstrip('/')}"**
        
        self.authorize_url = f"{self.domain}/authorize"

        self.authorize_params = {
            "response_type": "code",
            "scope": "openid profile email",
            "audience": f"{self.**original_domain**}/userinfo",
        }

    async def get_token(self, code: str, url: str):
        payload = {
            "client_id": self.client_id,
            "client_secret": self.client_secret,
            "code": code,
            "grant_type": "authorization_code",
            "redirect_uri": url,
        }
        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"{self.domain}/oauth/token",
                data=payload,
            )
            response.raise_for_status()
            json_content = response.json()
            token = json_content.get("access_token")
            if not token:
                raise HTTPException(
                    status_code=400, detail="Failed to get the access token"
                )
            return token

    async def get_user_info(self, token: str):
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"{self.**original_domain**}/userinfo",
                headers={"Authorization": f"Bearer {token}"},
            )
            response.raise_for_status()
            user = response.json()
            app_user = AppUser(
                username=user.get("email"),
                image=user.get("picture", ""),
                provider="auth0",
            )
            return (user, app_user)

**Comment by willydouhard** [comment]
Thank you for your report! Will create the PR to add it.

**Comment by willydouhard** [comment]
https://github.com/Chainlit/chainlit/pull/541

**Comment by willydouhard** [comment]
Available in the latest release `0.7.602`
