### ISSUE TITLE
Using the Access toke in app

### ISSUE THREAD

**Issue by JayRHa** [Chainlit/chainlit#537]
I building an app with EntraId authentication but I want to use the Access token in the app to do also some transactions agains MS Graph. Is the auth token somewhere saved?

**Comment by willydouhard** [comment]
You have access to the token in the [oauth_callback](https://docs.chainlit.io/authentication/oauth#change-the-username-to-the-email). There you can store the token in the `user_session` to re use it later.

**Comment by JayRHa** [comment]
But how can I change which scope is claimed. Currently it is only user

**Comment by willydouhard** [comment]
Currently not possible but this can be a config option of the oauth_callback, opened to contributions!

**Comment by JayRHa** [comment]
Added this functionality and created pull request

**Comment by willydouhard** [comment]
This will be added in the 1.0.0 release. A metadata field in AppUser will be introduced!

**Comment by JayRHa** [comment]
Do you have a roughs timeline for  the V1 and can I somehow support here?

**Comment by willydouhard** [comment]
Best case scenario is 1 week, worst case 2-3 weeks. I will ping you on issues if I see a good contribution opportunity!

**Comment by fabian-peschke** [comment]
Saving the token in the user_session also doesnt work in the cl.oauth_callback with the error:
    raise ChainlitContextException()
chainlit.context.ChainlitContextException: Chainlit context not found

Seems that the user session is not yet initalized when calling the oauth callback

**Comment by willydouhard** [comment]
Yep, we are close to release v1. Will keep you guys updated!

**Comment by willydouhard** [comment]
The new release should help with that issue. Especially the new [metadata field](https://docs.chainlit.io/guides/migration/1.0.0#appuser) on the User class.
