### ISSUE TITLE
Query re. use of of_chat_resume with LangChain

### ISSUE THREAD

**Issue by DBairdME** [Chainlit/chainlit#549]
Hi, I'm looking at using the @cl.on_chat_resume function with LangChain such that the conversation chain can be continued as needed. I see that the messages themselves are available as per the sample code on the site, but can the returned content then be passed to a LangChain agent? What would the interaction be between this function and an agent chain?

**Comment by willydouhard** [comment]
You will have to reinstantiate the langchain agent. If your agent has a memory, you will have to recreate the memory using the root_messages of the conversation. Once the new instance is ready, you will have to set it in the user session as you did it in on_chat start.
