### ISSUE TITLE
Voice recording function unreliable in Safari

### ISSUE THREAD

**Issue by stian-a-johansen** [Chainlit/chainlit#550]
The Safari implementation for voice recording seems very unreliable, however works in Chrome. 

The issue we are encountering is that it struggles to record any voice at all, and stops recording prematurely.

As an aside -  we noticed it is disabled in Firefox, might it be possible to disable in Safari as well?

**Comment by willydouhard** [comment]
This is relying on browser APIs so it is a bit out of our control. An improvement would be to be able to enable features based on the browser used by the user.

**Comment by stian-a-johansen** [comment]
Ok - understood! Thanks for the quick response @willydouhard 🙏
