### ISSUE TITLE
How to correctly pass the `msg = cl.Message(content="")` component to `AsyncLangchainCallbackHandler` for the normal display of streaming output?

### ISSUE THREAD

**Issue by SeasonGao** [Chainlit/chainlit#553]
I want to achieve the normal display of streaming output, but it doesn't work as expected based on the example code. I added print statements at the following locations 

**app.py :**
...

```python
@cl.on_message
async def on_message(message: cl.Message):
    answer_prefix_tokens = ["FINAL", "ANSWER"]

    msg = cl.Message(content="")
    print('-----------------msg------------', msg)  # Print statement 1

    callback = cl.AsyncLangchainCallbackHandler(
        stream_final_answer=True,
        answer_prefix_tokens=answer_prefix_tokens,
    )

    chain = cl.user_session.get("chain")  # type: LLMChain
    print(type(chain))
    res = await chain.arun(
        question=message.content, callbacks=[callback]
    )
```

In the `on_llm_new_token` callback method within the `LangchainTracer` class:

```python
def on_llm_new_token(
    self,
    token: str,
    *,
    chunk: Optional[Union[GenerationChunk, ChatGenerationChunk]] = None,
    run_id: UUID,
    parent_run_id: Optional[UUID] = None,
    **kwargs: Any,
) -> Any:
    msg = self.llm_stream_message.get(str(run_id), None)
    if msg:
        print('self.llm_stream_message', self.llm_stream_message)  # Print statement 2

        print('========', token)
        self._run_sync(msg.stream_token(token))
```

After debugging, it was found that the addresses of the `msg` objects printed in both places are not the same, for example:

Print statement 1: `<chainlit.message.Message object at 0x0000018CF5FD0B10>`
Print statement 2: `<chainlit.message.Message object at 0x0000018CF63E2250>`

Clearly, the `msg` component constructed in `main.py` is not correctly passed to the `callback` object, preventing the normal display of streaming text.

So, How can I correctly implement text display with streaming output?

**Comment by willydouhard** [comment]
Those are not the same messages. The Langchain callback will create its own messages. If you want to stream the final answer, take a look a [final answer streaming](https://docs.chainlit.io/api-reference/integrations/langchain#final-answer-streaming) or use [lcel](https://docs.chainlit.io/integrations/langchain#with-langchain-expression-language-lcel).
