### ISSUE TITLE
Chainlit app: UI customization

### ISSUE THREAD

**Issue by VasuMavaniT** [Chainlit/chainlit#554]
I have 3 questions related to UI changes while running chainlit application only using python with command chainlit run app.py
1) At the top of the page, how to use custom logo instead of chainlit logo
2) Just right to the chainlit logo, how to use custom text instead of the text "Chainlit"?
3) How to remove or modify the text "Build with chainlit"

**Comment by willydouhard** [comment]
Here is how to [change the chainlit logo](https://docs.chainlit.io/ui-customisation/custom-logo-and-favicon), including the chainlit text. As of now there is no simple way to remove the Built with Chainlit watermark.

**Comment by VasuMavaniT** [comment]
Thank you @willydouhard for your response.
