### ISSUE TITLE
How to load Dark Mode by default?

### ISSUE THREAD

**Issue by shawsa-artc** [Chainlit/chainlit#555]
I only need dark mode, how can i load dark mode by default?

**Comment by willydouhard** [comment]
As of now the first load is based on the system preference, then if the user changes the theme, the new preference is stored in the local storage.

**Comment by shawsa-artc** [comment]
> As of now the first load is based on the system preference, then if the user changes the theme, the new preference is stored in the local storage.

can we have this as a parameter in config.toml?

**Comment by sahajamit** [comment]
@shawsa-artc You can easily do this using custom js file.

Add a custom.js file with this content under the public directory:

```js
eval(console.log('Setting the default theme as dark.'));
eval(localStorage.setItem('themeVariant', 'dark'));
```

Now refer this file in config.toml as shown below:

```toml
custom_js = "/public/custom.js"
```

After doing this change when you restart the chainlit app, it will load the dark theme by default :-)
