### ISSUE TITLE
Chainlit UI Sidebar with selection list

### ISSUE THREAD

**Issue by VasuMavaniT** [Chainlit/chainlit#559]
I have question related to UI changes while running chainlit application only using python with command chainlit run app.py

I am implementing this functionality:
-> On starting the chat, user will first see the sidebar. And in this sidebar, there will be a selection list with options like 1, 2, 3, etc as shown below in the image.
-> Once user selects the particular option and hit the go button, the chosen option should be added to the prompt "Type your message ..." line. 

-> I am trying with this example, but not sure if cl.Select is there in element or not.
https://docs.chainlit.io/chat-experience/elements#add-an-element-to-a-message

![image](https://github.com/Chainlit/chainlit/assets/126754297/ef66a8ed-9d4d-4dba-845a-0bf15c195270)

**Comment by willydouhard** [comment]
As of now, you can only use the Select widget in chat settings. To achieve the behavior you describe, you can either:
- Use [chat settings](https://docs.chainlit.io/chat-experience/chat-settings)
- Use [AskActionMessage](https://docs.chainlit.io/api-reference/ask/ask-for-action) to make the user select options iteratively.

**Comment by philipplelidis** [comment]
I want to remention this request, because it would make chainlit a complete UI. With tick boxes it would be possible to choose between different data sources or mcp tools to use.
