### ISSUE TITLE
ImportError: dlopen - symbol not found in flat namespace '_CFRelease'

### ISSUE THREAD

**Issue by Elicherla01** [Chainlit/chainlit#56]
I am getting below error.

I am using Mac OS - M1

<img width="1716" alt="image" src="https://github.com/Chainlit/chainlit/assets/14846630/6be9a6f6-d8fe-4052-b964-2aae0242d9f5">

**Comment by willydouhard** [comment]
It looks like there is a problem with your grpc build as discussed [here](https://stackoverflow.com/questions/72620996/apple-m1-symbol-not-found-cfrelease-while-running-python-app).

Can you give me your version of grpc `pip show grpcio`? Also are you using `conda`?

**Comment by littson** [comment]
Same problem. Can be solved by rebuilding grpcio from source: [source link](https://stackoverflow.com/a/74306400/1699518).

**Comment by dsantiago** [comment]
> Same problem. Can be solved by rebuilding grpcio from source: [source link](https://stackoverflow.com/a/74306400/1699518).

Yeah this solves the problem, thanks!

Posting here the solution to facilitate:

```bash
pip uninstall grpcio
export GRPC_PYTHON_LDFLAGS=" -framework CoreFoundation"
pip install grpcio --no-binary :all:
```

**Comment by sumanghosh1234** [comment]
I am still facing the same problem even after trying 

pip uninstall grpcio
export GRPC_PYTHON_LDFLAGS=" -framework CoreFoundation"
pip install grpcio --no-binary :all:

 from grpc._cython import cygrpc
ImportError: dlopen(/Users/123456/miniforge3/lib/python3.11/site-packages/grpc/_cython/cygrpc.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'
@willydouhard 
@dsantiago

**Comment by willydouhard** [comment]
Can you try to disable the telemetry? Set `enable_telemetry=false` in `.chainlit/config.toml`. I think grpc is only used for that purpose.

**Comment by RoacherM** [comment]
i solved this issue with this method.
1. pip uninstall grpcio
2. add those three lines at the end of your .zshrc file

export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
export GRPC_PYTHON_LDFLAGS=" -framework CoreFoundation"
3. pip install grpcio --no-binary :all:

**Comment by wiharto** [comment]
I use conda environment and this works for me

`pip uninstall grpcio
conda install grpcio`

`pip install grpcio` gives me an error about not being able to build the wheel for grpcio.

**Comment by JustinGuese** [comment]
> > Same problem. Can be solved by rebuilding grpcio from source: [source link](https://stackoverflow.com/a/74306400/1699518).
> 
> Yeah this solves the problem, thanks!
> 
> Posting here the solution to facilitate:
> 
> ```shell
> pip uninstall grpcio
> export GRPC_PYTHON_LDFLAGS=" -framework CoreFoundation"
> pip install grpcio --no-binary :all:
> ```

confirm working

**Comment by pq-dong** [comment]
> > Same problem. Can be solved by rebuilding grpcio from source: [source link](https://stackoverflow.com/a/74306400/1699518).
> 
> Yeah this solves the problem, thanks!
> 
> Posting here the solution to facilitate:
> 
> ```shell
> pip uninstall grpcio
> export GRPC_PYTHON_LDFLAGS=" -framework CoreFoundation"
> pip install grpcio --no-binary :all:
> ```

I made an error using this command, but I changed it to `pip install --no-cache-dir  --force-reinstall -Iv grpcio --no-binary :all:` and it worked
