### ISSUE TITLE
chainlit keeps trying to connect to a german server

### ISSUE THREAD

**Issue by yrougy** [Chainlit/chainlit#560]
My chainlit pip package doesn't work (I have a connection refused on port 8000), but when I launch the hello app, I have a connection to 116.202.107.2 port 4317.
Content is not clear text.

I tried to grep this IP in the source code to see if it's mentionned, but can't find it.

Why connecting to a german server ?

OS: Ubuntu 22.04
Pip package: version 0.7.604

**Comment by willydouhard** [comment]
I would need more info about the setup to help you with the connection refused on port 8000.

For the connection to the german server, it is either Chainlit Cloud if you enabled [data persistence](https://docs.chainlit.io/cloud/persistence/getting-started) or the telemetry (you can opt out by setting `enable_telemetry` to `false` in your [config file](https://docs.chainlit.io/backend/config/project)).
