### ISSUE TITLE
cl.Text element rendering text as Markdown code unexpectedly 

### ISSUE THREAD

**Issue by Anjum48** [Chainlit/chainlit#561]
I'm rendering the text of a source using a `cl.Text` element, however part way through the text, it renders as a code snippet:

![image](https://github.com/Chainlit/chainlit/assets/13783303/7aebdab4-6873-405e-bc78-ddcce883f36d)

As far as I can tell, there are no characters that indicate markdown in the source:

![image](https://github.com/Chainlit/chainlit/assets/13783303/57e86a2d-928c-4962-93c2-8720667111a1)

Any ideas what could be causing this behaviour?

**Comment by willydouhard** [comment]
This is weird indeed. Can you provide the source text so I can try to reproduce?

**Comment by Anjum48** [comment]
Sure - I've attached a zipped CSV file and the line in question is 1058 (although this happens in more than one case)
[Technical_2023-08-31.zip](https://github.com/Chainlit/chainlit/files/13442281/Technical_2023-08-31.zip)

The data was originally parsed from a PDF file, but as far as I can tell, I can't see any strange characters, and the markdown section starts are roughly the same place in the source in each example I've seen this happen

**Comment by willydouhard** [comment]
I am able to reproduce, will investigate!

**Comment by willydouhard** [comment]
The tabs are the culprit. Here is what gpt-4 says

> It seems like you're encountering an issue where `react-markdown` is interpreting a portion of your text as code. This can happen if the text is indented with spaces or tabs, which is a common way to denote code blocks in Markdown.
> 
> In standard Markdown, code blocks can be created in two ways:
> 
> 1. Indented with four spaces or one tab (this is what's likely happening in your case).
> 2. Enclosed with triple backticks (```) before and after the code block.
> 
> Here's an example of how indentation can cause text to be treated as a code block:
> 
> ```markdown
> Normal text
> 
>     This will be treated as code because it's indented with four spaces.
> ```
> 
> To prevent `react-markdown` from interpreting your text as code, you need to ensure that there are no leading spaces or tabs before your lines of text. If the text is coming from an external source and you can't control the formatting, you might need to preprocess the text to remove any unintended indentation before passing it to `react-markdown`.
> 
> If you're copying and pasting text from a document that uses indentation for formatting, you'll need to strip out these leading spaces. You can do this manually or write a small function to preprocess the text:
> 
> ```javascript
> function removeLeadingSpaces(text) {
>   return text.split('\n').map(line => line.trimStart()).join('\n');
> }
> 
> const text = `Your text here...`;
> const processedText = removeLeadingSpaces(text);
> ```
> 
> Then you can use `processedText` with `react-markdown` to ensure it's not treated as a code block.

In this case what you can do is to pass `language=text` to your Message or Text element to ensure it is one code block at least.

**Comment by Anjum48** [comment]
Ha great use of GPT! I didn't know that 4-spaces also triggered a code block in Markdown. I'll fix my text.

I think I need to preserve the default `language` since I'm also inserting links, unless there is another way to do that? (presumably React will now allow HTML tags)
