### ISSUE TITLE
File Not Found 

### ISSUE THREAD

**Issue by vikram-s-narayan** [Chainlit/chainlit#570]
In the [docs for Document QA](https://docs.chainlit.io/examples/qa) the link to the state of the union is broken.

To reproduce, click on the link in the sentence: 

"The state of the union file is available here"

The link - https://github.com/langchain-ai/langchain/blob/master/docs/extras/modules/state_of_the_union.txt - leads to a 404 page.

**Comment by willydouhard** [comment]
Thanks for letting us know! Just fixed it.

**Comment by vikram-s-narayan** [comment]
Awesome! You guys rock!
