### ISSUE TITLE
LlamaIndex integration throws "LookupError: <ContextVar name='chainlit' at 0x7fb17e562840>"

### ISSUE THREAD

**Issue by younes-io** [Chainlit/chainlit#571]
It seems that Chainlit doesn't work when I integrate it with LlamaIndex

I'm using `Python 3.11.4`

This is my `requirements.txt` file:

```
chainlit==0.7.604
llama_index==0.9.7
openai==1.3.5
langchain==0.0.340
pypdf==3.17.1
```

```shell
zsh ❯ chainlit run app.py -w

2023-11-25 15:00:46 - Loaded .env file
llm._default_params :  {'model': 'gpt-3.5-turbo', 'stream': False, 'n': 1, 'temperature': 0.0}
Traceback (most recent call last):
  File "/home/userdev/dev/llm_chat/.venv/bin/chainlit", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/userdev/dev/llm_chat/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/dev/llm_chat/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/userdev/dev/llm_chat/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/dev/llm_chat/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/dev/llm_chat/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/dev/llm_chat/.venv/lib/python3.11/site-packages/chainlit/cli/__init__.py", line 143, in chainlit_run
    run_chainlit(target)
  File "/home/userdev/dev/llm_chat/.venv/lib/python3.11/site-packages/chainlit/cli/__init__.py", line 45, in run_chainlit
    load_module(config.run.module_name)
  File "/home/userdev/dev/llm_chat/.venv/lib/python3.11/site-packages/chainlit/config.py", line 274, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/userdev/dev/llm_chat/app.py", line 9, in <module>
    import helpers
  File "/home/userdev/dev/llm_chat/helpers.py", line 70, in <module>
    callback_manager=CallbackManager([cl.LlamaIndexCallbackHandler()]),
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/dev/llm_chat/.venv/lib/python3.11/site-packages/chainlit/llama_index/callbacks.py", line 31, in __init__
    self.context = context_var.get()
                   ^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='chainlit' at 0x7fb17e562840>
```

Could you please help on this ?

**Comment by younes-io** [comment]
@willydouhard : could you please take a look at this?

**Comment by willydouhard** [comment]
Are you instantiating the callback handler from a chainlit context (like on_message)?

**Comment by younes-io** [comment]
@willydouhard : here's what I do:

```python

service_context = ServiceContext.from_defaults(
    llm=llm,
    embed_model=embeddings, ## (optional)
    # node_parser=node_parser, ## (optional)
    prompt_helper=prompt_helper,
    callback_manager=CallbackManager([cl.LlamaIndexCallbackHandler()]),
)
```

just as described [here](https://docs.chainlit.io/integrations/llama-index)

That code snippet above is used in a file called `helpers.py` and not inside a chainlit-decorated function. Actually, I'm using the code in the chainlit cookbook repo: https://github.com/Chainlit/cookbook/blob/1bc9c009254ee951ae74386239772a6d142c25aa/llama-index-googledocs-qa/app.py#L73

**Comment by ookice** [comment]
Verify Environment: Check if your virtual environment (/.venv/) is activated and correctly configured. You can activate it using:
source /path/to/your/llm_chat/.venv/bin/activate

**Comment by willydouhard** [comment]
Notice that this code is an function `load_context` called in `on_chat_start`. Is this the case on your end?

**Comment by younes-io** [comment]
@willydouhard : it is

FYI: when I comment the call to to the callback handler, there is no error.. as soon as I use it, the error is thrown.. so, the issue is related to chainlit trying to set up context vars or something and it fails to for some reason..

**Comment by younes-io** [comment]
I found a workaround. Basically, when I wrap that code inside a function, then call it, the error disappears.. 

```python

def get_service_context(llm: AzureChatOpenAI, embeddings: AzureOpenAIEmbeddings) -> ServiceContext:
    service_context = ServiceContext.from_defaults(
        llm=llm,
        embed_model=embeddings, ## (optional)
        # node_parser=node_parser, ## (optional)
        prompt_helper=prompt_helper,
        callback_manager=CallbackManager([cl.LlamaIndexCallbackHandler()]),
    )
    set_global_service_context(service_context)
    return service_context
```

**Comment by younes-io** [comment]
I still have an issue though @willydouhard 

When I execute this [code ](https://github.com/Chainlit/cookbook/blob/1bc9c009254ee951ae74386239772a6d142c25aa/llama-index-googledocs-qa/app.py#L28), it throws an error stating that `callback_manager` isn't a property of storage context. So, basically, that code doesn't work... I need to figure out a way to make this work...

**Comment by younes-io** [comment]
do you use Azure OpenAI API ?

**Comment by willydouhard** [comment]
No, just the regular openai

**Comment by younes-io** [comment]
maybe it's worth testing with Azure OpenAI. also could you please let me know your openai, python versions ?

**Comment by willydouhard** [comment]
I am using openai `1.3.3` and python `3.11.5`. Can you share the exact code you run so I can try to reproduce?

**Comment by tjroamer** [comment]
I am trying to figure out the use case of LlamaIndexCallbackHandler. Is the intention to display llama_index handling as steps in UI?

**Comment by willydouhard** [comment]
Yes, display the intermediate steps + prompts in the UI (and monitor them if data persistence is enabled)

**Comment by tjroamer** [comment]
It seems that when using chat_engine, only the callback event types `CBEventType.QUERY` and `CBEventType.SYNTHESIZE` are generated. But the `LlamaIndexCallbackHandler` captures `CBEventType.RETRIEVE` and `CBEventType.LLM`, so the registration of this callback handler has no effect. 

What I want to do is: show the retrieved sources and get a playground for a chat session and display them in the step window. I suppose that I need to let llama_index generate `CBEventType.RETIEVE` and `CBEventType.LLM`. But have no idea how to impose. 

Any suggestion would be appreciated. Thanks.

**Comment by tpatel** [comment]
The original issue popped on discord again: https://discord.com/channels/1088038867602526210/1204448735615262811/1204448735615262811.

**Comment by younes-io** [comment]
Closing as Chainlit is broken and has tons of bugs..
