### ISSUE TITLE
Add the option to disable websocket compression.

### ISSUE THREAD

**Issue by TheHACKATHON** [Chainlit/chainlit#574]
Hi, 
I host Chainlit using IIS, but this server does not support websocket compression. I need to deactivate it by passing the `ws_per_message_deflate=False` parameter to the uvicorn configuration. 
Can you create a CLI option to perform this task? 

Thank you.

**Comment by willydouhard** [comment]
Will do!

**Comment by willydouhard** [comment]
With the latest release `0.7.700` you can disable it by declaring this `UVICORN_WS_PER_MESSAGE_DEFLATE=false` env var.

**Comment by hanshupe007** [comment]
@TheHACKATHON I am struggling with hosting Chainlit on IIS. Can you please explain how you accomplished this, did you use WSGI or URL Rewrite in IIS? It seems that there is an issue with websocket, but not the one above. I receive a bad request message. Any help would highly appreciated, thanks!

**Comment by TheHACKATHON** [comment]
@hanshupe007 I believe I encountered a similar problem. In my case, it was due to IIS running many workers by default and not balancing them reasonably. Therefore, I limited the number to one, and everything worked.

My web config:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <handlers>
			<add name="PythonHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
        </handlers>
		<httpPlatform processPath="C:\inetpub\wwwroot\chainlit\venv\Scripts\python.exe" arguments="-m chainlit run C:\inetpub\wwwroot\chainlit\main.py -h --port %HTTP_PLATFORM_PORT%" startupTimeLimit="60" processesPerApplication="1" stdoutLogEnabled="true" stdoutLogFile="C:\Logs\python.log">
			<environmentVariables>
				<environmentVariable name="SERVER_PORT" value="%HTTP_PLATFORM_PORT%" />
			</environmentVariables>
		</httpPlatform>
    </system.webServer>
</configuration>

```

stdoutLogFile very helpful 
processesPerApplication is worker limitation

**Comment by hanshupe007** [comment]
Thanks, will give it a try. Can I ask if you used URL Rewrite in IIS or WSGI, is the snippet above the original web.xml that worked for you?

**Comment by TheHACKATHON** [comment]
Yes, it is a snippet of web.config file, that should be in the root of your site folder, or you can create it and IIS will work with it. 

It's not URL Rewrite and not WSGI, I tried to run it through both, but I don't remember what went wrong, it worked through httpPlatformHandler 
![image](https://github.com/user-attachments/assets/83bd03ba-2aeb-47db-96a7-862c7ee39748)

**Comment by hanshupe007** [comment]
Great thanks this approach works. Did you also managed to get windows authentication working? As soon as I activate Windows Authentication and disable Anonymous authentication I get this error

![image](https://github.com/user-attachments/assets/acd6d75a-f401-4714-a8f8-14183b7fb587)
