### ISSUE TITLE
Not able to access UI when starting the app from linux vm

### ISSUE THREAD

**Issue by amitguptadumka** [Chainlit/chainlit#575]
Hi, 
I have a app.py script, same script when i run with command **chainlit run app.py -w** after setting (API Key/Auth Secret etc) is working from my local but when i start the same app from a linux vm i am not able to access the app UI. I am using my_ip:8000 to access but still not able to access. How can i fix this. I am trying to host from a remote machine because i want my entire team to access the app.
Appreciate any help, Thanks.

**Comment by willydouhard** [comment]
Can you try adding `-h` to your start command and try again?

**Comment by amitguptadumka** [comment]
Thanks @willydouhard . Worked. Closing this.
