### ISSUE TITLE
Input fields remain disabled when switching profiles 

### ISSUE THREAD

**Issue by selinerdem** [Chainlit/chainlit#576]
Hello, first of all, thank you for the incredible work on chainlit, it's a great library! 

I've noticed that with multiple profiles, if the user switches from a profile that uses AskFileMessage on @cl.on_chat_start to another profile, the input fields remain disabled. I think the only way to enable the input fields is refreshing the page.

I was trying to pinpoint the cause and noticed that askUserState is not being reset like the other states here in the clear callback fn: https://github.com/Chainlit/chainlit/blob/174535453f3147757976cfc46748b78e962766a9/libs/react-client/src/useChatInteract.ts#L40  

As its value is being used to disable the input field, the input field remains disabled . 

Is this a bug or is it excluded deliberately? If it's on purpose, is there any workaround that I can use to enable input fields during switching profiles? 

Thanks!

**Comment by willydouhard** [comment]
Thank you for this bug report! This should be fixed with the latest release `0.7.700`
