### ISSUE TITLE
Langchain v0.0.198 breaks chain of thought UI

### ISSUE THREAD

**Issue by jimmarshall87** [Chainlit/chainlit#58]
Langchain 0.0.198 seems to break the chain of thought functionality when using the chain lit langchain integration and everything is flattened in the UI.
Downgrading to langchain 0.0.197 fixes this.

**Comment by willydouhard** [comment]
You are correct, we are going to have a big release today fixing this among other things!

**Comment by jimmarshall87** [comment]
I figured you would be on this one @willydouhard ! Good luck!

**Comment by jimmarshall87** [comment]
Yep, all good for me. Nice work! 👍👍
