### ISSUE TITLE
add regenerate？

### ISSUE THREAD

**Issue by lw3259111** [Chainlit/chainlit#583]
<img width="996" alt="image" src="https://github.com/Chainlit/chainlit/assets/12690488/2239efea-f0f2-4201-985a-a2db43b2fbfc">
When the results are generated, I would like to rewrite the above answer.

**Comment by willydouhard** [comment]
I think you can achieve this with actions and message.update()

**Comment by lw3259111** [comment]
Can you provide an example of streaming output combined with a regenerate output? I've tried but haven't been successful.
