### ISSUE TITLE
Feature request: Add feature to auto hide and rename nested messages

### ISSUE THREAD

**Issue by fabian-peschke** [Chainlit/chainlit#584]
Hello,

We're using nested messages for debug information and facing two issues:

1. Nested Messages Auto-Expand: We need an option to set these messages to be collapsed by default.
2. Customizable Text for Nested Messages: Instead of the default "Took {nr} steps" text, we want to customize this text.

Proposed Enhancements:
Visibility Setting: Allow setting nested messages to be either expanded or collapsed by default.
Custom Marker Text: Enable custom text for the markers in nested messages.

**Comment by willydouhard** [comment]
Nested messages should not auto expand unless the [default_expand_message](https://docs.chainlit.io/backend/config/ui) parameter is set to `true` in your config.

For the default text customisation, it might come in the future but is not prioritised atm.

**Comment by fabian-peschke** [comment]
Yes, seems that we missed that config. Thanks for the help
