### ISSUE TITLE
Maximum number of concurrent users 

### ISSUE THREAD

**Issue by Deepansharora27** [Chainlit/chainlit#586]
Hello,
Is there a provision where multiple users can access Chainlit service at the Same Time ?

Right now while trying to access the service on multiple devices on multiple browsers , the service just times out. 

Is there a hard cap on the number of concurrent users that can access the service at the same time ?

**Comment by willydouhard** [comment]
The server can handle a lot of concurrent users as long as you do not block the main thread with long running tasks. If you make sync calls to an assistant in on_message, this will not work. Either make async calls or wrap the sync calls in `cl.make_async`.
