### ISSUE TITLE
Progress bar / spinning wheel

### ISSUE THREAD

**Issue by dcieslak19973** [Chainlit/chainlit#588]
Is there a way in the UI to let the user know that a request / message is currently being processed?

**Comment by willydouhard** [comment]
[Yes](https://docs.chainlit.io/chat-experience/loader)!

**Comment by dcieslak19973** [comment]
Thanks - I missed that!

**Comment by nileshtrivedi** [comment]
Found the [old docs](https://github.com/Chainlit/docs/blob/a2153e7fe85e420ed8c833d0cbbcde7dd6493a8f/chat-experience/loader.mdx) but apparently this trick (sending an empty message and then updating it later) does not work anymore.

**Comment by nileshtrivedi** [comment]
Tested this code in version 1.1.304 and a blinking dot was displayed, but in the latest version 1.1.401, no progress indicator is shown. Looks like this ability was removed sometime in between these two versions.

```
import chainlit as cl


@cl.on_message
async def on_message(message: cl.Message):
    msg = cl.Message(content="")
    await msg.send()

    # do some work
    await cl.sleep(4)

    msg.content = f"Processed message {message.content}"

    await msg.update()
```

**Comment by vaclcer** [comment]
Exactly this! It works until 1.1.306.
