### ISSUE TITLE
Use Chainlit on SageMaker Studio

### ISSUE THREAD

**Issue by geodra** [Chainlit/chainlit#59]
I tried to deploy a Chainlit app on SM studio running this command `chainlit run app.py -w --port 6001` and access it through this url -> https://<domain-id>.studio.<region>.sagemaker.aws/jupyter/default/proxy/6001/ but nothing was being rendered.

Streamlit & Gradio APPs can be easily rendered on SM studio as per this repo -> https://github.com/machinelearnear/use-gradio-streamlit-sagemaker-studiolab

**Comment by willydouhard** [comment]
Are you using studio or studio labs? I requested access to studio labs to try myself

**Comment by geodra** [comment]
I use [SageMaker Studio on AWS](https://aws.amazon.com/sagemaker/studio/). You first need to create a domain and then inside a domain a user. SM studio is very similar to Jupyter Lab but with steroids you can do extra stuff like visualizing the pipelines, navigate Jumpstart solution etc. It is weird because when I try to open the page the title says Chatbot but nothing is being rendered as per the image below. Do I need to add some other arguments when running `chainlit run`
![image](https://github.com/Chainlit/chainlit/assets/42205330/092dc76b-19b0-41af-9172-00dd111bb7cd)
![Screenshot 2023-06-14 at 10 06 54](https://github.com/Chainlit/chainlit/assets/42205330/4c250e39-ff56-43fa-bf76-9e9edc4416b3)

**Comment by geodra** [comment]
This is what I get when I inspect the page.
![image](https://github.com/Chainlit/chainlit/assets/42205330/233585d9-6a7e-40c9-a49a-47dda40d6910)

**Comment by willydouhard** [comment]
I suspect this is the same issue as #38

**Comment by geodra** [comment]
Any update on this issue?

**Comment by willydouhard** [comment]
Not yet, I think the problem is that the chainlit app is not served at the root of the domain or subdomain. Do you have a way to set a direct domain name or subdomain for your app on sagemaker studio?

**Comment by duyongan** [comment]
Any update?

**Comment by willydouhard** [comment]
This is has not been addressed yet. The fix for the moment would be to serve your sage maker endpoint from a subdomain. That way the chainlit app would be served at the root level

**Comment by armenavd** [comment]
### Temporary Working Solution for Running Chainlit in Amazon SageMaker Notebook(Fixes White Screen)

I ran into the same issue (blank UI / nothing rendered when accessing Chainlit through SageMaker’s proxy).  
Here is a fully working solution using:

- `--root-path` so Chainlit knows it lives under a URL prefix
- A small reverse proxy (Uvicorn + Starlette + httpx) to forward requests correctly

This completely eliminates the white screen problem.

---

## ✅ **How it Works**

SageMaker Notebook exposes ports under a path like:

```
https://<notebook>.notebook.<region>.sagemaker.aws/proxy/9000/
```

Chainlit does **not** automatically detect this prefix, so we provide it via `--root-path`, and we route all requests through a Starlette reverse proxy.

---

##  **Step 1 — Run Chainlit with the correct root-path**

```bash
chainlit run app.py \
  --port 8000 \
  --host 0.0.0.0 \
  --root-path /proxy/9000 \
  --watch
```

---

## **Step 2 — Create the reverse proxy (`proxy_app.py`)**

It should look like something like this:

```python
from starlette.applications import Starlette
from starlette.responses import Response
from starlette.requests import Request
from starlette.websockets import WebSocket
from starlette.endpoints import WebSocketEndpoint
from starlette.routing import Route, WebSocketRoute
import httpx

ROOT_PATH = "/proxy/9000"
UPSTREAM = "http://127.0.0.1:8000"

async def http_proxy(request: Request):
    path = request.path_params.get("path", "")
    upstream_path = f"{ROOT_PATH}/{path}" if path else ROOT_PATH
    url = f"{UPSTREAM}{upstream_path}"
    if request.url.query:
        url += f"?{request.url.query}"

    async with httpx.AsyncClient(follow_redirects=True, timeout=30.0) as client:
        rp = await client.request(
            request.method, url,
            headers={k: v for k, v in request.headers.items()
                     if k.lower() not in ("host", "accept-encoding")},
            content=await request.body(),
        )

    return Response(
        content=rp.content,
        status_code=rp.status_code,
        headers={k: v for k, v in rp.headers.items()
                 if k.lower() not in ("content-length", "transfer-encoding", "content-encoding")},
    )

class WSProxy(WebSocketEndpoint):
    encoding = "text"

    async def on_connect(self, websocket: WebSocket):
        await websocket.accept()
        await websocket.close(code=1000)

    async def on_receive(self, websocket: WebSocket, data):
        pass

    async def on_disconnect(self, websocket: WebSocket, close_code: int):
        pass

routes = [
    Route("/{path:path}", http_proxy, methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]),
    WebSocketRoute("/ws/socket.io/", WSProxy),
]

app = Starlette(routes=routes)
```

---

## **Step 3 — Run the proxy**

```bash
uvicorn proxy_app:app --host 0.0.0.0 --port 9000
```

---

## **Step 4 — Open Chainlit**

Navigate to:

```
https://<your-notebook>.notebook.<region>.sagemaker.aws/proxy/9000/
```

---

### Result

- No more blank page  
- All static files load properly  
- Works with SageMaker’s internal proxying  
- Framework-agnostic → can be reused e.g. in JupyterHub, internal proxies, enterprise environments  

If anyone needs help adapting this to another prefix or environment, let me know!
