### ISSUE TITLE
Attach large files

### ISSUE THREAD

**Issue by nviso-bjarne** [Chainlit/chainlit#591]
Hey all,

I recently added Multi-Modal support to my chatbot (https://docs.chainlit.io/chat-experience/multi-modal).
That is, users can upload files and I answer questions based on those files.

It seems that when I press the 'Upload Files' button and proceed to select a large pdf file (more than 50MB), nothing happens. By which I mean that the attachment does not show up above the 'Type you message here...' input. 
This works perfectly for smaller files, but not for large ones. Is there a limit on the file size somewhere in the code that I can adjust?

Kind regards,
Bjarne

**Comment by willydouhard** [comment]
Currently it is pretty limited. Chainlit 1.0.0 will remove this limit and enhance upload performances. Release date is 2024 january 2!

**Comment by nviso-bjarne** [comment]
Great! Thank you.
