### ISSUE TITLE
K8s deployment recommendation

### ISSUE THREAD

**Issue by dcieslak19973** [Chainlit/chainlit#592]
I've dockerized a chainlit application and I would like to run it in a kubernetes environment to enable multiple concurrent users.  Is there any guidance on how best to do this?  Simply run some number of pods in a deployment behind either an Ingress or Load Balancer?

**Comment by willydouhard** [comment]
No special advice except that your load balancer should have sticky sessions since Chainlit uses web sockets. I would also not spawn lots of pods, one pod should handle hundreds of users.
