### ISSUE TITLE
The output is not aligned for codes

### ISSUE THREAD

**Issue by Sawyer117** [Chainlit/chainlit#595]
Like I showed in the image, the codes are all left aligned.
![Untitled](https://github.com/Chainlit/chainlit/assets/41589262/a8bd5c98-d7ea-46be-9657-41083a1f253d)

Not sure the reason because when I try huggingface's pipeline of phi-1.5, it can correctly generate aligned codes.
the code I wrote is like this:

import chainlit as cl
from langchain.llms import VLLM
from langchain import HuggingFaceHub, PromptTemplate, LLMChain
from langchain.prompts import ChatPromptTemplate
from langchain.schema import StrOutputParser
from langchain.schema.runnable import Runnable
from langchain.schema.runnable.config import RunnableConfig

os.environ['CURL_CA_BUNDLE'] = ''

llm = VLLM(
    model="microsoft/phi-1_5",
    trust_remote_code=True,  # mandatory for hf models
    max_new_tokens=300,
    top_k=10,
    top_p=0.95,
    temperature=0.8,
)

@cl.on_chat_start
async def on_chat_start():
    model = llm
    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                "Please answer following questions",
            ),
            ("user", "{question}"),
        ]
    )
    runnable = prompt | model | StrOutputParser()
    cl.user_session.set("runnable", runnable)

@cl.on_message
async def on_message(message: cl.Message):
    runnable = cl.user_session.get("runnable")  # type: Runnable

    msg = cl.Message(content="")

    async for chunk in runnable.astream(
        {"question": message.content},
        config=RunnableConfig(callbacks=[cl.LangchainCallbackHandler()]),
    ):
        await msg.stream_token(chunk)

    await msg.send()

**Comment by willydouhard** [comment]
A better way would be that the model wrap the code with ```py for instance. Then it would be correctly displayed.

**Comment by willydouhard** [comment]
I am not saying the output is bad. I am saying that if the code is wrapped in ```py the code will be displayed in a code block with syntax highlighting. It might also fix your indentation problem :)
