### ISSUE TITLE
Making Port / Host configurable

### ISSUE THREAD

**Issue by michaelfeil** [Chainlit/chainlit#6]
Currently hardcoded to Port 8000

- read from env
- read from args

Same for hostname 0.0.0.0 / localhost

**Comment by willydouhard** [comment]
Thank you for your feedback!

The `0.2.106` release makes the port and hostname configurable through the `CHAINLIT_HOST` and `CHAINLIT_PORT` env variables. You can also use `--host` and `--port` when running `chainlit run ...`.
