### ISSUE TITLE
Feature request: Automatic Chat History Refresh and URL-Based App Switching

### ISSUE THREAD

**Issue by mikuh** [Chainlit/chainlit#603]
Suggestion  #1: "After creating a new chat by clicking the 'new chat' button, it would be great if the chat history list could automatically refresh."

Suggestion #2: "Consider implementing the ability to switch between different apps using URL paths for a more seamless navigation experience."

**Comment by hayescode** [comment]
Any updates we can look forward to on this? Is being developed?
