### ISSUE TITLE
Render LaTeX equations in chat

### ISSUE THREAD

**Issue by Enoch2090** [Chainlit/chainlit#604]
- [KaTeX](https://github.com/KaTeX/KaTeX)
- [MathJax](https://www.mathjax.org/)

Although it is possible to manually render the equations with HTML, things gets messy when using streamed chunks. It is therefore better to do this within the framework.

**Comment by willydouhard** [comment]
Did you check the [latex feature flag](https://docs.chainlit.io/backend/config/features) in the config file?

**Comment by Enoch2090** [comment]
Ah my bad, missed this flag in the config, it's working now! Thanks!
