### ISSUE TITLE
Shortcut copy button not working

### ISSUE THREAD

**Issue by qianghuangwhu** [Chainlit/chainlit#609]
# Shortcut copy button in the upper right corner of the code block not working

![截屏2023-12-20 上午9 39 50](https://github.com/Chainlit/chainlit/assets/62199595/44158199-23ab-416f-9d65-fbcebf9acb09)

### 3. Chainlit 0.7.700 (pip install)

**Comment by willydouhard** [comment]
Should be fixed with the `1.0.0` release!

**Comment by qianghuangwhu** [comment]
thanks!
