### ISSUE TITLE
Chainlit responses being cut off

### ISSUE THREAD

**Issue by CryptVenture** [Chainlit/chainlit#623]
I am attempting to create a chainlit-based chat application using Embedchain. Everything is working except the responses coming through chainlit are cut off / truncated and never seem to be displayed in their entirety. Is there a setting of some description that would make sure that all the streaming content is displayed?

**Comment by willydouhard** [comment]
What version of Chainlit are you using? Also, are you saying the response is not entirely visible (we have a feature to shrink long messages and you have a button to expand those responses) or the response is missing tokens entirely?

**Comment by antoniodagata77** [comment]
I have the same issue. 
If the answer provided by LLM covers more than one line the final answer shown by the UI includes only the first one. chainlit version 1.0.101 farm-haystack version 1.23.0.

complete answer on shell
<img width="540" alt="Screenshot 2024-01-16 165425" src="https://github.com/Chainlit/chainlit/assets/151049115/73e7e094-21e3-4da8-a3ea-3c1300a47633">

truncated
<img width="1271" alt="Screenshot 2024-01-16 165548" src="https://github.com/Chainlit/chainlit/assets/151049115/4f52d774-73fd-475c-a3e0-0231a06e92f7">

**Comment by willydouhard** [comment]
Can you provide the code to reproduce?

**Comment by antoniodagata77** [comment]
this is the code slice of interest:

`retriever = get_retriever()
agent = get_agent(retriever)
cl.HaystackAgentCallbackHandler(agent)


@cl.author_rename
def rename(orig_author: str):
    rename_dict = {"custom-at-query-time": "Agent Step"}
    return rename_dict.get(orig_author, orig_author)


@cl.on_message
async def main(message: cl.Message):
    response = await cl.make_async(agent.run)(message.content)
    await cl.Message(author="Agent", content=response["answers"][0].answer).send()


Note: If I set the paramenter "stream_final_answer=True" in this way:

cl.HaystackAgentCallbackHandler(agent, stream_final_answer=True)

the answer is complete, but the first row is repeated

<img width="916" alt="Screenshot 2024-01-17 120841" src="https://github.com/Chainlit/chainlit/assets/151049115/8aed363f-8f69-4520-a26d-16a7f8d6b1aa">

**Comment by tpatel** [comment]
If this is still something you are working on, have you tried using `stream_final_answer=True` and removing the line 

```
await cl.Message(author="Agent", content=response["answers"][0].answer).send()
 ```
