### ISSUE TITLE
Remove the "switch-hide-cot" from the Settings UI

### ISSUE THREAD

**Issue by scoronado** [Chainlit/chainlit#624]
Is there a way to remove the "switch-hide-cot" from the Settings UI, from the settings options top-right PersonIcon?

<img width="989" alt="Screenshot 2024-01-02 at 13 59 05" src="https://github.com/Chainlit/chainlit/assets/7807739/681f4dc0-f55a-4f0d-ab10-63c69ae242c0">

**Comment by SalamanderXing** [comment]
You probably can do that using custom CSS

**Comment by willydouhard** [comment]
Curious about the use case? Is this because you do not want the user to see the Chain of Thought at all? In this week's release, if hide_cot is set to true in the config, the intermediate steps will never be sent to the UI.

**Comment by scoronado** [comment]
Yes @willydouhard, this is the case. To have a clean UI for end users.

**Comment by willydouhard** [comment]
Okay so the release should fix that (the toggle will still show but will not change anything if the original value is set to true on the server)

**Comment by scoronado** [comment]
Furthermore, the 'prompt_playground = false' setting in config.toml does not function as intended; you can still access the prompt playground and use it openly

**Comment by willydouhard** [comment]
I doubled checked and everything should work correctly with tomorrow's release!

**Comment by scoronado** [comment]
Everything looks good, thx @willydouhard
