### ISSUE TITLE
Rendering a Web Page Using Chainlit Callback Methods

### ISSUE THREAD

**Issue by Deepansharora27** [Chainlit/chainlit#632]
Hi, 
I see that there are various Elements that can be rendered on the UI (https://docs.chainlit.io/api-reference/elements/text)

I was trying to make use of the `File Element` in order to render a Basic HTML Page but what happens is that instead of rendering I am just able to Download the File as an element. Is there a way where I could Render an Entire Web Page for instance to serve/render a static asset ?

**Comment by willydouhard** [comment]
You can use [unsafe_allow_html](https://docs.chainlit.io/backend/config/features) to directly put html if your message content (can also be an iframe).

**Comment by Deepansharora27** [comment]
Instead of displaying it as a message, I want to change the state of the UI and enable/disable certain elements ? Would that be possible ?

**Comment by willydouhard** [comment]
I don't think so
