### ISSUE TITLE
How to handle "Timed out: no action was taken"

### ISSUE THREAD

**Issue by lianghsun** [Chainlit/chainlit#634]
I am currently encountering an issue related to exception handling. Specifically, I'm trying to catch a _timeout exception_ using the `run_sync` method, but my attempts have been unsuccessful so far.

Here's the code snippet I'm using:
```
try:
    reply = cl.run_sync(ask_helper(cl.AskUserMessage, content="", timeout=300, raise_on_timeout=True))
except TimeoutError:
    # Handle the timeout exception
```

Despite using a _try...except_ block to catch TimeoutError, the exception doesn't seem to be captured as expected. Could you provide guidance on the correct way to catch this timeout exception? Are there any specific exceptions related to Chainlit's `run_sync` method that I should be aware of? Thanks :)

**Comment by willydouhard** [comment]
This might be tricky. Is it impossible for you to execute this code in a async function in this particular context? If you could `await` the ask helper it should work.
