### ISSUE TITLE
Can't attach new files when changing chat profile

### ISSUE THREAD

**Issue by ssillerom** [Chainlit/chainlit#647]
Hi,

I just updated to the latest version (1.0.0) and when I try to upload an image with the default profile, it works. However, when I switch to another profile and try to attach a new file, I receive an error. It seems like the profile session is not being reset properly. This needs to be fixed.

![image](https://github.com/Chainlit/chainlit/assets/69167303/b3bdb01b-54e1-4030-9ed8-0ce0ea70d1bf)

**Comment by ssillerom** [comment]
that happens too when creating a new chat in the same chat profile

**Comment by willydouhard** [comment]
Thank you for your report, [here](https://github.com/Chainlit/chainlit/pull/651) is the fix. Will be released tomorrow!

**Comment by ssillerom** [comment]
Thanks dude, you are amazing!

**Comment by willydouhard** [comment]
Should be fixed with the latest release!
