### ISSUE TITLE
Chainlit UI breaks after a file is sent on user message. The file size is ~ 20 mb which is a response from smartdataframe as a markdown

### ISSUE THREAD

**Issue by suman12345678** [Chainlit/chainlit#649]
Chainlit UI breaks after a file is sent on user message. The file size is ~ 20 mb which is a response form smartdataframe. FIle is sent correctly but after that chainlit UI becoms irresponsive. Is there any settings I need to change?

**Comment by willydouhard** [comment]
What version of chainlit are you using?

**Comment by suman12345678** [comment]
Hi Chainlit/chainlit
I am using version 0.7.2 when I try to send a dataframe of size ~ 20 mb it
works fine. But when I try to send same dataframe as markup it's getting
stuck.

**Comment by willydouhard** [comment]
Please upgrade 1.0.0, this bug should be fixed. Here is the [migration guide](https://docs.chainlit.io/guides/migration/1.0.0).
