### ISSUE TITLE
Input widget "SELECT" doesn't change the value of the variable

### ISSUE THREAD

**Issue by tamil-acog** [Chainlit/chainlit#658]
Hi,

I followed this [docs](https://docs.chainlit.io/api-reference/input-widgets/select) to incorporate a select option in my app. However, when I select any option, it doesn't seem to change.

For example:
```
settings = await cl.ChatSettings(
        [
            Select(
                id="Model",
                label="OpenAI - Model",
                values=["gpt-3.5-turbo", "gpt-4-1106-preview"],
                initial_index=0,
            ),
            Select(
                id="caching",
                label="Caching",
                values=["True", "False"],
                initial_index=0,
            ),
        ]
    ).send()
    model = settings["Model"]
    caching = settings["caching"]
    print("model", model)
    print("caching", caching)
```
The above code, no matter what I select from drop down always prints model as "gpt-3.5-turbo" and caching as "True" in the terminal. Am I missing anything here?

**Comment by willydouhard** [comment]
You have to use [@cl.on_settings_update](https://docs.chainlit.io/api-reference/chat-settings) to listen for updates.

**Comment by tamil-acog** [comment]
Thanks man! It worked.
