### ISSUE TITLE
How to show Pandas DataFrame in Chainlit?

### ISSUE THREAD

**Issue by daviddwlee84** [Chainlit/chainlit#665]
Hi, I am new to Chainlit.

I am wondering if it is possible to render Pandas DataFrame similar to what Streamlit does

- [Dataframes - Streamlit Docs](https://docs.streamlit.io/library/advanced-features/dataframes)
- [st.dataframe - Streamlit Docs](https://docs.streamlit.io/library/api-reference/data/st.dataframe)

Attempts: 

I haven't found DataFrame-related [Element](https://docs.chainlit.io/concepts/element) in the API Reference document:

> [Text](https://docs.chainlit.io/api-reference/elements/text)
> [Image](https://docs.chainlit.io/api-reference/elements/image)
> [File](https://docs.chainlit.io/api-reference/elements/file)
> [PDF viewer](https://docs.chainlit.io/api-reference/elements/pdf)
> [Audio](https://docs.chainlit.io/api-reference/elements/audio)
> [Video](https://docs.chainlit.io/api-reference/elements/video)
> [Avatar](https://docs.chainlit.io/api-reference/elements/avatar)
> [Plotly](https://docs.chainlit.io/api-reference/elements/plotly)
> [Pyplot](https://docs.chainlit.io/api-reference/elements/pyplot)
> [TaskList](https://docs.chainlit.io/api-reference/elements/tasklist)

And I found the demo video was able to render DataFrame (but haven't found the source code yet)

https://github.com/Chainlit/chainlit/assets/13104895/8882af90-fdfa-4b24-8200-1ee96c6c7490

Directly returning DataFrame or using `df.to_html()` at a `@cl.step` function didn't do the trick.

**Comment by willydouhard** [comment]
Chainlit support markdown so you can use markdown tables. Here is an [example](https://github.com/Chainlit/cookbook/blob/main/bigquery/app.py#L82) to convert a DF to a markdown table

**Comment by desertproject** [comment]
I believe #1373 is on the way to implement this feature. Hopefully, it will be available soon!
