### ISSUE TITLE
clipboard is undefined when using http to access, so the copy button doesn't work!

### ISSUE THREAD

**Issue by qianghuangwhu** [Chainlit/chainlit#670]
clipboard is undefined when using **_http_** to access, You can see this for detials:
https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

Thanks!

#660

**Comment by willydouhard** [comment]
Ah I see, however you should deploy with https when you are not serving the app on localhost. Any reason you can't do that?

**Comment by qianghuangwhu** [comment]
> Ah I see, however you should deploy with https when you are not serving the app on localhost. Any reason you can't do that?

I totally agree with you, I have configured **_https_** service, and it works fine now. Thanks!

**Comment by willydouhard** [comment]
Awesome! Closing the issue then.
