### ISSUE TITLE
Username is always "You"

### ISSUE THREAD

**Issue by zulven** [Chainlit/chainlit#672]
It looks like on the react side, name is always set to "You" if the message type is "user_message". Seems impossible to rename the user from app.py. Shouldn't author renaming be allowed?

This is the code in the react file:
o=t.type==="user_message", s=o?"You":t.name

**Comment by willydouhard** [comment]
This is the intended behaviour at the moment. Could be enhanced by enabling author rename to work or using the user identifier if authentified.

**Comment by zulven** [comment]
Thanks for the quick reply!
