### ISSUE TITLE
COLLAPSE_MIN_LINES

### ISSUE THREAD

**Issue by cccc11231** [Chainlit/chainlit#675]
is there a way to modify these numbers?

const COLLAPSE_MIN_LINES = 25; // Set this to the maximum number of lines you want to display before collapsing
const COLLAPSE_MIN_LENGTH = 3000; // Set this to the maximum number of characters you want to display before collapsing

**Comment by cccc11231** [comment]
also, can someone confirm that newer version has removed the download icon button?
![image](https://github.com/Chainlit/chainlit/assets/131196441/516d0d3b-4a64-455a-99ed-c9c10846644f)

**Comment by willydouhard** [comment]
Currently you cannot modify these values. I confirm we removed the download button because we added a copy button below messages.

**Comment by cccc11231** [comment]
got it. thanks. currently, is there a feature that we can download or share the chat?

**Comment by willydouhard** [comment]
Sharing a chat is coming!

**Comment by cccc11231** [comment]
![image](https://github.com/Chainlit/chainlit/assets/131196441/91284520-dbb6-449e-8b6a-f4a9dfdf3100)

Is there a plan to add an export feature in the future?

**Comment by willydouhard** [comment]
Opened to contributions!
