### ISSUE TITLE
PDF elements aren't correctly displayed in the chat window

### ISSUE THREAD

**Issue by mirekevertz** [Chainlit/chainlit#684]
![Chainlit_bug](https://github.com/Chainlit/chainlit/assets/147809137/ce9756cd-2f05-410e-a09f-c8ea5d5bd24c)
As you can see in the image above, PDF links aren't correctly displayed if they contain parenthes. Here is the code that caused the issue:
elements.append(cl.Pdf(name="\\\\path\\to\\(1)data.pdf", display="side", url="test", path="mypath.pdf", page=doc_page))

**Comment by willydouhard** [comment]
I think this is clashing with markdown parsing. Will check if we can fix that
