### ISSUE TITLE
Feedback failed with literalai

### ISSUE THREAD

**Issue by lw3259111** [Chainlit/chainlit#693]
Mycode 
<img width="519" alt="image" src="https://github.com/Chainlit/chainlit/assets/12690488/9a4db9a8-4cf9-4d4a-a6eb-3bdf034ccc1e">

<img width="869" alt="image" src="https://github.com/Chainlit/chainlit/assets/12690488/205e0594-014c-41d8-9c31-a12f129638e3">

**Comment by willydouhard** [comment]
You need to call .send() on the message once the streaming is done.

**Comment by lw3259111** [comment]
@willydouhard 
ok!
