### ISSUE TITLE
Get user locale server-side 

### ISSUE THREAD

**Issue by hanfi** [Chainlit/chainlit#695]
hi 

i send a welcome message to client using cl.Message, i need to have the user locale to send the welcome message in the correct language.

i searched and i can't put my hand on a way to get the user browser language in the python side of the project.

does any one have an idea on how i can have this ?

thanks a lot

**Comment by l4time** [comment]
I have the same issue. I'm struggling to make my Chainlit app dynamically adjust the language for my LLM queries.

The current translation feature lets us change Chainlit's interface language using .json files but doesn't give direct access to the user's locale.

It would be great to have the user's locale as a default user session variable.

**Comment by francisjervis** [comment]
This appears to be "fixed" now @hanfi @l4time - the following works
```@cl.on_chat_start
async def start():

    l = cl.user_session.get("languages")

    print(l)```
    
    outputting eg ```en-US,en;q=0.9,es;q=0.8,fr;q=0.7```.

See https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/user_session.py#L33
    
    This does not appear to be documented yet @tpatel
