### ISSUE TITLE
[Feature Request] Recorded Speech pop up as audio file so LLM can utilize to convert Speech-to-text

### ISSUE THREAD

**Issue by Girrajjangid** [Chainlit/chainlit#696]
Thank you team for making such amazing library. It completely change the way we interact with UI. 
I am facing one challenge.
I wanted to record user voice and then pass it to speech to text model. I don't know how can I achieve this right now.
Any guidance would really appreciated.

**Comment by tpatel** [comment]
Hello, you should set `speech_to_text.enabled` to `true` in the [configuration](https://docs.chainlit.io/backend/config/features#default-configuration).

In your `.chainlit/config.toml`, you should change:

```
[features.speech_to_text]
    enabled = true # set this to `true`
    language = "en-US" # set this to the language, you can choose from https://github.com/JamesBrill/react-speech-recognition/blob/HEAD/docs/API.md#language-string
```

Note that this uses the browser speech to text engine, and the experience is only optimal in Chrome.

**Comment by tpatel** [comment]
If the browser speech to text engine isn't enough for you, you can follow this issue: https://github.com/Chainlit/chainlit/issues/626

**Comment by Girrajjangid** [comment]
Thanks @tpatel I followed that #626 , It's not working now.

**Comment by tpatel** [comment]
You're correct, I wanted to say: #626 is the place where the future update will happen.
Right now, only the browser speech to text is supported.
