### ISSUE TITLE
Not working out of the box

### ISSUE THREAD

**Issue by snovaisg** [Chainlit/chainlit#697]
Just wanted to quickly try this, but both the hello-world (from running `chainlit hello`) and the python demo give me the same error "Object.hasOwn is not a function. (In 'Object.hasOwn(e,E.from)', 'Object.hasOwn' is undefined)".

Chat tab:
<img width="1355" alt="Screenshot 2024-01-25 at 17 00 54" src="https://github.com/Chainlit/chainlit/assets/24900912/009c286a-1442-4388-a789-7abd3322f77b">

Readme tab: 
<img width="1355" alt="Screenshot 2024-01-25 at 17 00 59" src="https://github.com/Chainlit/chainlit/assets/24900912/3cb13b2c-3290-405d-a951-d8a79d7591c0">

**Comment by willydouhard** [comment]
What browser and version are you using?

**Comment by snovaisg** [comment]
Safari 15.1

Didn't think that would be an issue, but It indeed works on chrome. Thanks!
