### ISSUE TITLE
Message don't always get updated on the UI

### ISSUE THREAD

**Issue by thehapyone** [Chainlit/chainlit#698]
Hi, I have been using this framework for a while and I think it's really great. I have notice a situation where message don't get updated or sent to the UI. It seems the task gets discarded somehow.

For example, in the following code below during the on_chat_start
```python
files = await cl.AskFileMessage(
    content=intro_message,
    disable_feedback=True,
    accept=[
        "text/plain",
        "application/pdf"
    ],
    max_size_mb=10,
    max_files=5,
    timeout=300,
).send()

msg = cl.Message(
content=f"Now, I will begin processing {len(files)} files ..."
)
await msg.send()

# process files - Note: this is a blocking operation
retriever = await process_files(files)
# Let the user know that the system is ready
file_names = "\n  ".join([file.name for file in files])
msg.content = (
"The following files are now processed and ready to be used!\n"
f"  {file_names}"
)
print("done1")
await msg.update() # This update never gets sent if the process file takes some time
await cl.sleep(1) # This delay added here gives a chance for the message below to get sent sometimes. The higher the value the more likely it gets sent
print("done2")
await cl.Message(
content=f"done processing..."
).send() # This message occassionally gets sent depending on how long it takes for the process_files section
print("done3")
```

Overall, it seems when there is a blocking task and when that task finish the msg.update(() never gets sent to the UI and for messages to get updated I needed to increase the delay value. Note, all the print statement works.

Any idea why this behaviour?

**Comment by saimurali52944** [comment]
I am having the same issue while running the ChainLit app with GPT-4. Specifically, when posing longer questions that require additional processing time, there is a delay in receiving a response from GPT-4. However, even after obtaining the response, the frontend at localhost:8000 does not reflect the updated answer. The delay in frontend update becomes more apparent with more complex queries.

**Comment by s-jse** [comment]
I am having a similar issue when sending a message to the front-end in an `on_chat_start` function.
I check that when I refresh the browser this function gets called in the back-end, but the message is sometimes shown in the front-end, and sometimes is not.

**Comment by thehapyone** [comment]
Yes, when I moved `process_files` towards a true async function the messages now get delivered. So it seems long running blocking operation sorts of timeouts the serer.
