### ISSUE TITLE
PDF Element linking to external source not persisted

### ISSUE THREAD

**Issue by dat-leth** [Chainlit/chainlit#700]
### Description
I've encountered an issue where the PDF element that links to an external source is not being persisted. I am using the Data Persistence feature with Literal AI (formerly Chainlit Cloud). Specifically, when I reopen an old thread, the PDF element is missing. I.e., during a new chat, the PDF element is open-able via the link in the message. However, when re-opening the thread, the same link is no longer available. The PDF element is also not found as an attachment on cloud.getliteral.ai. This seems to be a potential bug, but I am unsure if this behavior is intended or not.

### Steps to Reproduce
1. Define callback on receiving a new message from the user.
```python
@cl.on_message
async def main(message: cl.Message):
    image = cl.Image(path="./data/test_welcome.png", name="image1", display="inline")
    pdf = cl.Pdf(name="pdf1", url="https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf", display="side")
    text = cl.Text(name="text1", content="miau", display="side")
    # Attach the image to the message
    await cl.Message(
        content=f"This message has an image! image1, pdf1, text1"
        elements=[image, pdf, text],
    ).send()
```
2. Create a new chat in the browser.
3. Create a new message and interact with the elements.
4. Close the browser or switch threads.
5. Reopen the same thread.

### Expected Behavior
The PDF element linking to an external source should be persistent and visible upon reopening the thread.

### Actual Behavior
The PDF element is missing when the thread is reopened.

### Potential Cause
I have identified some lines of code that seems to be causing this issue:

[chainlit/element.py:126](https://github.com/Chainlit/chainlit/blob/4c08c24c807ac5e075646845827c9826bbed888a/backend/chainlit/element.py#L126)
```python
@dataclass
class Element:
    # [... omitted ...]
    async def _create(self) -> bool:
        if (self.persisted or self.url) and not self.updatable:
            return True
        # [...]
```

### Additional Information
- Chainlit version: 1.0.101, 1.0.200

It would be helpful to get clarification on whether this is a bug or intended functionality, and if it's a bug, any guidance on potential fixes would be appreciated. I'd be able to create a corresponding pull request.

**Comment by PawelMorawian** [comment]
Hi. thank you for this bug report, I was able to reproduce the bug. I am working on a fix.

**Comment by willydouhard** [comment]
Should be fixed with today's release!
