### ISSUE TITLE
date input widget filter

### ISSUE THREAD

**Issue by ggnicolau** [Chainlit/chainlit#706]
Hi,

Is it possible to add a date window widget to use as a filter as we've in streamlit already?

**Comment by tpatel** [comment]
Hi, can you share more about this date window widget, is this something you want to use in the [chat settings](https://docs.chainlit.io/advanced-features/chat-settings)?

**Comment by ggnicolau** [comment]
Hi, @tpatel! Sorry for the late response. It's something like a calendar widget that the user can use it and pass as an input and we use it as a filter. Something like in this discussion for streamlit:

https://discuss.streamlit.io/t/calendar-widget/39220/2

This as an old discussion, I'm almost certain that Streamlit already has it implemented. I remember to see it somewhere and find in the documentation. But I couldn't find it again right now.

But it's something like this picture:

![b65d563830a62c6527452d749d6f4369cd718e6f](https://github.com/Chainlit/chainlit/assets/79374447/cbde3377-f1b7-4fc6-bc22-60d2656c508d)

**Comment by ggnicolau** [comment]
Hi, @tpatel! Sorry for the late response. It's something like a calendar widget that the user can use it and pass as an input and we use it as a filter. Something like in this discussion for streamlit:

https://discuss.streamlit.io/t/calendar-widget/39220/2

This as an old discussion, I'm almost certain that Streamlit already has it implemented. I remember to see it somewhere and find in the documentation. But I couldn't find it again right now.

But it's something like this picture:
![b65d563830a62c6527452d749d6f4369cd718e6f](https://github.com/Chainlit/chainlit/assets/79374447/09209ee4-8dcd-4f34-af7d-fa1f211f3b34)
