### ISSUE TITLE
How can I implement feedback buttons and consequently, sending the feedback data to Literal AI?

### ISSUE THREAD

**Issue by abhat-koppert** [Chainlit/chainlit#713]
Hi, 

My colleague and I are trying to set up a custom frontend by making use of the example in chainlit's [cookbook repository](https://github.com/Chainlit/cookbook/tree/main/custom-frontend). We have a Literal AI cloud account set up and were able to make a basic feedback system there. 

However, we are not sure how to go about implementing it on the custom react frontend. What should we call? Should we make use of the Literal AI typescript client? Or should we implement it on the backend? If so, how do we send the feedback response? 

Please let us know at the earliest.

**Comment by constantinidan** [comment]
Hi @abhat-koppert! 
Can you shoot me an email at dan@chainlit.io? We'll schedule a call to deep dive on your use case.
Thanks!
