### ISSUE TITLE
logging chat response in cloud.getliteral.ai

### ISSUE THREAD

**Issue by easygoingeric** [Chainlit/chainlit#714]
We're using cloud.getliteral.ai to log user interactions and feedback.  The feedback and the question from the user gets logged, but the response back from the language model is blank.  Is this a bug or does an additional step need to be taken?

**Comment by willydouhard** [comment]
Do you stream the response of the model? If so do you call .send() once the streamed is finished?

**Comment by easygoingeric** [comment]
We were doing "Trick: Display a loader while waiting for a response" where it sends the blank message to display the loader.  When removing this line, the response from the language model shows up in literal.  
https://docs.chainlit.io/concepts/message

**Comment by willydouhard** [comment]
Then try to call `await msg.update()` once the stream is over.
