### ISSUE TITLE
File element in message

### ISSUE THREAD

**Issue by cccc11231** [Chainlit/chainlit#715]
I recently encountered an issue where the message doesn't display the file element, even when using the sample code:

import chainlit as cl
@cl.on_chat_start
async def start():
    elements = [
        cl.File(
            name="test.py",
            path="./test.py",
            display="inline",
        ),
    ]
    await cl.Message(
        content="This message has a file element", elements=elements
    ).send()

then I found out that it's due to custom_css in config.toml. if I specify this fied, then the file element does not show up.

anyone has any idea about this?

![image](https://github.com/Chainlit/chainlit/assets/131196441/0e318d20-ec52-400f-ac75-69dc6055b906)
![image](https://github.com/Chainlit/chainlit/assets/131196441/9baf8380-1d52-48bc-af53-37cb55510817)
![image](https://github.com/Chainlit/chainlit/assets/131196441/f735bfc9-bf93-436e-9148-f284e0dbd1bd)

**Comment by willydouhard** [comment]
Wow interesting, what is the content of that css file?

**Comment by cccc11231** [comment]
/* Hide the chat tab on top left */
.css-1mzerio {
  visibility: hidden;
}

this is content of css file. basically just want to hide this button..
![image](https://github.com/Chainlit/chainlit/assets/131196441/5311f994-3448-4cc5-bc7c-b88dab938bcc)

**Comment by willydouhard** [comment]
Then the file element probably share that class i'd say. Try a more specific selector including the parent of the button you want to hide.
