### ISSUE TITLE
set latex=true in config.toml not works for mathematical formula

### ISSUE THREAD

**Issue by qianghuangwhu** [Chainlit/chainlit#716]
# Chainlit version
- Chainlit 1.0.100

@willydouhard Hi, when i set _latex=true_ in config.toml not works for mathematical formula:
## 1. settings in config.toml file
![截屏2024-02-01 下午4 45 59](https://github.com/Chainlit/cookbook/assets/62199595/13219d89-1da1-41dd-80dc-1646b3504320)
## 2. mathematical formula display
![截屏2024-02-01 下午4 46 19](https://github.com/Chainlit/cookbook/assets/62199595/11d71617-4217-4d4e-9a12-351f9ec25707)

why set _latex=true_ in issue #604 works? Am I missing a dependency package for rendering mathematical formulas?

**Comment by willydouhard** [comment]
We only support the $ notation

**Comment by qianghuangwhu** [comment]
> We only support the $ notation

@willydouhard, Hi Willy, I use a system prompt to solve this issue:
```python
system_prompt = """
You are a helpful assistant. 
If you have mathematical formulas in your output, please use $ to wrap mathematical equations and mathematical symbols in your output! For example: $ x^2 + 2x + 1 = 0 $, $ a^2 + b^2 = c^2 $ and $x$.
Do not use \[ and \] or \( and \) to wrap equations. For example: \[ x^2 + 2x + 1 = 0 \] or \( x^2 + 2x + 1 = 0 \) or \( x \).
"""
```
I tested some mathematical formulas and basically all of them display normally. 
![截屏2024-02-01 下午10 14 45](https://github.com/Chainlit/chainlit/assets/62199595/fee04be4-fba4-4a85-bf69-8ef8140ba272)

**Comment by qianghuangwhu** [comment]
> Is the direct notation coming from OpenAI now supported ? I still see its not working?

Probably not supported yet.
