### ISSUE TITLE
Human Feedback on Custom React Client

### ISSUE THREAD

**Issue by NisaarAgharia** [Chainlit/chainlit#718]
How to enable Human Feedback on Custom React Client code?

Can you give me some examples.

**Comment by yash1996** [comment]
Yes we need a way to get custom UI added to capture feedback

**Comment by NisaarAgharia** [comment]
I recently came across Literal AI Typescript client, It has the Function to add Feedback. 

is this the way we add feedback, need someone to shed some light on it . 

[typescript-client](https://www.npmjs.com/package/@literalai/client)

[Literal-docs](https://docs.getliteral.ai/introduction)

**Comment by willydouhard** [comment]
Nope, the literal typescript client is made for developers building non chainlit applications in typescript. To add a feedback with a custom react application, you should call[ this chainlit endpoint](https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/server.py#L527)

**Comment by NisaarAgharia** [comment]
So i have chainlit backend with custom react frontend. Connected via the new react chainlit api client.

Should i use the one you suggested @willydouhard

**Comment by willydouhard** [comment]
Yes, this is how we do it in the main chainlit ui

**Comment by NisaarAgharia** [comment]
thanks @willydouhard , Will Implement this and let you know.

**Comment by NisaarAgharia** [comment]
hi @willydouhard , we have a custom Frontend in react, we are trying to implement Google Oauth, we are trying to use chainlit backend app to create a new endpoint for google login.

- we want to know how to call it from the UI?

- Do we need to create a different api service for authentication or can it be a part of chanlit app?

- what is the best way to implement login for chainlit backend with React frontend. where we use the new react chainlit client library

**Comment by ModEnter** [comment]
Hello, [this page](https://docs.chainlit.io/authentication/oauth) explains how to setup OAuth in Chainlit
