### ISSUE TITLE
Unprocessable Entity: [object Object]

### ISSUE THREAD

**Issue by tjohn88** [Chainlit/chainlit#720]
Hello!

I tried to clear install chainlit. Installation has successfully completed, but I have an error when first start:
>>> chainlit hello
![2024-02-02_09-38-56](https://github.com/Chainlit/chainlit/assets/116616313/3eef122e-a184-4c13-b59b-df2c2c916695)
![2024-02-02_09-39-39](https://github.com/Chainlit/chainlit/assets/116616313/73218796-657a-4a92-b4a5-2376b4c2dc34)
Please help me

**Comment by tjohn88** [comment]
Ok. I resolved this problem by deleting my entire python folder. Then reinstalled it. I think some packages was incompatible:thumbsup:

**Comment by LozanoJohan** [comment]
> Ok. I resolved this problem by deleting my entire python folder. Then reinstalled it. I think some packages was incompatible

how did you solve? i have the same error. chainlit is the only package i have
