### ISSUE TITLE
cl.step can't feedback?

### ISSUE THREAD

**Issue by lw3259111** [Chainlit/chainlit#723]
cl.step can't feedback?

![WX20240203-220703@2x](https://github.com/Chainlit/chainlit/assets/12690488/1d46f1d5-de29-4702-9a9b-27193be15e2f)

**Comment by willydouhard** [comment]
Set [disable_feedback](https://docs.chainlit.io/api-reference/step-decorator) to `False`.

**Comment by samosun** [comment]
> cl.step can't feedback?
> 
> ![WX20240203-220703@2x](https://private-user-images.githubusercontent.com/12690488/302040576-1d46f1d5-de29-4702-9a9b-27193be15e2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxOTA2OTIsIm5iZiI6MTcwNzE5MDM5MiwicGF0aCI6Ii8xMjY5MDQ4OC8zMDIwNDA1NzYtMWQ0NmYxZDUtZGUyOS00NzAyLTlhOWItMjcxOTNiZTE1ZTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDAzMzMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzOGQzZDY1ZDk2M2Y2NzVjNDhmOTMwOTc3N2M5MDcxYjk5ZDE0MmMyMDYwOTNhYWRlMDkzMzAwYTE2YjRjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0sqTIsc3kTZiBtPskRGZhftF7WtvOSr774WV1fCi6x4)

hi @lw3259111 , 我在学习chainlit应用，想请教下您是通过[Literal AI](https://cloud.getliteral.ai/) 实现的吗？

**Comment by samosun** [comment]
@lw3259111 你好，我在学习chainlit，想问下您是怎么实现 feedback功能的？是通过literalai吗？还是有其他方式实现

**Comment by lw3259111** [comment]
其他方式

---- Replied Message ----
| From | ***@***.***> |
| Date | 02/06/2024 13:51 |
| To | Chainlit/chainlit ***@***.***> |
| Cc | lw3259111 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [Chainlit/chainlit] cl.step can't feedback? (Issue #723) |

@lw3259111 您好，我在学习chainlit，想问下您是怎么实现 feedback功能的？是通过literalai吗？还是有其他方式实现
