### ISSUE TITLE
Possible to nest AskUserMessage under a step?

### ISSUE THREAD

**Issue by pchalasani** [Chainlit/chainlit#724]
[Pasting from discord] Is there some way to nest AskUserMessage at an inner level (i.e. not root)? E.g. in a multi-agent setup, when a nested sub-task requires user input, I need the input to show up at that level, not at root level. Thanks for this fantastic framework btw.

Agent A delegates to Agent B, hence all Agent B's steps are nested under Agent A. One of the steps of B might be to ask user input. When user inputs something, it should show up at the level of B, not A.

To be clear, I don't need the user prompt input box to be nested under the step. That is fine, but once the user responds, the response is immediately echoed back at root level, and this is what I want to change -- it should echo it under the step. In the attached pic, I want "Darth" to be nested at same level as What is Your name, which I was able to nest by patching the AskUserMessage to take a parent_id in its constructor. See this gist for a full MWE https://gist.github.com/pchalasani/a81dd178e31c1f9fcb240fad33a88729

<img width="375" alt="image" src="https://github.com/Chainlit/chainlit/assets/554347/f9b58c8e-4cdf-47df-a587-db25b6c1c652">

```
class AskUserMessageNested(AskMessageBase):
    """
    Patch of AskUserMessage that takes a `parent_id` in constructor, and
    sticks it into the `step_dict` to force the prompt to be nested under a step.
    The intent is that both the prompt and user answer should be nested under a step,
    but this only works partially -- i.e. the prompt does get nested, but the user answer
    is immediately echoed at root level. One of two things might help with nesting the user's 
    answer under the step:
    - a way to have the echoing of user input be under the given parent_id
    - a way to delete an already-echoed root-level user input, so that we can capture
      the user's response and render it ourselves under the step.
    """



    def __init__(
        self,
        content: str,
        author: str = config.ui.name,
        type: MessageStepType = "assistant_message",
        disable_feedback: bool = False,
        timeout: int = 60,
        raise_on_timeout: bool = False,
        parent_id: Optional[str] = None,
    ):
        self.content = content
        self.author = author
        self.timeout = timeout
        self.type = type
        self.disable_feedback = disable_feedback
        self.raise_on_timeout = raise_on_timeout
        self.parent_id = parent_id

        super().__post_init__()

    async def send(self) -> Union[StepDict, None]:
        """
        Sends the question to ask to the UI and waits for the reply.
        """
        trace_event("send_ask_user")
        if not self.created_at:
            self.created_at = datetime.utcnow().isoformat()

        if config.code.author_rename:
            self.author = await config.code.author_rename(self.author)

        if self.streaming:
            self.streaming = False

        self.wait_for_answer = True

        step_dict = await self._create()
        if self.parent_id:
            step_dict["parentId"] = self.parent_id

        spec = AskSpec(type="text", timeout=self.timeout)

        res = cast(
            Union[None, StepDict],
            await context.emitter.send_ask_user(step_dict, spec, self.raise_on_timeout),
        )

        self.wait_for_answer = False

        return res
      

import chainlit as cl


@cl.on_chat_start
async def main():
    step = cl.Step(name="Root", type="step")
    step.output = "Say something"
    await step.send()

    # ask user's name, NESTED under this step.
    # The QUESTION does get nested, but user's answer is immediately 
    # echoed at Root level, not under the step.
    
    res = await AskUserMessageNested(
        content="What is your name?",
        timeout=60_000,
        parent_id=step.id, # so it is nested under the step
    ).send()


```

**Comment by s0l4r** [comment]
I am wondering this too. Since the feature is similar I also post this here. It would be nice if AskActionMessage would support this, so that you can inject a confirmation in each step. Something like: 
```       
    def _run(
        self,
        query: str,
        step: Step,
        run_manager=None,
    ) -> str:
        """Use the Human input confirmation tool."""
            res = run_sync(cl.AskActionMessage(
            content=query,
            parent_id=step.id,
            timeout=10,
            actions=[
                cl.Action(
                    name="feedback",
                    value="feedback",
                    label="💬 Provide feedback",
                ),
                cl.Action( 
                    name="exit",
                    value="exit", 
                    label="🔚 Exit Conversation" 
                ),
                cl.Action(name="continue", value="continue", label="✅ Continue"),
                cl.Action(name="cancel", value="cancel", label="❌ Cancel"),
            ],
        ).send())
```

**Comment by pchalasani** [comment]
I forgot to update here, but I managed to solve this, without the need for overriding any classes. Two ideas:
- the `id` of a `cl.Message` can be used to create a new `cl.Step` with the same `id` and you can change its `name` or `content` fields and call `step.update()` to change it
- you can replace the `AskUserMessage` by a step (which can therefore be arbitrarily nested), and still leverage the "awaiting user input" functionality of the `AskUserMessage` so the user gets an input box to enter.

I'm probably explaining it badly. Here's how I solved it in Langroid: https://github.com/langroid/langroid/blob/main/langroid/agent/callbacks/chainlit.py
(see the `ask_user_step` and `show_first_user_message` methods).
Here's an example of how it looks.  Note how all the `Student` steps (including user input) are nested under the `Teacher` steps. 
<img width="1037" alt="image" src="https://github.com/Chainlit/chainlit/assets/554347/86a1e425-22cc-485a-8af6-4681aff69f8f">

**Comment by pchalasani** [comment]
To clarify/elaborate a bit -- my notion of "steps" and "nesting" is different from what the chainlit docs assume. I don't give any special status to "chain of thought". Instead, when agent A delegates to agent B, all steps of agen B are nested 1 level below those A.

**Comment by pchalasani** [comment]
closing this as solved
