### ISSUE TITLE
react-client's chatSettingsValue state not updating upon calling updateChatSettings

### ISSUE THREAD

**Issue by jannisbecker** [Chainlit/chainlit#726]
Hi,

In our custom react frontend I'm using the `chatSettingsValue` exposed by `useChatData()` to populate settings widgets, but also to show the currently applied settings elsewhere in the ui.

While implementing this, I assumed that, upon calling `updateChatSettings()` to apply some new settings, the `chatSettingsValue` state would also reflect the new values. 
Basically I assumed that `updateChatSettings()` would send the new settings to the backend, which would confirm the update and the react-client would then store the new settings.

Instead, it seems that the `chatSettingsValue` state only holds the values returned by the backend, but the backend does not return any new values when I apply new settings, so the state will be out of sync once I do so.

My workaround for now is to expose a setter for this state, and call it whenever I apply new settings
```jsx
const [_, setChatSettingsValue] = useRecoilState(chatSettingsValueState);
	
function save() {	
    // send settings to backend
    updateChatSettings(inputState);
    // update chainlit settings locally
    setChatSettingsValue(inputState);
}
```

**Comment by willydouhard** [comment]
At the moment it is up to the react app to update the settings state + call updateChatSettings
