### ISSUE TITLE
Providing application healthiness probe routes

### ISSUE THREAD

**Issue by a-recknagel** [Chainlit/chainlit#727]
Hi, I have a feature request.

I'd like to deploy chainlit in a kubernetes-managed cluster, which expects all web-applications to provide probe-endpoints that kubernetes can use in order to decide if a container is up-and-running or needs to be restartet: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

In short (while the linked document ist correct, it's also quite wordy):
 - I'd like to have three GET-routes in every running chainlit server that can be reached without authentication at `/startup`, `/health`, and `/liveness`. 
 - each of them will either respond with a status code of 200 and a simple `{"message": "OK"}` or a status code of 503
 - startup is successful once the server can receive traffic (model is loaded, all routes are set up, etc.) 
   - k8s[503]: "I wait and query again in x seconds"
   - k8s[200]: "I can now route traffic to this pod and will stop querying this route"
 - health is successful if the server can receive traffic (it can reach all its external dependencies, no resource is blocked)
   - k8s[503]: "I can't route traffic to this pod right now"
   - k8s[200]: "I can route traffic to this pod"
 - liveness is successful if the server process is running
   - k8s[503]: "The server process is dead, I need to restart the container"
   - k8s[200]: "All is well"
Some configurations also expect the health-route to be called `/healthz`, so it might be a good idea to provide configuration options.

**Comment by invokeinnovation** [comment]
Did you come up with a solution to this?
