### ISSUE TITLE
Element cl.Text with display="side" does not work.

### ISSUE THREAD

**Issue by pylanglois** [Chainlit/chainlit#729]
Using this example : https://docs.chainlit.io/api-reference/elements/text with chainlit=1.0.200

When I set display="side" nothing is rendered. 

![image](https://github.com/Chainlit/chainlit/assets/1401905/68e878be-1848-4fb6-b20c-da52bcf6dc46)

**Comment by willydouhard** [comment]
You need to have the element name mentioned in the message content to have the link displayed
