### ISSUE TITLE
Users are getting responses to questions asked by other users

### ISSUE THREAD

**Issue by tituslhy** [Chainlit/chainlit#733]
Hello!

I've developed a simple chainlit application using this link (https://docs.chainlit.io/integrations/llama-index) except that I'm using LLaMA2 instead of ChatGPT. The thing is when I have multiple users using the tool at the same time, they get responses to questions asked by other users instead of their own.

For e.g., user A asks "How do I troubleshoot issue A?" but gets the response to user B's question on "What are the main steps to implement solution B?" User A eventually gets a reply as well to his own question.

How do I fix this?

**Comment by willydouhard** [comment]
Did you instantiate one agent for all users ? Would have to look at the code to help

**Comment by tituslhy** [comment]
Oh sure! I just deployed the cookbook's code on a server for multiple users to play with. I'm thinking I should just store the "response_message = cl.Message(content="")" as a cl.user_session variable at the beginning of @cl.on_message to solve this problem.

**Comment by dokterbob** [comment]
Closed due to inactivity.
