### ISSUE TITLE
Every time I switch profiles or log in, I find it is very slow.

### ISSUE THREAD

**Issue by wuheyi** [Chainlit/chainlit#734]
version:1.0.200  
When I log in or switch profiles, I find that the following requests are sent：
    HTTP Request: POST https://cloud.getliteral.ai/api/graphql
Many requests were found from the network of chrome browser：
     ws/socket.io/
These requests seem to interact with chainlit cloud. Can these interactions be removed or the logic here optimized?

**Comment by ModEnter** [comment]
Hello, you can manually remove these interactions, but it is not part of chainlit's roadmap to add options to remove them at the moment. Feel free to make PRs, all contributions are welcomed !
