### ISSUE TITLE
How to interact with upload file from input message 

### ISSUE THREAD

**Issue by ericosmic** [Chainlit/chainlit#738]
how to build a chatbot interact with input file in multi-modality. 
My code attached below. But this code don't give respond. Where is wrong? 
<img width="723" alt="image" src="https://github.com/Chainlit/chainlit/assets/35327931/e52514c7-e96a-48eb-9945-b339665f40cb">

**Comment by willydouhard** [comment]
This looks OK to me, do you see any errors or does it just hangs? If so, can you put debug prints (or use a debugger) to find out which part is blocking?
