### ISSUE TITLE
Dynamically change placeholder text  in input box 

### ISSUE THREAD

**Issue by pchalasani** [Chainlit/chainlit#744]
A common scenario is where we want to give custom instructions in the chat input box at the bottom. 
Currently this is hardcoded `.chainlit/translations/en-US.json` as `...inputBox.input.placeholder = "..."`

A way to customize this from Python code would be very useful.

**Comment by shayan09** [comment]
You can change the placeholder message from `.chainlit/translations/en-US.json`

**Comment by nmstoker** [comment]
@shayan09 I think you may have misread what is being asked here.

What you stated is clearly known as it's referenced in the question and doing what you mention is not dynamic, which is the whole point of this question.
