### ISSUE TITLE
Backend changes not reflecting

### ISSUE THREAD

**Issue by parthdacoder** [Chainlit/chainlit#746]
I have an app.py file which as a demo was provided in one of your modules. I removed authentication, changed the welcome message and such changes are taking places at the react frontend too. But if I add a new function, no change appears on the frontend for example:

```
@cl.on_chat_start
async def on_chat_start():
    await cl.Avatar(
        name="Luminous Genie",
        path="chainlit/libs/react-components/src/elements/images.png",
    ).send()

    cl.user_session.set(
        "message_history",
        [{"role": "system", "content": "You are a helpful assistant."}],
    )
    await cl.Message(content="Connected with Lumie!").send()
```

Earlier the code was:

```
@cl.on_chat_start
async def on_chat_start():
    cl.user_session.set(
        "message_history",
        [{"role": "system", "content": "You are a helpful assistant."}],
    )
    await cl.Message(content="Connected to Chainlit!").send()
```

And the earlier code was working fine and changes made to the content were also reflecting in runtime. Please tell what the issue is and how can it be resolved?

**Comment by parthdacoder** [comment]
For reference:
![Frontend](https://github.com/Chainlit/chainlit/assets/122528926/923cbce9-a1ab-4ffd-b66f-406f9b3881b6)
Changes to the frontend section are taking place!

**Comment by willydouhard** [comment]
If I understand correctly you now have two `on_chat_start` functions? If that is the case, this is not supported, you should only declare one.

**Comment by parthdacoder** [comment]
No that is not entirely the case. If I add the following part of the code then that part gets executed:
@cl.on_chat_start
async def on_chat_start():
cl.user_session.set(
"message_history",
[{"role": "system", "content": "You are a helpful assistant."}],
)
await cl.Message(content="Connected to Chainlit!").send()
But if I remove this and add another on_chat_start function, I just get the default screen by chainlit:

![image](https://github.com/Chainlit/chainlit/assets/122528926/ee94c5c2-9508-4290-89fc-7fbbeaa17534)

**Comment by tpatel** [comment]
I'm trying to understand exactly what's the issue, are you using the `-w` argument when launching Chainlit (file watcher)?
