### ISSUE TITLE
Translation problems on Running text of spinner in the chatwindow

### ISSUE THREAD

**Issue by puppetm4st3r** [Chainlit/chainlit#747]
Hi, great job with Chainlit, I think there is a little bug with the Running label on the spinner in the chat window, may be the issue is related to the hardcoded 'Running' text in the next lines:

https://github.com/Chainlit/chainlit/blob/051d882381c6f3f686dfa4be3bac31d0e6937ebd/libs/react-components/src/messages/components/DetailsButton.tsx#L47

Best regards!

**Comment by puppetm4st3r** [comment]
Im running chainlit with spanish translation, and when I send to the UI an empty message in order to get the Running spinner it did not took the spanish translation and instead it display 'Running'

**Comment by willydouhard** [comment]
You are correct, adding this to the roadmap!

**Comment by puppetm4st3r** [comment]
thanks!

**Comment by puppetm4st3r** [comment]
Hi, there!
I got the same problem but now in the label of the user in the chatwindow, it is always "You" and there is no way to change it for other languajes.

![image](https://github.com/Chainlit/chainlit/assets/109969044/a354ea04-430b-410a-a77b-ffc1f3b750c8)

**Comment by puppetm4st3r** [comment]
Hi there, a found another text without translation (on server errors), i 'm using spanisg translate. (If you want I can do a merge request with the translation of spanish)

<img width="1027" alt="image" src="https://github.com/Chainlit/chainlit/assets/109969044/95c5102c-b3a9-4644-a319-1cfb63f4f81b">

**Comment by puppetm4st3r** [comment]
@willydouhard some other minor bugs attached to the thread
