### ISSUE TITLE
openai- -error

### ISSUE THREAD

**Issue by wupengfei0904** [Chainlit/chainlit#75]
I don't know why, but suddenly I'm experiencing communication failures with OpenAI. This has been the case from version 0.3 to 0.4. I'm not using langchain, just pure Python. I've checked my key and it should be able to communicate normally. I have my VPN turned on.

**Comment by willydouhard** [comment]
Hello, I don't think we changed anything about open ai in this release. What is the error you get? Sometimes OpenAI has some issues and is not able to process all the requests.

**Comment by wupengfei0904** [comment]
raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI

**Comment by willydouhard** [comment]
Is this happening 100% of the time or from time to time? My first guess is an issue on OpenAI's side.

**Comment by willydouhard** [comment]
If you use `acreate` you need to use `await`. Full example here https://docs.chainlit.io/concepts/streaming/python
