### ISSUE TITLE
Upgrade httpx version

### ISSUE THREAD

**Issue by wolvever** [Chainlit/chainlit#750]
Chainlit python backend has dependency constraint :

`httpx = ">=0.23.0,<0.25.0"
`
which cause my local httpcore lock on 0.17.3.

But many projects uses httpcore >= 1.0.0, so any chance to upgrade httpx to 0.26  ?

**Comment by wolvever** [comment]
httpx is required by literalai LiteralClient, it seems to be OK to upgrade literalai.  However this library is not available on github.  So any maintainer can upgrade liberalai and chainlit httpx dependency ?

**Comment by wolvever** [comment]
httpx is required by literalai LiteralClient, it seems to be OK to upgrade literalai. However this library is not available on github. So any maintainer can upgrade liberalai and chainlit httpx dependency ?

**Comment by willydouhard** [comment]
This fixed in the latest release!

**Comment by wolvever** [comment]
Thanks, confirmed on new version.
