### ISSUE TITLE
Integrating Frontend Page Information with Copilot on Page Load

### ISSUE THREAD

**Issue by lianghsun** [Chainlit/chainlit#755]
I would like to ask about the possibility of transmitting frontend page information to the content within `@cl.on_chat_start` each time a page initializes. The reason is the desire for Copilot to utilize different background information on various pages.

**Comment by willydouhard** [comment]
This is a good feature to add, currently the copilot can send messages to the frontend through functions, but the frontend cannot message the copilot. Adding this to the roadmap
