### ISSUE TITLE
Playground Template Recognitiion doesn't work anymore in current version 1.0.300

### ISSUE THREAD

**Issue by andrePankraz** [Chainlit/chainlit#758]
See title.
When I update 1.0.200 to 300, Playground cannot find template formats anymore.

**Comment by willydouhard** [comment]
You can follow the [migration guide](https://docs.chainlit.io/guides/migration/1.0.300). It should be fairly easy, basically some fields got renamed.

**Comment by andrePankraz** [comment]
oh...i didn't notice this intentional change, sry. in development mode we just get the updates and don't fixate the version. i thought it was some problem.

hmm, i think templates where the best feature of chainlit playgrounds.
langchain in the background uses templates heavily for scenarious above "Hello World"
for huge prompts with rag-chains and documents etc. the devision into template and variables etc. was a major plus - especially with the callback handler, that mostly just worked.
i don't really see an "improvment" with this.
the playground in this form is not much better than just using the official API-cloud-playgrounds, but may be I just don't get it.
