### ISSUE TITLE
Authentication of chainlit from company’s sso or LDAP

### ISSUE THREAD

**Issue by palash-fin** [Chainlit/chainlit#759]
I am struggling to find a solution to integrate my chainlit application to my companies ADS using ldap or SSO

going through the documentation it is hard to understand.

**Comment by lucebert** [comment]
There is a great example for implements custom oauth here : https://github.com/Chainlit/cookbook/pull/92/files

**Comment by rccl-aftellez98** [comment]
I was able to make it work with Micosoft Azure ADD Groups

.env should have something like:

# OAUTH 
OAUTH_AZURE_AD_CLIENT_ID=""
OAUTH_AZURE_AD_CLIENT_SECRET=""
OAUTH_AZURE_AD_TENANT_ID=""
CHAINLIT_AUTH_SECRET=""
OAUTH_AZURE_AD_ENABLE_SINGLE_TENANT=true

and code:

`@cl.oauth_callback
def auth_callback(provider_id: str, token: str, raw_user_data, default_app_user):
    if provider_id == "azure-ad":
        return default_app_user
    else:
        raise HTTPException(
            status_code=401,
            detail="Authentication failed: Unsupported provider or invalid token.",
        )`
