### ISSUE TITLE
Is there a way to change the display name of Readme in chainlit app?

### ISSUE THREAD

**Issue by PrashantSaikia** [Chainlit/chainlit#765]
I would like to have it replaced with something like "User Guide" or "Instructions". 

<img width="267" alt="Screenshot 2024-02-25 at 11 21 29 AM" src="https://github.com/Chainlit/chainlit/assets/39755678/1ad1960e-d86e-4693-855c-309bcc808179">

How do I do that? There's nothing in the [UI documentation](https://docs.chainlit.io/backend/config/ui) about this.

**Comment by puppetm4st3r** [comment]
in the new version you could do that with the JS injection feature, its overkilling but is better than nothing if there is not support for change in the settings.

**Comment by pranjal-ngi** [comment]
The js injection is not working. 
I added a custom.js file in the public folder and added custom_js = "/public/custom.js" in config.toml.  It does not show up in sources of inspect element.

**Comment by dahifi** [comment]
```app/.chainlit/translations/en-US.json
            },
            "header": {
                "chat": "Chat",
                "readme": "AWESOME"
            }
        }
 ```

**Comment by dahifi** [comment]
Above PR to add this to the customization overview and update Translation page.
