### ISSUE TITLE
User session changed after embedding using llamaindex

### ISSUE THREAD

**Issue by tjroamer** [Chainlit/chainlit#767]
I find the user session has been changed after I created an index in the on_message callback. I am using LlamaIndex to create index, the code is here:

```python

@cl.on_message
async def handle_message(message: cl.Message):
    file_paths = [element.path for element in message.elements if element.type == "file"]
    documents = SimpleDirectoryReader(input_files=file_paths).load_data()
    orig_session_id = cl.user_session.get("id")
    index = VectorStoreIndex.from_documents(documents)
    cur_session_id = cl.user_session.get("id")
    chat_engine = index.as_chat_engine(chat_mode=ChatMode.CONDENSE_QUESTION)
    // using chat_engine to handle message ....
```

Sometimes, the above code is not working, because the `orig_session_id` is not equal to `cur_session_id` after the indexing stage. It is not deterministic however. Sometimes, I did get the same ID.

What is the proper way to handle the document embedding on-the-fly?

Thanks.

**Comment by l4time** [comment]
How long is your embedding process? If it's longer than 30 seconds it will break Chainlit's event loop and create a new user session.
You may need to use chainlit make_async method to run the embedding in a separate thread to keep the event loop running:
[https://docs.chainlit.io/api-reference/make-async](https://docs.chainlit.io/api-reference/make-async)

**Comment by tjroamer** [comment]
It seems that I cannot reproduce this error any more. Not sure it was related to the embedding time. I remember that it occurred also when the embedding time was quite short (<10s). I will close this issue and will reopen if I have a reproducer. Thanks for your comments. It is good to know the session handling.
