### ISSUE TITLE
How to read URL parameters?

### ISSUE THREAD

**Issue by palmentropyc** [Chainlit/chainlit#774]
Hi everyone, I'm trying to obtain a URL parameter or find another way to identify a specific chat session in Chainlit, without using authentication. 

I'm looking for guidance on how to read URL parameters from within Chainlit, as accessing them directly from the Python backend seems not straightforward. Specifically, I'm unsure how to bridge the gap between the frontend (React or similar) and the Python backend to achieve this. 

**I.E if I run mydomain.com/?param1=hello, how can I read this from chainlit?**

Any advice or pointers on how to approach this within Chainlit? 

Thank you!

**Comment by puppetm4st3r** [comment]
with a fastapi middleware as interceptor may be it can be done.

**Comment by nmstoker** [comment]
In case you haven't seen it, there's a potential solution for this here: 

https://github.com/Chainlit/chainlit/issues/144#issuecomment-2071954807
