### ISSUE TITLE
Dark/light mode profile icons and message image icons

### ISSUE THREAD

**Issue by JamesLloydPartingtonSerendipityai** [Chainlit/chainlit#779]
Hello, Is there a way of setting a dark and light mode image icon for chat profiles? Also, is it possible to use image icons on chat message avatar icons? The only way I can think of changing these is through custom css/js, if so, what is the best way to check if the UI is using dark/light theme?

**Comment by ModEnter** [comment]
Hello, this enhancement is not in the roadmap, but it should not be hard to implement ; if you have the time, do not hesitate to make a PR to propose this feature in chainlit
