### ISSUE TITLE
Image not rendering in the Readme section

### ISSUE THREAD

**Issue by Shivanandroy** [Chainlit/chainlit#79]
I'm trying to render image along with some text in `chainlit.md` file. The image is not coming up in the UI. Its weird.

```markdown
# Title of my project

Some description

![](assets/image.jpg)  - This is not showing in the UI
```

**Comment by Shivanandroy** [comment]
@willydouhard  : Any update on this?

**Comment by willydouhard** [comment]
Will be fixed in today's release!

**Comment by willydouhard** [comment]
Just released, let me know if that fixes your issue :)

**Comment by Shivanandroy** [comment]
Thank you, 👍
