### ISSUE TITLE
Running on Azure VM - cannot start server

### ISSUE THREAD

**Issue by weasel4o** [Chainlit/chainlit#80]
Running on Azure Ubuntu 22.04 LTS VM. When starting any chainlit app, i get the following log error:
2023-06-17 20:25:07.236 ERROR   chainlit: Module should at least expose one of @langchain_factory, @on_message or @on_chat_start function
ERROR:    Exception in ASGI application
2023-06-17 20:25:15 - Module should at least expose one of @langchain_factory, @on_message or @on_chat_start function
2023-06-17 20:25:15.056 ERROR   chainlit: Module should at least expose one of @langchain_factory, @on_message or @on_chat_start function

Any ideas?

**Comment by willydouhard** [comment]
Hello, does your app file have one of @langchain_factory, @on_message or @on_chat_start function? would be easier if you could provide a code snippet

**Comment by weasel4o** [comment]
import torch
import gradio as gr
import transformers
from transformers import AutoTokenizer, AutoModelForCausalLM
from instruct_pipeline import InstructionTextGenerationPipeline
from langchain.llms import HuggingFacePipeline
from langchain import ConversationChain
from langchain.memory import ConversationBufferMemory
from langchain.document_loaders import PyPDFDirectoryLoader,PyMuPDFLoader
import chainlit as cl
from langchain import PromptTemplate, LLMChain

# Load docuemnts

# loader = PyMuPDFLoader("example_data/layout-parser-paper.pdf")
# data = loader.load()

model_path = "tiiuae/falcon-7b-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_path)
tokenizer.pad_token_id = tokenizer.eos_token_id

model = AutoModelForCausalLM.from_pretrained(
    model_path, trust_remote_code=True, torch_dtype=torch.bfloat16, device_map="auto"
)
# InstructionTextGenerationPipeline
pipeline = transformers.pipeline(
        task="text-generation",
        model=model,
        tokenizer=tokenizer,
        torch_dtype=torch.bfloat16,
        trust_remote_code=True,
        device_map="auto"
)

local_llm = HuggingFacePipeline(pipeline=pipeline)

conversation_buff = ConversationChain(llm=local_llm, memory=ConversationBufferMemory())


template = """
You are an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

{question}

"""

@cl.langchain_factory(use_async=True)
def factory():
    prompt = PromptTemplate(template=template, input_variables=["question"])
    llm_chain = LLMChain(prompt=prompt, llm=local_llm, verbose=True)

    return llm_chain

**Comment by willydouhard** [comment]
My only guess is that the code before the langchain_factory takes a long time to execute or never succeed to execute. hence the factory is never registered. Could you add prints in your code to make sure everything is executing correctly?
