### ISSUE TITLE
socket.io error when using custom react as frontend and chainlit as backend on cloud, local it works

### ISSUE THREAD

**Issue by suman12345678** [Chainlit/chainlit#804]
**Describe the bug**
When I use custom react as frontend and chainlit as backend, sometimes the backend endpoint call from react frontend doesnot work. This works in local system. But when I deploy chainlit server as a docker in cloud, sometimes it waits.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wxp16** [comment]
Hello @suman12345678 How did you fix the above issue? I encountered the same issue for my chainlit ui which is deployed in GCP
