### ISSUE TITLE
Customizing the favicon

### ISSUE THREAD

**Issue by sebderhy** [Chainlit/chainlit#81]
Hi, I want to customize the favicon for the chatbot I'm building (I'd like to put an emoticon such as 🐤 as favicon instead of the chainlit logo). Is there a way to do that in the current version of Chainlit?

**Comment by willydouhard** [comment]
This is not possible yet, will be coming with the theme customisability features

**Comment by willydouhard** [comment]
This is now possible! Docs [here](https://docs.chainlit.io/concepts/customization/custom-logo-and-favicon).
