### ISSUE TITLE
Allow dynamic adjustment of chainlit ChatSettings

### ISSUE THREAD

**Issue by tituslhy** [Chainlit/chainlit#810]
Hello!

**Is your feature request related to a problem? Please describe.**
I think that most people use the chainlit ChatSettings (https://docs.chainlit.io/api-reference/chat-settings) tool to set LLM model related settings such as temperature. 

But I've been using the ChatSettings tool as a channel directory for the user to choose which data source they'd like to talk to. Some users might want to refer to administrative manuals while some users want to talk to their own uploaded documents. I have different llamaindex query engines over each different data source. I deliberately designed my chainlit app this way so that there is no data contamination. 

**Describe the solution you'd like**
Users now have to toggle between each chat setting manually to choose their data source. But actually we can adjust the data source on the backend using the cl.user_session variable. So when I detect that the user has uploaded a document with the message, I'll automatically change the document source to the "Uploaded Documents" channel (i.e. cl.user_session.set("document_source") = "uploaded documents"). 

However there is currently no way to automatically port this change to the Chainlit ChatSettings tool - i.e. the ChatSettings does not automatically update itself to show that it's talking to uploaded documents. This is purely optics of course, the users can still just manually adjust it themselves.

**Describe alternatives you've considered**
At the start of every LLM response, I get Chainlit to inform the user via a chainlit Message object on which document source it's constructing the answer from. So that the end user can manually toggle the app to point at a different data source.

I can also prevent any reading of uploaded documents if the user does not toggle to the "Uploaded Documents" channel but I decided against this because Chainlit has an upload button with the message bar by default.

**Comment by Valdanitooooo** [comment]
I found that resending `ChatSettings` when switching `ChatProfiles` can achieve the effect of dynamically switching configurations
```   
    if profile == "test01":
        settings = await cl.ChatSettings(
            [
                Select(
                    id="xxx",
                    label="xxx",
                    values=[
                        "xx01",
                        "xx02"
                    ],
                    initial_index=0,
                )
        ).send()
    else:
        await cl.ChatSettings([]).send()
```
