### ISSUE TITLE
Chainlit executable not found in $PATH: unknown

### ISSUE THREAD

**Issue by GianfrancoFois** [Chainlit/chainlit#812]
I'm using Chainlit to run my app with a Dockerfile. It suddenly stopped working when pip installed the version 1.0.401. The error was `chainlit executable not found in $PATH: unknown`. 
Temporarily I was able to keep it working by forcing version 1.0.400 to be installed

**Comment by ModEnter** [comment]
This means that you did not add chainlit to your path. Add the pip package to your path (for example by adding the package's path to your bashrc)
