### ISSUE TITLE
does not starts on windows 10

### ISSUE THREAD

**Issue by snarb** [Chainlit/chainlit#82]
conda create --name chainlit-env python=3.9
conda activate chainlit-env 
pip install chainlit
chainlit hello
'chainlit' is not recognized as an internal or external command,
operable program or batch file.

**Comment by willydouhard** [comment]
This means that the chainlit executable is not in your PATH (happens sometimes on windows). You should see a message asking you to add it to your PATH with the actual path to the chainlit executable at the end of the pip install output.

**Comment by isuru0x01** [comment]
> This means that the chainlit executable is not in your PATH (happens sometimes on windows). You should see a message asking you to add it to your PATH with the actual path to the chainlit executable at the end of the pip install output.

There is no message asking to add chainlit to the path. How can I find the chainlit installed path?
