### ISSUE TITLE
Will not write code? At all?

### ISSUE THREAD

**Issue by PhiliptheGinger** [Chainlit/chainlit#820]
**Describe the bug**
Even an attempt to output a code that prints "hello world" fails, or at the very least, is incredibly slow.

**To Reproduce**
1. Open Chainlit with chainlit hello
2. Type your name, all that.
3. Please write me a code that prints "hello world".
4. Wait forever, I guess?

**Expected behavior**
I expected chainlit to write a code that prints "hello world."

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome
 - Version 122.0.6261.118

**Comment by jxraynaud** [comment]
Hum, the chainlit hello command does nothing. It asks your name and generate a preformatted message. There isn't any llm behind it to handle the message you're sending. It's just here to check that your pip install worked nothing else.
Somebody needs to cleanup this issue are there isn't any bug here. OP doesn't understand/read the docs.

**Comment by ModEnter** [comment]
This is expected behaviour, since chainlit hello does not rely on any LLM and simply displays "Hello + name".
