### ISSUE TITLE
How to add a custom async function?

### ISSUE THREAD

**Issue by JINO-ROHIT** [Chainlit/chainlit#826]
Im trying to do RAG with llamaindex and i want a evaluation pipeline to run async after the result is returned, how to do this?
i feel like im doing it wrong, adding code snippet here.

async def evaluate_response(evaluator_llama, prompt, response):
    eval_result = evaluator_llama.evaluate_response(query = prompt, response = response.get_response())
    return eval_result

@cl.on_message
async def main(message: cl.Message):
    query_engine = cl.user_session.get("query_engine")
    response = await cl.make_async(query_engine.query)(message.content)

    prompt = message.content

    evaluator_llama = cl.user_session.get("evaluator_llama")
    eval_result = await evaluate_response(evaluator_llama, prompt, response)
    print(eval_result)

    response_message = cl.Message(content="")

**Comment by ModEnter** [comment]
This is not a bug. Please ask the code-related questions to the Chainlit's Discord server (https://discord.gg/k73SQ3FyUh)
