### ISSUE TITLE
UploadFile re rendering

### ISSUE THREAD

**Issue by AlessandroGussoni** [Chainlit/chainlit#83]
Hi! I was following the Document QA example from the docs and i noticed this
![image](https://github.com/Chainlit/chainlit/assets/55053260/b8f93aa2-d73c-4263-ad0b-b01630b52d45)
Basically if i don't upload a file the app keeps rendering a new UploaFile component every one minute and a half.
Is there a way to prevent this?

**Comment by willydouhard** [comment]
The `AskFileMessage` has a timeout parameter. You can increase the timeout value, here is the doc https://docs.chainlit.io/api-reference/ask/ask-for-file
