### ISSUE TITLE
To turn off the Prompt Playground feature in live?

### ISSUE THREAD

**Issue by hfinda** [Chainlit/chainlit#840]
[features]
"# Show the prompt playground"
prompt_playground = false 

in the config file is not working.

chainlit ver is 0.7.700. I don't want to change the version of chainlit, but I want to turn off Prompt Playground for security purpose?

Should this come under [features] or under [UI] in config file, as at githash e4c81afb5ee35dee8eb2aa093dfecbae77aaf05a, I have noticed that it is mentioned within [UI] but in the config file by default it is mentioned under [features]. By the way, I tried both, but it's not working.

**Comment by ModEnter** [comment]
Hello, since the prompt playground has been deprecated, I guess it solves your issue
