### ISSUE TITLE
Autoplay for cl.audio

### ISSUE THREAD

**Issue by MaxMLang** [Chainlit/chainlit#847]
**Is your feature request related to a problem? Please describe.**
We are currently trying to build a conversational AI app with voice output (reading out the response), and ideally, the player should start automatically. Currently, the user needs to click on the play button (of the CL audio player) first, interrupting the conversation flow. 
**Describe the solution you'd like**
A parameter in `cl.audio(autoplay = true)` such that the audio (player) automatically starts. 
**Describe alternatives you've considered**
We tried implementing the autoplay ourselves in the React frontend and Javascript backend, but it didn't work well.

**Comment by Simon-Stone** [comment]
This is already implemented since version 1.1.0 and the issue should be closed.
