### ISSUE TITLE
Remove the "dark-mode" from the Settings UI

### ISSUE THREAD

**Issue by guisalva** [Chainlit/chainlit#849]
I want to hide the option dark-mode of the settings UI.

There is a way to hide the theme switch from the user ?

I know that I could hide using CSS, but I'd like to know if there is an official and correct way to do it.

**Comment by dahifi** [comment]
It's not supported. CS injection would be the way to go unless you want to fork the FE and remove it entirely.

**Comment by hayescode** [comment]
@dahifi Any tips on CSS injection? It seems react creates random class names so I haven't been able to target specific elements.

**Comment by ModEnter** [comment]
Hello, you can add custom css to hide the button, or overload the dark theme's palette with the light theme ones.
