### ISSUE TITLE
LangChain new-style agents don't show execution steps (when invoked with `avinvoke` and not `arun`)

### ISSUE THREAD

**Issue by omrihar** [Chainlit/chainlit#859]
**Describe the bug**
When using LangChain agents with the langchain callback with ainvoke, no intermediate steps are shown.

**To Reproduce**
Using the following code works, but doesn't show the steps in the execution:
```python
@cl.on_start_chat
async def init():
        prompt = hub.pull("hwchase17/openai-tools-agent")
        agent = create_openai_tools_agent(llm=llm, tools=tools, prompt=prompt)
        agent_executor = AgentExecutor(
            agent=agent, 
            tools=tools, 
            handle_parsing_errors=True, 
            verbose=True,
            return_intermediate_steps=True,
        )
       cl.user_session.set("agent", agent_executor)
# ...
@cl.on_message
async def main(message: cl.Message):
    agent = cl.user_session.get("agent") # type: AgentExecutor
    cb = cl.AsyncLangchainCallbackHandler(stream_final_answer=True)

    result = await agent.ainvoke({"input": message.content}, callbacks=[cb])

    await cl.Message(content=result['output']).send()
```

If I use 
```python
    result = await agent.arun({"input": message.content}, callbacks=[cb])
```
instead, it does show the steps, but does not return the final result back to the agent. 

**Expected behavior**
The final response of the agent is shown including the steps.

**Screenshots**
This is the output when using `arun`:
![image](https://github.com/Chainlit/chainlit/assets/306672/0783906c-5356-460d-828d-95cd29d7e95b)

This is the output when using `ainvoke`:
![image](https://github.com/Chainlit/chainlit/assets/306672/c89b0d4d-3ee6-4e92-83ab-c3ba376ba0be)
so no intermediate steps. If I get `result['output']` the final result is shown nicely, but nothing else.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Additional context**
```python
        agent_executor = initialize_agent(
            tools, 
            llm, 
            agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
            verbose=True
        )
```
using this old-style syntax does work, but it has other drawbacks (this agent doesn't support chat_history, for example) and is deprecated (as is `run` and `arun`).

**Comment by constantinidan** [comment]
Hi @omrihar 

LangChain recently changed their API and now uses a config class.

You need to change this
```
cb = cl.AsyncLangchainCallbackHandler(stream_final_answer=True)
result = await agent.ainvoke({"input": message.content}, callbacks=[cb])
```

to this

```
from langchain_core.runnables.config import RunnableConfig
...
cb = cl.AsyncLangchainCallbackHandler(stream_final_answer=True)
config = RunnableConfig(callbacks=[cb])
result = await agent.ainvoke({"input": message.content}, config=config)
```

**Comment by omrihar** [comment]
Thanks a lot, that works!
I must have missed this in the documentation. Perhaps this example is missing from the chainlit documentation and is worth considering an update?
