### ISSUE TITLE
Issue with error checking in config file (project_id)

### ISSUE THREAD

**Issue by jimmarshall87** [Chainlit/chainlit#86]
I might be wrong, but shouldn't:

`if not project_settings.public and not project_settings.project_id:`

...be:

`if not project_settings.public and not project_settings.id:`

in `config.py`?

I think this may have broken in 0.4.0

**Comment by willydouhard** [comment]
Nice catch, will be fixed in the next release!

**Comment by jimmarshall87** [comment]
Great, now I got one right I will PR the next one I find for you....!

**Comment by willydouhard** [comment]
Awesome, you can follow here https://github.com/Chainlit/chainlit/pull/88
