### ISSUE TITLE
Text box is too small in chat settings

### ISSUE THREAD

**Issue by constantinidan** [Chainlit/chainlit#871]
The text box is too small in the chat settings.
![image](https://github.com/Chainlit/chainlit/assets/16107237/dac13d46-b688-4a46-996f-b73c3222b217)

**Comment by kevinwmerritt** [comment]
Dan not 100% sure, but I made an issue that seems similar yours: https://github.com/Chainlit/chainlit/issues/507

I'm hoping a proper textarea comes to chainlit.

**Comment by josetoaguilera** [comment]
Hey there!, we were looking for the same fix with my coworker and found out there's a multiline argument that you give to the text input class. 
Hope this helps somebody
![image](https://github.com/Chainlit/chainlit/assets/53382772/80830838-4988-4231-8977-cc60ad18546b)
