### ISSUE TITLE
instance of MultiModalFeature, tuple or dict expected (type=type_error.dataclass; class_name=MultiModalFeature)

### ISSUE THREAD

**Issue by ehalit** [Chainlit/chainlit#875]
I have been using chainlit smoothly for a while and I decided to upgrade to the newest version.

After running `pip install -U chainlit` and installation completes, `chainlit hello` fails with the following error:
```
  File "pydantic/dataclasses.py", line 332, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
    in comparison functions.  metadata, if specified, must be a
  File "pydantic/dataclasses.py", line 447, in pydantic.dataclasses._dataclass_validate_values
    # No default factory.
pydantic.error_wrappers.ValidationError: 1 validation error for FeaturesSettings
multi_modal
  instance of MultiModalFeature, tuple or dict expected (type=type_error.dataclass; class_name=MultiModalFeature)
```

**Current System**
 - MacOS Sonoma 14.4
 - Python 3.9.6

**Comment by martinskeem** [comment]
I had a similar error after upgrading. For me it was just a matter of updating `config.toml` with the new way of configuring `multi_modal` as described [here](https://docs.chainlit.io/guides/migration/1.0.500#2-update-the-multi-modal-config-setting)

```
[features.multi_modal]
    enabled = false
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500```

**Comment by ModEnter** [comment]
@martinskeem answered
