### ISSUE TITLE
ConversationalRetrievalChain returning question first while streaming 

### ISSUE THREAD

**Issue by sanket-rudder** [Chainlit/chainlit#890]
I have created simple chatbot using ConversationalRetrievalChain.
I am trying to stream the answer using code below.

@cl.on_message
async def main(message: cl.Message):
    chain = cl.user_session.get("chain")  # type: ConversationalRetrievalChain
    cb = cl.LangchainCallbackHandler(
        stream_final_answer=True,
        force_stream_final_answer=True
    )
    cb.answer_reached = True
    res = await chain.acall(message.content, callbacks=[cb])
    
    
 Streaming is working as expected but I am getting question first in my output and then answer.
 
 
![image](https://github.com/Chainlit/chainlit/assets/166543665/1f34a003-f153-442c-b6b6-d7c8c6bba819)

I tried to use different strings in answer_prefix_tokens as well but nothing changed.

**Comment by ElonTelos** [comment]
could you find the problem ?

**Comment by sanket-rudder** [comment]
> could you find the problem ? I encounter this problem too.

Yes. Use different llm for creating question and set streaming =  False for that one.
Below is example.

question_generator_llm = ChatOpenAI(model_name="gpt-4-0125-preview", temperature=0, streaming=False)
    chain = ConversationalRetrievalChain.from_llm(
        ChatOpenAI(model_name="gpt-4-0125-preview", temperature=0, streaming=True),
        chain_type="stuff",
        retriever=docsearch.as_retriever(),
        memory=memory,
        return_source_documents=False,
        combine_docs_chain_kwargs={"prompt": prompt},
        condense_question_llm = question_generator_llm,
        verbose=False
    )
