### ISSUE TITLE
Unable to serve chainlit frontend on a subpage

### ISSUE THREAD

**Issue by kshitijagrwl** [Chainlit/chainlit#908]
**Describe the bug**

I'm trying to serve chainlit frontend on a remote server where I am already running a few apps. 
On opening <domain>/chainlit in the browser, the request is received by the server(running in debug) but the browser shows `404 not found` for the `.js` and `.css` files

I want to serve the frontend on <domain>/chainlit and here is my nginx config for that: 

```
server {
  server_name your-domain.com;

  location /my-app/ {
    proxy_pass http://localhost:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
```
 I'm running the app using - 
`chainlit run app.py`

I believe this is due to some static routing in the react front end. **What's the best way to handle this?**

**Server config:**
chainlit - 1.0.502
flask - 0.110.1
python - 3.10

**Comment by willydouhard** [comment]
Fixed with the latest release, run `chainlit run app.py --root-path /chainlit`
