### ISSUE TITLE
Unable to utilize OAuth authentication with custom react frontend due to internal URL

### ISSUE THREAD

**Issue by mikkelgthang** [Chainlit/chainlit#911]
When using `@cl.oauth_callback` as described in the [docs](https://docs.chainlit.io/authentication/oauth), `CHAINLIT_URL` can be set to define the backend's URL - which works as expected. However, the `RedirectResponse` defined in [oauth_callback](https://github.com/Chainlit/chainlit/blob/8e532b7e2382f91628c4eb4569b0912abc8af09a/backend/chainlit/server.py#L469C5-L472C6) simply calls `url=f"/login?{params}"`, which means that the callback url wrongly uses the CHAINLIT_URL, and not the frontend's URL that made the request. I can see that it includes a `FIXME` comment, but in case other matters are more pressing, is there potentially any way to overwrite the implementation? I tried to define the same endpoint in my `app.py` file, but it still uses the internal function. Currently, I have no way of returning the token to my custom frontend url detached from `CHAINLIT_URL`. 😃 

Thank you in advance 👏

**Comment by bsuarezSWORD** [comment]
I have the same issue, was any solution found?

**Comment by brii7** [comment]
I have the same issue, was any solution found? Not deploying Chainlit's UI would work, only if the react custom frontend is deployed in the same port (8000). But as per Willy's comment on issue [705](https://github.com/Chainlit/chainlit/issues/705), Chainlit's UI is always declared last and it cannot be overwritten.

**Comment by mikkelgthang** [comment]
@brii7 Unfortunately, there still seems to be no natively working solution available. For this reason, we opted for a manual "hacky" solution, where we post-package-install in our docker image simply replaces the `chainlit/backend/chainlit
/server.py` file with a modified duplicate, replacing `url=f"/login/callback?{params}"` with our custom environment url's.

**Comment by brii7** [comment]
Thank you for your reply and solution. I've also just found out that changing the _custom_build_ paremeter on the _config.toml_ file, enables you to use your own custom UI folder. But it needs to have a specific structure, which is also not 100% convenient.

**Comment by mikkelgthang** [comment]
@brii7 it seems they have fixed this issue in their latest versioning 😄

**Comment by mikkelgthang** [comment]
@brii7 it seems they have fixed this issue in their latest versioning 😄

**Comment by mikkelgthang** [comment]
I was a bit too fast on the trigger, they merely added support for the `CHAINLIT_ROOT_PATH`, which is a path appended to the base `CHAINLIT_URL`, not directly transferrable to custom frontend URL. With their new mounted setup however, perhaps a better solution exists using fastapi overwrite.
