### ISSUE TITLE
Injecting custom javascript code not working

### ISSUE THREAD

**Issue by tituslhy** [Chainlit/chainlit#919]
**Describe the bug**
I'm trying to change the placeholder value of "Email Address" in the chainlit password login page to "Username".

**To Reproduce**
1.  I created a public/test.js file and wrote the code
`document.getElementByID('email').placeholder='Username'`

2. I edited config.toml to specify the custom javascript file

3. I restarted my application
4. I still see "Email Address" instead of "Username" in the login form.

**Comment by b4s36t4** [comment]
@tituslhy if what you wanted is just the changing the `placeholder` of the input you could it via the translations.

for every project you'll be having `.chainlit` folder inside the `translations` folder you can find `en-US.json` file which will be having the all strings that you see on the UI.

You can change the values of the inputs here itself, but you still be have to access value of the username as `email` only.

<img width="556" alt="Screenshot 2024-04-25 at 5 50 42 PM" src="https://github.com/Chainlit/chainlit/assets/59088937/256089f6-8573-4fd2-9439-8a1eadfd4b57">

**Comment by tituslhy** [comment]
Thanks! But can I check why the JavaScript method didn't work? Was there anything wrong with my steps and code? Just in case I want to incorporate more JavaScript code.

**Comment by b4s36t4** [comment]
The chainlit application is running on React whereas you're injecting javascript into the HTML template of React, so by the time your custom javascript executed there won't be any element to run the `querySelector`. 

I think the purpose of custom javascript is to inject custom elements or some third-party integrations or so.

**Comment by tituslhy** [comment]
I see! In that case how do I do up a spinning wheel icon at the login page just to show the user that my app is in the process of authenticating credentials?

**Comment by ylin766** [comment]
Hi, I also have same problem with this part! Did you figure out finally?

**Comment by HeisenbergHK** [comment]
I want to console.log("anything!")

when the page loads, i put the js code inside the customize.js in the public dir, why it won't work!?
