### ISSUE TITLE
Build chainlit frontend such that it can be served from any server.

### ISSUE THREAD

**Issue by NavinKumarMNK** [Chainlit/chainlit#920]
**Is your feature request related to a problem? Please describe.**
Yeah i have a django server where one part of it need to be a chat application. I have my custom `vllm engine` when i would query too for text generation. So i thought of using chainlit as a frontend, but i couldn't integrate it into my application

Things i tried.
- I tried to run the `chainlit/frontend` using pnpm, but i got a `full white screen` (it would be helpful if anyone walks me though this)
- i got the app from `chainlit.server.app`  and mounted it with my fastapi at `/chat` which also mounted my `django asgi` at `/`. even though this works, i couldn't get the complete ui to the front-end
- i also tried setting up nginx and `proxy pass /chat -> localhost:8001 where chainlit is running` and `proxy pass / -> localshot:8000 my django mounted fastapi app`.  Here the django app works fine but when i queried `localhost:9999/chat` (nginx) i am receiving a blank white screen

**Describe the solution you'd like**
It would be helpfull if we could build the frontend alone so that it can be shared from any server.

**Describe alternatives you've considered**
No alternatives for my design. 

**Additional context**

**Comment by seleniumpython2016** [comment]
Why not support flask?
