### ISSUE TITLE
there is no text in login page

### ISSUE THREAD

**Issue by wac81** [Chainlit/chainlit#935]
![image](https://github.com/Chainlit/chainlit/assets/5139426/44b88b97-eb37-4105-9d74-c2a019acfd84)

**Comment by wac81** [comment]
how to fix it ?

**Comment by wac81** [comment]
it's the newest version

**Comment by b4s36t4** [comment]
I think you might have deleted `.chainlit` folder, can you check?!

**Comment by wac81** [comment]
> I think you might have deleted `.chainlit` folder, can you check?!

no，its still there
![image](https://github.com/Chainlit/chainlit/assets/5139426/681c1bbe-23e1-45e4-a81c-c8ea367ee9fa)

**Comment by tpatel** [comment]
Hello, you should delete the translations folder: https://docs.chainlit.io/guides/migration/1.0.500#1-regenerate-translations
