### ISSUE TITLE
Messages are missing from a new thread

### ISSUE THREAD

**Issue by kevinwmerritt** [Chainlit/chainlit#941]
**Describe the bug**
Fresh thread data is not fetched from the API prior to returning to a recently ended chat.

**To Reproduce**
1. Start a chat.
2. Add a few messages to the conversation.
3. Click "New Chat"
4. Click on the most recent thread at the top of "Past Chats"

**Expected behavior**
The full thread of messages should be visible.

**Screenshots**

https://github.com/Chainlit/chainlit/assets/590874/4ce96742-ee2b-4ba6-afcf-f9881c8c990d

**Comment by kaushik0030** [comment]
Hi Everyone,

I am not able to use the "copy to clipboard" via AWS but while running over my local server on my PC it is allowing.

Someone can guide how to fix this bug of Chainlit?
