### ISSUE TITLE
chainlit --version produces: Input should be a dictionary or an instance of MultiModalFeature

### ISSUE THREAD

**Issue by miriam-z** [Chainlit/chainlit#946]
**Describe the bug**

Upgraded:

pip install --upgrade chainlit==1.0.505

chainlit --version

pydantic_core._pydantic_core.ValidationError: 1 validation error for FeaturesSettings
multi_modal
  Input should be a dictionary or an instance of MultiModalFeature [type=dataclass_type, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.5/v/dataclass_type

Is this related to pydantic also needing to be upgraded. 

**To Reproduce**

1. pip install --upgrade chainlit==1.0.505
2. chainlit --version

**Expected behavior**
Chainlit, version 1.0.5xx

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Mac OS
- Browser chrome
- Version 123.0.6312.122

**Comment by AshSid00** [comment]
I am facing the same issue.

**Comment by tpatel** [comment]
Hello, you would need to either:

- remove the entire `./chainlit/config.toml` file and restart your app
- or update the multi_modal setting manually (example [here](https://docs.chainlit.io/backend/config/features#default-configuration))

This is part of the migration to chainlit v1.0.500: https://docs.chainlit.io/guides/migration/1.0.500#2-update-the-multi-modal-config-setting.
