### ISSUE TITLE
How can get message of a specific action

### ISSUE THREAD

**Issue by amirrezam** [Chainlit/chainlit#95]
I set an like/dislike action for all messages. but i don't know how get message related to a specific action ?

**Comment by willydouhard** [comment]
The like / dislike action is already provided by Chainlit in cloud mode. We are currently working on making it available in local mode as well.

In the mean time, you can use the `forId` attribute of the Action class as shown here:

```py
import chainlit as cl



@cl.action_callback("confirm_action")
async def on_action(action: cl.Action):
    print("msg id", action.forId)
    if action.value == "ok":
        content = "Confirmed!"
    elif action.value == "not_ok":
        content = "Rejected!"
    else:
        await cl.ErrorMessage(content="Invalid action").send()
        return

    actions = cl.user_session.get("actions")
    if actions:
        for action in actions:
            await action.remove()
        cl.user_session.set("actions", None)

    await cl.Message(content=content).send()


@cl.on_chat_start
async def start():
    approve_action = cl.Action(name="confirm_action", value="ok", label="Confirm")
    reject_action = cl.Action(name="confirm_action", value="not_ok", label="Reject")
    actions = [approve_action, reject_action]
    cl.user_session.set("actions", actions)

    msg = cl.Message(
        content="Test message",
        actions=actions,
    )

    print("Message id", msg.temp_id)

    await msg.send()
```

If you are using cloud mode, use `msg.id` instead of `msg.temp_id`.

**Comment by amirrezam** [comment]
how we can fetch Message from its msg.id ?

**Comment by willydouhard** [comment]
You can't at the moment, but you can store the messages in the [user_session](https://docs.chainlit.io/concepts/user-session) for now.

**Comment by scooter7** [comment]
Does this mean that the chat histories can be accessed? If so, how and where would the chat histories be viewed? Thanks!

**Comment by willydouhard** [comment]
> Does this mean that the chat histories can be accessed? If so, how and where would the chat histories be viewed? Thanks!

I replied here https://github.com/Chainlit/chainlit/issues/103
