### ISSUE TITLE
Chainlit is unrecognized error in MacOs M1 chip

### ISSUE THREAD

**Issue by RaghuNandan-Srinivas** [Chainlit/chainlit#97]
chainlit run chainlit_mac_app.py -w
- Loaded .env file
usage: chainlit [-h] [--hide-source] [--mute-stream]
chainlit: error: unrecognized arguments: run chainlit_mac_app.py -w

**Comment by masafumimori** [comment]
That is weird?
I am also using M1 chip (Apple M1 Pro) but I can run the command `chainlit run xxx.py -w` fine.

Maybe sharing more info about your environment could help solving this issue?
