### ISSUE TITLE
HIGH SECURITY VIOLATION in cypress/support/utils.ts

### ISSUE THREAD

**Issue by hayescode** [Chainlit/chainlit#983]
**Describe the bug**
My workplace uses Apiiro for security compliance and [this section of code](https://github.com/Chainlit/chainlit/blob/main/cypress/support/utils.ts#L26-L33) gives a high severity security violation.

Error message: `Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')`

References: https://cheatsheetseries.owasp.org/cheatsheets/Nodejs_Security_Cheat_Sheet.html#do-not-use-dangerous-functions

![image](https://github.com/Chainlit/chainlit/assets/35790761/fb34a2f5-d231-471e-ab51-6bf54c36f50d)

**Comment by willydouhard** [comment]
Thank you for the report. This code is only used to orchestrate the CI. It never lands in any Chainlit application.

That being said, it would be nice to clear the warning!

**Comment by dokterbob** [comment]
Looking at the code it, I don't think there's a trivial work around.

Nor an underlying security issue! Note: "[...] if the input is user controllable."

In the CI context _there is no user_, it's simply a wrapper around `execSync()` to ensure that tests are called with proper `pnpm` context. To my knowledge, there's no way to do this without forking, pnpm doesn't have a supported/documented JS API. Nor is this necessary.

Rather, best to tell the security scanner that this is a false positive.

**Comment by dokterbob** [comment]
Closing this as it's a false positive (see comment before).
